// SPDX-FileCopyrightText: 2026 Marcin Kaim
// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileComment: Generated by Gemini 3.8 Flash

package fsutil

import (
	"archive/tar"
	"context"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"time"
)

const (
	// DirMode represents normalized directory permissions (0755).
	DirMode os.FileMode = 0755

	// ExecMode represents normalized executable file permissions (0755).
	ExecMode os.FileMode = 0755

	// FileMode represents normalized standard non-executable file permissions (0644).
	FileMode os.FileMode = 0644

	// DefaultOwnerUID is the deterministic root UID (0).
	DefaultOwnerUID = 0

	// DefaultOwnerGID is the deterministic root GID (0).
	DefaultOwnerGID = 0

	// DefaultOwnerName is the deterministic root owner name ("root").
	DefaultOwnerName = "root"

	// DefaultGroupName is the deterministic root group name ("root").
	DefaultGroupName = "root"
)

// IsExecutable returns true if any of the execute permission bits are set.
func IsExecutable(mode os.FileMode) bool {
	return mode&0111 != 0
}

// NormalizeFileMode returns the normalized permission bits for a given mode:
// 0755 for directories and executables, 0644 for regular files.
func NormalizeFileMode(mode os.FileMode) os.FileMode {
	if mode.IsDir() || IsExecutable(mode) {
		return ExecMode
	}
	return FileMode
}

// NormalizeTarHeader normalizes ownership to root:root (UID/GID 0) and
// resets permission bits to 0755 (dirs/executables) or 0644 (regular files),
// while preserving file modification timestamps for auditing and reproducibility.
func NormalizeTarHeader(hdr *tar.Header, fi os.FileInfo) {
	hdr.Uid = DefaultOwnerUID
	hdr.Gid = DefaultOwnerGID
	hdr.Uname = DefaultOwnerName
	hdr.Gname = DefaultGroupName

	if fi.IsDir() {
		hdr.Typeflag = tar.TypeDir
		hdr.Mode = int64(DirMode)
	} else {
		hdr.Typeflag = tar.TypeReg
		if IsExecutable(fi.Mode()) {
			hdr.Mode = int64(ExecMode)
		} else {
			hdr.Mode = int64(FileMode)
		}
	}

	hdr.ModTime = fi.ModTime()
}

// ClampModTime returns t truncated to second precision, clamped to maxTime if maxTime is non-zero and t is after maxTime.
func ClampModTime(t, maxTime time.Time) time.Time {
	utc := t.UTC().Truncate(time.Second)
	if !maxTime.IsZero() && utc.After(maxTime) {
		return maxTime.UTC().Truncate(time.Second)
	}
	return utc
}

// NormalizeTarHeaderWithEpoch normalizes ownership and file modes, clamping ModTime to epoch if non-zero.
func NormalizeTarHeaderWithEpoch(hdr *tar.Header, fi os.FileInfo, epoch time.Time) {
	NormalizeTarHeader(hdr, fi)
	if !epoch.IsZero() && hdr.ModTime.After(epoch) {
		hdr.ModTime = epoch.UTC().Truncate(time.Second)
	}
}

// ResolveSourceDateEpoch resolves the canonical build timestamp adhering to the Reproducible Builds specification:
// 1. Explicit timestamp if non-zero
// 2. SOURCE_DATE_EPOCH environment variable (decimal unix timestamp)
// 3. Git commit timestamp of HEAD within workspaceDir (git log -1 --pretty=%ct)
// 4. Fallback to current time truncated to seconds.
func ResolveSourceDateEpoch(workspaceDir string, explicitDate time.Time) time.Time {
	if !explicitDate.IsZero() {
		return explicitDate.UTC().Truncate(time.Second)
	}
	if sde := os.Getenv("SOURCE_DATE_EPOCH"); sde != "" {
		if sec, err := strconv.ParseInt(strings.TrimSpace(sde), 10, 64); err == nil {
			return time.Unix(sec, 0).UTC()
		}
	}
	gitDir := workspaceDir
	if gitDir == "" {
		gitDir = "."
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "git", "-C", gitDir, "log", "-1", "--pretty=%ct")
	if out, err := cmd.Output(); err == nil {
		if sec, err := strconv.ParseInt(strings.TrimSpace(string(out)), 10, 64); err == nil {
			return time.Unix(sec, 0).UTC()
		}
	}
	return time.Now().UTC().Truncate(time.Second)
}
