// SPDX-FileCopyrightText: 2026 Marcin Kaim
// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileComment: Generated by Gemini 3.8 Flash

package fsutil

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var (
	// ErrPathTraversal is returned when a path resolves outside the permitted workspace directory.
	ErrPathTraversal = errors.New("path traversal detected: path references location outside workspace")
)

// AssertWithinWorkspace verifies that targetPath resides strictly within workspaceDir,
// defending against directory traversal tricks, parent directory references ('..'),
// absolute path injections, and symbolic links resolving outside the workspace.
// Returns the resolved, clean absolute path on success.
func AssertWithinWorkspace(workspaceDir string, targetPath string) (string, error) {
	if workspaceDir == "" {
		workspaceDir = "."
	}

	absWorkspace, err := filepath.Abs(workspaceDir)
	if err != nil {
		return "", fmt.Errorf("failed to resolve workspace path '%s': %w", workspaceDir, err)
	}

	// Resolve symlinks in workspace directory if it exists
	if evalWorkspace, err := filepath.EvalSymlinks(absWorkspace); err == nil {
		absWorkspace = evalWorkspace
	}
	absWorkspace = filepath.Clean(absWorkspace)

	var fullTarget string
	if filepath.IsAbs(targetPath) {
		fullTarget = filepath.Clean(targetPath)
	} else {
		// Clean the relative target before joining
		cleanRel := filepath.Clean(targetPath)
		if cleanRel == ".." || strings.HasPrefix(cleanRel, ".."+string(filepath.Separator)) {
			return "", fmt.Errorf("%w: relative path '%s' attempts to traverse above root", ErrPathTraversal, targetPath)
		}
		fullTarget = filepath.Clean(filepath.Join(absWorkspace, cleanRel))
	}

	// Lexical containment check: fullTarget must equal absWorkspace or have absWorkspace + separator as prefix
	if fullTarget != absWorkspace && !strings.HasPrefix(fullTarget, absWorkspace+string(filepath.Separator)) {
		return "", fmt.Errorf("%w: target path '%s' resolves to '%s' which is outside workspace '%s'", ErrPathTraversal, targetPath, fullTarget, absWorkspace)
	}

	// If fullTarget exists (or any intermediate symlink exists), verify symlink containment.
	// First check if fullTarget exists directly or via symlink.
	if evalTarget, err := filepath.EvalSymlinks(fullTarget); err == nil {
		evalTarget = filepath.Clean(evalTarget)
		if evalTarget != absWorkspace && !strings.HasPrefix(evalTarget, absWorkspace+string(filepath.Separator)) {
			return "", fmt.Errorf("%w: path '%s' resolves to '%s' outside workspace '%s'", ErrPathTraversal, fullTarget, evalTarget, absWorkspace)
		}
		return evalTarget, nil
	}

	// If fullTarget itself is a symlink whose target does not exist (broken symlink):
	if targetFi, err := os.Lstat(fullTarget); err == nil && targetFi.Mode()&os.ModeSymlink != 0 {
		linkTarget, err := os.Readlink(fullTarget)
		if err != nil {
			return "", fmt.Errorf("failed to read symlink '%s': %w", fullTarget, err)
		}
		var resolvedLink string
		if filepath.IsAbs(linkTarget) {
			resolvedLink = filepath.Clean(linkTarget)
		} else {
			resolvedLink = filepath.Clean(filepath.Join(filepath.Dir(fullTarget), linkTarget))
		}
		if resolvedLink != absWorkspace && !strings.HasPrefix(resolvedLink, absWorkspace+string(filepath.Separator)) {
			return "", fmt.Errorf("%w: symlink '%s' points to '%s' outside workspace '%s'", ErrPathTraversal, fullTarget, resolvedLink, absWorkspace)
		}
		return resolvedLink, nil
	}

	// If fullTarget does not exist, verify that any existing ancestor directories do not
	// escape via symlinks (intermediate directory symlink defense).
	curr := filepath.Dir(fullTarget)
	for {
		if curr == absWorkspace || !strings.HasPrefix(curr, absWorkspace) {
			break
		}
		if _, err := os.Lstat(curr); err == nil {
			evalCurr, err := filepath.EvalSymlinks(curr)
			if err != nil {
				return "", fmt.Errorf("failed to evaluate symlinks for '%s': %w", curr, err)
			}
			evalCurr = filepath.Clean(evalCurr)
			if evalCurr != absWorkspace && !strings.HasPrefix(evalCurr, absWorkspace+string(filepath.Separator)) {
				return "", fmt.Errorf("%w: directory '%s' resolves to '%s' outside workspace '%s'", ErrPathTraversal, curr, evalCurr, absWorkspace)
			}
			// Compute resolved path: replace existing prefix `curr` with `evalCurr`
			rel, err := filepath.Rel(curr, fullTarget)
			if err == nil {
				return filepath.Clean(filepath.Join(evalCurr, rel)), nil
			}
			break
		}
		parent := filepath.Dir(curr)
		if parent == curr {
			break
		}
		curr = parent
	}

	return fullTarget, nil
}

// CollectFiles traverses dirPath recursively, verifying that no paths or symlinks
// escape workspaceDir, and returns relative paths from dirPath sorted alphabetically.
func CollectFiles(dirPath string, workspaceDir string) ([]string, error) {
	absDir, err := AssertWithinWorkspace(workspaceDir, dirPath)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(absDir)
	if err != nil {
		return nil, fmt.Errorf("failed to stat directory '%s': %w", absDir, err)
	}
	if !fi.IsDir() {
		return nil, fmt.Errorf("path '%s' is not a directory", absDir)
	}

	var relPaths []string
	err = filepath.Walk(absDir, func(currentPath string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		// Don't include the root dir itself as a file entry
		if currentPath == absDir {
			return nil
		}

		// Verify that this path is within workspace (including evaluating symlinks)
		if _, err := AssertWithinWorkspace(workspaceDir, currentPath); err != nil {
			return err
		}

		rel, err := filepath.Rel(absDir, currentPath)
		if err != nil {
			return fmt.Errorf("failed to compute relative path for '%s': %w", currentPath, err)
		}

		relPaths = append(relPaths, rel)
		return nil
	})

	if err != nil {
		return nil, err
	}

	sort.Strings(relPaths)
	return relPaths, nil
}

// CopyFile copies a single file from src to dst, creating any required parent
// directories with 0755 permissions and applying normalized permissions to dst.
func CopyFile(src, dst string) error {
	srcFile, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("failed to open source file '%s': %w", src, err)
	}
	defer srcFile.Close()

	srcInfo, err := srcFile.Stat()
	if err != nil {
		return fmt.Errorf("failed to stat source file '%s': %w", src, err)
	}
	if srcInfo.IsDir() {
		return fmt.Errorf("source '%s' is a directory, not a regular file", src)
	}

	if err := os.MkdirAll(filepath.Dir(dst), DirMode); err != nil {
		return fmt.Errorf("failed to create destination directory for '%s': %w", dst, err)
	}

	dstMode := NormalizeFileMode(srcInfo.Mode())
	dstFile, err := os.OpenFile(dst, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, dstMode)
	if err != nil {
		return fmt.Errorf("failed to create destination file '%s': %w", dst, err)
	}
	defer dstFile.Close()

	if _, err := io.Copy(dstFile, srcFile); err != nil {
		return fmt.Errorf("failed to copy data from '%s' to '%s': %w", src, dst, err)
	}

	// Preserve timestamps
	_ = os.Chtimes(dst, srcInfo.ModTime(), srcInfo.ModTime())

	return nil
}

// CopyDir recursively copies the contents of srcDir to dstDir, ensuring all
// source files reside safely within workspaceDir.
func CopyDir(srcDir, dstDir string, workspaceDir string) error {
	absSrc, err := AssertWithinWorkspace(workspaceDir, srcDir)
	if err != nil {
		return err
	}

	fi, err := os.Stat(absSrc)
	if err != nil {
		return fmt.Errorf("failed to stat source directory '%s': %w", absSrc, err)
	}
	if !fi.IsDir() {
		return fmt.Errorf("source '%s' is not a directory", absSrc)
	}

	return filepath.Walk(absSrc, func(currentPath string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		rel, err := filepath.Rel(absSrc, currentPath)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}

		targetDst := filepath.Join(dstDir, rel)

		if info.IsDir() {
			return os.MkdirAll(targetDst, DirMode)
		}

		// Verify source path safety
		if _, err := AssertWithinWorkspace(workspaceDir, currentPath); err != nil {
			return err
		}

		return CopyFile(currentPath, targetDst)
	})
}
