// SPDX-FileCopyrightText: 2026 Marcin Kaim
// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileComment: Generated by Gemini 3.8 Flash

package main

import (
	"context"
	"os"
	"os/signal"
	"syscall"

	"craftpack/pkg/cli"
)

// Build metadata populated via -ldflags at compile time.
var (
	version   string
	gitCommit string
	buildDate string
)

func init() {
	if version != "" {
		cli.Version = version
	}
	if gitCommit != "" {
		cli.GitCommit = gitCommit
	}
	if buildDate != "" {
		cli.BuildDate = buildDate
	}
}

func main() {
	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	code := ExecuteContext(ctx, os.Args[1:])
	os.Exit(code)
}
