// SPDX-FileCopyrightText: 2026 Marcin Kaim
// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileComment: Generated by AI (Gemini 3.8 Flash)

package cli

import (
	"bytes"
	"context"
	"log/slog"
	"os"
	"strings"
	"testing"
	"time"
)

func TestParseLogLevel(t *testing.T) {
	tests := []struct {
		input       string
		expected    slog.Level
		expectError bool
	}{
		{"trace", LevelTrace, false},
		{"TRACE", LevelTrace, false},
		{"debug", slog.LevelDebug, false},
		{"DEBUG", slog.LevelDebug, false},
		{"info", slog.LevelInfo, false},
		{"INFO", slog.LevelInfo, false},
		{"warn", slog.LevelWarn, false},
		{"warning", slog.LevelWarn, false},
		{"WARN", slog.LevelWarn, false},
		{"error", slog.LevelError, false},
		{"ERROR", slog.LevelError, false},
		{"invalid", slog.LevelInfo, true},
		{"", slog.LevelInfo, true},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got, err := ParseLogLevel(tt.input)
			if tt.expectError && err == nil {
				t.Errorf("ParseLogLevel(%q) expected error, got nil", tt.input)
			}
			if !tt.expectError && err != nil {
				t.Errorf("ParseLogLevel(%q) unexpected error: %v", tt.input, err)
			}
			if !tt.expectError && got != tt.expected {
				t.Errorf("ParseLogLevel(%q) = %v, want %v", tt.input, got, tt.expected)
			}
		})
	}
}

func TestResolveLogLevel_LWW(t *testing.T) {
	tests := []struct {
		name        string
		args        []string
		env         string
		expected    slog.Level
		expectError bool
	}{
		{
			name:     "default info when no flags or env",
			args:     []string{},
			env:      "",
			expected: slog.LevelInfo,
		},
		{
			name:     "env variable fallback",
			args:     []string{},
			env:      "debug",
			expected: slog.LevelDebug,
		},
		{
			name:        "invalid env variable returns error",
			args:        []string{},
			env:         "unknown_level",
			expectError: true,
		},
		{
			name:     "single -v flag produces DEBUG",
			args:     []string{"-v"},
			env:      "error",
			expected: slog.LevelDebug,
		},
		{
			name:     "--verbose flag produces DEBUG",
			args:     []string{"--verbose"},
			expected: slog.LevelDebug,
		},
		{
			name:     "double -v (-vv) produces TRACE",
			args:     []string{"-vv"},
			expected: LevelTrace,
		},
		{
			name:     "two -v flags produces TRACE",
			args:     []string{"-v", "-v"},
			expected: LevelTrace,
		},
		{
			name:     "-q flag produces ERROR",
			args:     []string{"-q"},
			expected: slog.LevelError,
		},
		{
			name:     "--quiet flag produces ERROR",
			args:     []string{"--quiet"},
			expected: slog.LevelError,
		},
		{
			name:     "--silent flag produces ERROR",
			args:     []string{"--silent"},
			expected: slog.LevelError,
		},
		{
			name:     "LWW: --verbose then --quiet -> ERROR",
			args:     []string{"--verbose", "--quiet"},
			expected: slog.LevelError,
		},
		{
			name:     "LWW: --quiet then --verbose -> DEBUG",
			args:     []string{"--quiet", "--verbose"},
			expected: slog.LevelDebug,
		},
		{
			name:     "LWW: -q then -v -> DEBUG",
			args:     []string{"-q", "-v"},
			expected: slog.LevelDebug,
		},
		{
			name:     "LWW: -v then -q -> ERROR",
			args:     []string{"-v", "-q"},
			expected: slog.LevelError,
		},
		{
			name:     "LWW: chained -vq -> ERROR",
			args:     []string{"-vq"},
			expected: slog.LevelError,
		},
		{
			name:     "LWW: chained -qv -> DEBUG",
			args:     []string{"-qv"},
			expected: slog.LevelDebug,
		},
		{
			name:     "LWW: -q then -vv -> TRACE",
			args:     []string{"-q", "-vv"},
			expected: LevelTrace,
		},
		{
			name:     "--log-level explicit value",
			args:     []string{"--log-level", "warn"},
			expected: slog.LevelWarn,
		},
		{
			name:     "--log-level=trace syntax",
			args:     []string{"--log-level=trace"},
			expected: LevelTrace,
		},
		{
			name:     "LWW: -v then --log-level=warn -> WARN",
			args:     []string{"-v", "--log-level=warn"},
			expected: slog.LevelWarn,
		},
		{
			name:     "LWW: --log-level=warn then -v -> DEBUG",
			args:     []string{"--log-level=warn", "-v"},
			expected: slog.LevelDebug,
		},
		{
			name:        "invalid --log-level returns error",
			args:        []string{"--log-level=foobar"},
			expectError: true,
		},
		{
			name:     "LWW: chained -vvq -> ERROR",
			args:     []string{"-vvq"},
			expected: slog.LevelError,
		},
		{
			name:     "LWW: chained -qvv -> TRACE",
			args:     []string{"-qvv"},
			expected: LevelTrace,
		},
		{
			name:     "LWW: chained -vqv -> DEBUG",
			args:     []string{"-vqv"},
			expected: slog.LevelDebug,
		},
		{
			name:     "LWW: CLI -v overrides env error",
			args:     []string{"-v"},
			env:      "error",
			expected: slog.LevelDebug,
		},
		{
			name:     "LWW: CLI -q overrides env trace",
			args:     []string{"-q"},
			env:      "trace",
			expected: slog.LevelError,
		},
		{
			name:     "LWW: CLI --log-level overrides env",
			args:     []string{"--log-level=warn"},
			env:      "debug",
			expected: slog.LevelWarn,
		},
		{
			name:     "env case-insensitive and whitespace trimmed",
			args:     []string{},
			env:      "  TRACE  ",
			expected: LevelTrace,
		},
		{
			name:     "flags after double dash are ignored",
			args:     []string{"--", "-v", "-q"},
			expected: slog.LevelInfo,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ResolveLogLevel(tt.args, tt.env)
			if tt.expectError && err == nil {
				t.Errorf("ResolveLogLevel() expected error, got nil")
			}
			if !tt.expectError && err != nil {
				t.Errorf("ResolveLogLevel() unexpected error: %v", err)
			}
			if !tt.expectError && got != tt.expected {
				t.Errorf("ResolveLogLevel() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func TestColorEnabled(t *testing.T) {
	origNoColor := os.Getenv("NO_COLOR")
	origTerm := os.Getenv("TERM")
	defer func() {
		os.Setenv("NO_COLOR", origNoColor)
		os.Setenv("TERM", origTerm)
	}()

	var buf bytes.Buffer

	// Buffer is not a TTY
	if ColorEnabled(&buf) {
		t.Errorf("ColorEnabled(buffer) should be false")
	}

	// NO_COLOR set
	os.Setenv("NO_COLOR", "1")
	if ColorEnabled(os.Stderr) {
		t.Errorf("ColorEnabled with NO_COLOR=1 should be false")
	}

	// TERM=dumb
	os.Unsetenv("NO_COLOR")
	os.Setenv("TERM", "dumb")
	if ColorEnabled(os.Stderr) {
		t.Errorf("ColorEnabled with TERM=dumb should be false")
	}
}

func TestCLIHandler_Formatting(t *testing.T) {
	var buf bytes.Buffer
	handler := NewCLIHandler(&buf, CLIHandlerOptions{
		Level: slog.LevelInfo,
		Color: false,
	})

	ctx := context.Background()

	// 1. Info record
	rInfo := slog.NewRecord(time.Now(), slog.LevelInfo, "Building target", 0)
	rInfo.AddAttrs(slog.String("target", "deb"), slog.Int("count", 42))
	if err := handler.Handle(ctx, rInfo); err != nil {
		t.Fatalf("Handle info failed: %v", err)
	}

	got := buf.String()
	if !strings.Contains(got, "[INFO ] Building target target=deb count=42\n") {
		t.Errorf("Handler output unexpected: %q", got)
	}

	// 2. Filtered record (debug when level is info)
	if handler.Enabled(ctx, slog.LevelDebug) {
		t.Errorf("Debug should not be enabled when level is info")
	}

	// 3. WithAttrs
	buf.Reset()
	attrHandler := handler.WithAttrs([]slog.Attr{slog.String("pkg", "craftpack")})
	rWarn := slog.NewRecord(time.Now(), slog.LevelWarn, "Deprecation notice", 0)
	if err := attrHandler.Handle(ctx, rWarn); err != nil {
		t.Fatalf("Handle warn failed: %v", err)
	}
	got = buf.String()
	if !strings.Contains(got, "[WARN ] Deprecation notice pkg=craftpack\n") {
		t.Errorf("Handler output unexpected: %q", got)
	}

	// 4. WithGroup
	buf.Reset()
	groupHandler := handler.WithGroup("meta")
	rGroup := slog.NewRecord(time.Now(), slog.LevelError, "Failure", 0)
	rGroup.AddAttrs(slog.String("code", "E01"))
	if err := groupHandler.Handle(ctx, rGroup); err != nil {
		t.Fatalf("Handle error failed: %v", err)
	}
	got = buf.String()
	if !strings.Contains(got, "[ERROR] Failure meta.code=E01\n") {
		t.Errorf("Handler output unexpected: %q", got)
	}
}

func TestCLIHandler_Color(t *testing.T) {
	var buf bytes.Buffer
	handler := NewCLIHandler(&buf, CLIHandlerOptions{
		Level: LevelTrace,
		Color: true,
	})

	ctx := context.Background()
	rTrace := slog.NewRecord(time.Date(2026, 1, 1, 12, 0, 0, 0, time.UTC), LevelTrace, "Tracing detail", 0)
	if err := handler.Handle(ctx, rTrace); err != nil {
		t.Fatalf("Handle trace failed: %v", err)
	}

	got := buf.String()
	if !strings.Contains(got, ansiMagenta+"[TRACE]"+ansiReset) {
		t.Errorf("Expected ANSI color for TRACE, got: %q", got)
	}
	if !strings.Contains(got, "12:00:00.000") {
		t.Errorf("Expected timestamp in trace output, got: %q", got)
	}
}

func TestSetupLogger(t *testing.T) {
	var buf bytes.Buffer
	logger := SetupLogger(&buf, slog.LevelInfo, false)
	if logger == nil {
		t.Fatalf("SetupLogger returned nil")
	}

	slog.Info("Global log message", "key", "val")
	got := buf.String()
	if !strings.Contains(got, "[INFO ] Global log message key=val\n") {
		t.Errorf("SetupLogger output unexpected: %q", got)
	}
}

func TestCLIHandler_QuotedAttributes(t *testing.T) {
	var buf bytes.Buffer
	handler := NewCLIHandler(&buf, CLIHandlerOptions{
		Level: slog.LevelInfo,
		Color: false,
	})

	ctx := context.Background()
	r := slog.NewRecord(time.Now(), slog.LevelInfo, "Quoting test", 0)
	r.AddAttrs(
		slog.String("simple", "hello"),
		slog.String("with_spaces", "value with spaces"),
		slog.String("with_quotes", `value "with" quotes`),
	)

	if err := handler.Handle(ctx, r); err != nil {
		t.Fatalf("Handle failed: %v", err)
	}

	got := buf.String()
	if !strings.Contains(got, `simple=hello`) {
		t.Errorf("expected simple=hello: %q", got)
	}
	if !strings.Contains(got, `with_spaces="value with spaces"`) {
		t.Errorf("expected with_spaces quoted: %q", got)
	}
	if !strings.Contains(got, `with_quotes="value \"with\" quotes"`) {
		t.Errorf("expected with_quotes escaped: %q", got)
	}
}

func TestCLIHandler_LevelTraceFiltering(t *testing.T) {
	var buf bytes.Buffer

	// When handler is at LevelDebug, LevelTrace records should be suppressed
	handlerDebug := NewCLIHandler(&buf, CLIHandlerOptions{
		Level: slog.LevelDebug,
		Color: false,
	})
	if handlerDebug.Enabled(context.Background(), LevelTrace) {
		t.Errorf("LevelTrace should not be enabled on Debug handler")
	}

	// When handler is at LevelTrace, LevelTrace records should be enabled
	handlerTrace := NewCLIHandler(&buf, CLIHandlerOptions{
		Level: LevelTrace,
		Color: false,
	})
	if !handlerTrace.Enabled(context.Background(), LevelTrace) {
		t.Errorf("LevelTrace should be enabled on Trace handler")
	}
}

func TestResolveLogLevel_ShortFlagsEdgeCases(t *testing.T) {
	tests := []struct {
		name        string
		args        []string
		wantLevel   slog.Level
		expectError bool
		errContains string
	}{
		{
			name:        "missing argument for --log-level at end of args",
			args:        []string{"--log-level"},
			expectError: true,
			errContains: "flag needs an argument: --log-level",
		},
		{
			name:        "empty --log-level=",
			args:        []string{"--log-level="},
			expectError: true,
			errContains: "invalid log level",
		},
		{
			name:      "path with 'v' in attached flag does not trigger verbose",
			args:      []string{"-s/var/log/app.yml"},
			wantLevel: slog.LevelInfo,
		},
		{
			name:      "output path with 'v' does not trigger verbose",
			args:      []string{"-o/tmp/version_output"},
			wantLevel: slog.LevelInfo,
		},
		{
			name:      "spec path with 'q' does not trigger quiet",
			args:      []string{"-s/quiet/spec.yml"},
			wantLevel: slog.LevelInfo,
		},
		{
			name:      "target deb does not trigger anything",
			args:      []string{"-tdeb"},
			wantLevel: slog.LevelInfo,
		},
		{
			name:      "version and verbose combo -Vv produces DEBUG",
			args:      []string{"-Vv"},
			wantLevel: slog.LevelDebug,
		},
		{
			name:      "verbose and version combo -vV produces DEBUG",
			args:      []string{"-vV"},
			wantLevel: slog.LevelDebug,
		},
		{
			name:      "verbose and help combo -vh produces DEBUG",
			args:      []string{"-vh"},
			wantLevel: slog.LevelDebug,
		},
		{
			name:      "help flag -h produces INFO",
			args:      []string{"-h"},
			wantLevel: slog.LevelInfo,
		},
		{
			name:      "version flag -V produces INFO",
			args:      []string{"-V"},
			wantLevel: slog.LevelInfo,
		},
		{
			name:      "single dash '-' does not panic or alter state",
			args:      []string{"-"},
			wantLevel: slog.LevelInfo,
		},
		{
			name:      "single dash followed by -v produces DEBUG",
			args:      []string{"-", "-v"},
			wantLevel: slog.LevelDebug,
		},
		{
			name:      "unknown flag stopping bundle parsing: -xv produces INFO",
			args:      []string{"-xv"},
			wantLevel: slog.LevelInfo,
		},
		{
			name:      "bundle with 'v' before unknown flag: -vx produces DEBUG",
			args:      []string{"-vx"},
			wantLevel: slog.LevelDebug,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ResolveLogLevel(tt.args, "")
			if tt.expectError {
				if err == nil {
					t.Fatalf("expected error containing %q, got nil", tt.errContains)
				}
				if !strings.Contains(err.Error(), tt.errContains) {
					t.Errorf("error %q does not contain %q", err.Error(), tt.errContains)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != tt.wantLevel {
				t.Errorf("ResolveLogLevel(%v) = %v, want %v", tt.args, got, tt.wantLevel)
			}
		})
	}
}

func TestIsTTY_And_ColorEnabled_EdgeCases(t *testing.T) {
	// 1. IsTTY with a regular temporary file (not a terminal)
	tmpFile, err := os.CreateTemp(t.TempDir(), "not-a-tty")
	if err != nil {
		t.Fatalf("failed to create temp file: %v", err)
	}
	defer tmpFile.Close()

	if IsTTY(tmpFile) {
		t.Errorf("IsTTY(tmpFile) should return false for a regular disk file")
	}

	// 2. IsTTY with non-*os.File io.Writer
	var buf bytes.Buffer
	if IsTTY(&buf) {
		t.Errorf("IsTTY(&bytes.Buffer) should return false")
	}

	// 3. ColorEnabled with NO_COLOR="0" (non-empty disables color)
	origNoColor := os.Getenv("NO_COLOR")
	origTerm := os.Getenv("TERM")
	defer func() {
		os.Setenv("NO_COLOR", origNoColor)
		os.Setenv("TERM", origTerm)
	}()

	os.Setenv("NO_COLOR", "0")
	if ColorEnabled(tmpFile) {
		t.Errorf("ColorEnabled with NO_COLOR='0' should be false")
	}

	// 4. ColorEnabled with NO_COLOR="" (empty string does not disable color by itself)
	os.Setenv("NO_COLOR", "")
	os.Setenv("TERM", "xterm-256color")
	// Still false on tmpFile because it's not a TTY
	if ColorEnabled(tmpFile) {
		t.Errorf("ColorEnabled(tmpFile) should be false even when NO_COLOR is empty")
	}
}

type testMaskedSecret string

func (s testMaskedSecret) LogValue() slog.Value {
	return slog.StringValue("***REDACTED***")
}

func TestCLIHandler_EdgeCases(t *testing.T) {
	ctx := context.Background()

	// 1. Nil writer defaults to io.Discard without crashing
	handlerNilWriter := NewCLIHandler(nil, CLIHandlerOptions{
		Level: nil, // defaults to LevelInfo
	})
	if handlerNilWriter.opts.Level != slog.LevelInfo {
		t.Errorf("nil opts.Level should default to slog.LevelInfo")
	}
	r := slog.NewRecord(time.Now(), slog.LevelInfo, "discarded message", 0)
	if err := handlerNilWriter.Handle(ctx, r); err != nil {
		t.Errorf("Handle with nil writer should succeed into io.Discard, got: %v", err)
	}

	// 2. Zero Time in DEBUG record defaults to time.Now()
	var buf bytes.Buffer
	handlerDebug := NewCLIHandler(&buf, CLIHandlerOptions{
		Level: slog.LevelDebug,
		Color: false,
	})
	rZeroTime := slog.NewRecord(time.Time{}, slog.LevelDebug, "debug with zero time", 0)
	if err := handlerDebug.Handle(ctx, rZeroTime); err != nil {
		t.Fatalf("Handle failed: %v", err)
	}
	if !strings.Contains(buf.String(), "[DEBUG] debug with zero time") {
		t.Errorf("expected debug output with timestamp, got: %q", buf.String())
	}

	// 3. Custom LogValuer resolving
	buf.Reset()
	rSecret := slog.NewRecord(time.Now(), slog.LevelInfo, "auth attempt", 0)
	rSecret.AddAttrs(slog.Any("token", testMaskedSecret("secret-token-12345")))
	if err := handlerNilWriter.Handle(ctx, rSecret); err != nil {
		t.Fatalf("Handle failed: %v", err)
	}

	handlerWithBuf := NewCLIHandler(&buf, CLIHandlerOptions{Level: slog.LevelInfo})
	if err := handlerWithBuf.Handle(ctx, rSecret); err != nil {
		t.Fatalf("Handle failed: %v", err)
	}
	if !strings.Contains(buf.String(), "token=***REDACTED***") {
		t.Errorf("LogValuer was not resolved properly: %q", buf.String())
	}

	// 4. Nested slog.KindGroup support
	buf.Reset()
	rGroup := slog.NewRecord(time.Now(), slog.LevelInfo, "telemetry", 0)
	rGroup.AddAttrs(
		slog.Group("system",
			slog.Int("cpu_pct", 45),
			slog.String("hostname", "build-node-1"),
		),
		slog.Group("", // anonymous group inlined
			slog.String("flat_key", "flat_val"),
		),
		slog.Group("empty_group"), // empty group omitted
		slog.Attr{},               // empty attr omitted
	)
	if err := handlerWithBuf.Handle(ctx, rGroup); err != nil {
		t.Fatalf("Handle group failed: %v", err)
	}
	groupOut := buf.String()
	if !strings.Contains(groupOut, "system.cpu_pct=45") {
		t.Errorf("expected system.cpu_pct=45 in: %q", groupOut)
	}
	if !strings.Contains(groupOut, "system.hostname=build-node-1") {
		t.Errorf("expected system.hostname=build-node-1 in: %q", groupOut)
	}
	if !strings.Contains(groupOut, "flat_key=flat_val") {
		t.Errorf("expected flat_key=flat_val in: %q", groupOut)
	}
	if strings.Contains(groupOut, "empty_group") {
		t.Errorf("empty_group should not be present in: %q", groupOut)
	}

	// 5. WithGroup("") returns same handler without error
	hSame := handlerWithBuf.WithGroup("")
	if hSame != handlerWithBuf {
		t.Errorf("WithGroup(\"\") should return the same handler receiver")
	}

	// 6. Group isolation: With(a) -> WithGroup(g) -> With(b)
	buf.Reset()
	hIsolated := handlerWithBuf.WithAttrs([]slog.Attr{slog.String("root_key", "root_val")}).
		WithGroup("subsystem").
		WithAttrs([]slog.Attr{slog.String("child_key", "child_val")})

	rIsolated := slog.NewRecord(time.Now(), slog.LevelInfo, "isolated msg", 0)
	rIsolated.AddAttrs(slog.String("record_key", "record_val"))
	if err := hIsolated.Handle(ctx, rIsolated); err != nil {
		t.Fatalf("Handle failed: %v", err)
	}
	isoOut := buf.String()
	if !strings.Contains(isoOut, "root_key=root_val") {
		t.Errorf("root_key should NOT have subsystem prefix: %q", isoOut)
	}
	if !strings.Contains(isoOut, "subsystem.child_key=child_val") {
		t.Errorf("child_key should have subsystem prefix: %q", isoOut)
	}
	if !strings.Contains(isoOut, "subsystem.record_key=record_val") {
		t.Errorf("record_key should have subsystem prefix: %q", isoOut)
	}

	// 7. Format Level full coverage (Trace, Debug, Info, Warn, Error, and higher)
	levelsToTest := []struct {
		lvl      slog.Level
		color    bool
		wantTag  string
		wantCode string
	}{
		{LevelTrace, true, "[TRACE]", ansiMagenta},
		{LevelTrace, false, "[TRACE]", ""},
		{slog.LevelDebug, true, "[DEBUG]", ansiCyan},
		{slog.LevelDebug, false, "[DEBUG]", ""},
		{slog.LevelInfo, true, "[INFO ]", ansiGreen},
		{slog.LevelInfo, false, "[INFO ]", ""},
		{slog.LevelWarn, true, "[WARN ]", ansiYellow},
		{slog.LevelWarn, false, "[WARN ]", ""},
		{slog.LevelError, true, "[ERROR]", ansiRed},
		{slog.LevelError, false, "[ERROR]", ""},
		{slog.LevelError + 4, true, "[ERROR]", ansiRed},
		{slog.LevelError + 4, false, "[ERROR]", ""},
	}

	for _, tc := range levelsToTest {
		res := formatLevel(tc.lvl, tc.color)
		if !strings.Contains(res, tc.wantTag) {
			t.Errorf("formatLevel(%v, %v) = %q, want tag %q", tc.lvl, tc.color, res, tc.wantTag)
		}
		if tc.color && !strings.Contains(res, tc.wantCode) {
			t.Errorf("formatLevel(%v, %v) missing color code %q", tc.lvl, tc.color, tc.wantCode)
		}
	}

	// 8. formatAttr quoting characters (\n, \t)
	buf.Reset()
	rSpecial := slog.NewRecord(time.Now(), slog.LevelInfo, "newlines and tabs", 0)
	rSpecial.AddAttrs(
		slog.String("tabbed", "value\twith\ttab"),
		slog.String("multiline", "line1\nline2"),
	)
	if err := handlerWithBuf.Handle(ctx, rSpecial); err != nil {
		t.Fatalf("Handle failed: %v", err)
	}
	specOut := buf.String()
	if !strings.Contains(specOut, `tabbed="value\twith\ttab"`) {
		t.Errorf("expected escaped tab: %q", specOut)
	}
	if !strings.Contains(specOut, `multiline="line1\nline2"`) {
		t.Errorf("expected escaped newline: %q", specOut)
	}
}
