// SPDX-FileCopyrightText: 2026 Marcin Kaim
// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileComment: Generated by AI (Gemini 3.8 Flash)

package builder

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"craftpack/pkg/fsutil"
	"craftpack/pkg/spec"
	"craftpack/pkg/target"
)

func TestBuildContext_EdgePaths(t *testing.T) {
	// 1. Absolute SpecPath
	absSpec := "/tmp/test/craftpack.yml"
	bCtx1, err := NewBuildContext(BuildOptions{SpecPath: absSpec})
	if err != nil {
		t.Fatalf("NewBuildContext failed: %v", err)
	}
	if bCtx1.Options.WorkspaceDir != "/tmp/test" {
		t.Errorf("expected WorkspaceDir '/tmp/test', got '%s'", bCtx1.Options.WorkspaceDir)
	}

	// 2. Relative subpath SpecPath
	relSpec := "sub/folder/craftpack.yml"
	bCtx2, err := NewBuildContext(BuildOptions{SpecPath: relSpec})
	if err != nil {
		t.Fatalf("NewBuildContext failed: %v", err)
	}
	if !strings.HasSuffix(bCtx2.Options.WorkspaceDir, filepath.Join("sub", "folder")) {
		t.Errorf("expected WorkspaceDir to end with 'sub/folder', got '%s'", bCtx2.Options.WorkspaceDir)
	}

	// 3. DataDir before staging allocation
	bCtx3, _ := NewBuildContext(BuildOptions{})
	if bCtx3.DataDir() != "" {
		t.Errorf("expected empty DataDir before EnsureStagingDir, got '%s'", bCtx3.DataDir())
	}
}

func TestManifest_ExtendedCoverage(t *testing.T) {
	// 1. ReadManifest on non-existent file
	if _, err := ReadManifest("/nonexistent/path/checksums.sha256"); err == nil {
		t.Errorf("expected error reading non-existent manifest, got nil")
	}

	// 2. ReadManifest with comment lines, blank lines, and valid lines
	tmpDir, err := os.MkdirTemp("", "manifest-test-*")
	if err != nil {
		t.Fatalf("failed creating temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	manifestFile := filepath.Join(tmpDir, "checksums.sha256")
	content := "# This is a comment\n\n   \n" +
		strings.Repeat("a", 64) + "  pkg1.deb  (100 bytes)\n" +
		"# Another comment\n" +
		strings.Repeat("b", 64) + "  pkg2.deb  (200 bytes)\n"
	if err := os.WriteFile(manifestFile, []byte(content), fsutil.FileMode); err != nil {
		t.Fatalf("failed writing manifest file: %v", err)
	}

	entries, err := ReadManifest(manifestFile)
	if err != nil {
		t.Fatalf("ReadManifest failed: %v", err)
	}
	if len(entries) != 2 {
		t.Fatalf("expected 2 entries, got %d", len(entries))
	}
	if entries[0].Filename != "pkg1.deb" || entries[1].Filename != "pkg2.deb" {
		t.Errorf("unexpected entries: %+v", entries)
	}

	// 3. ReadManifest with malformed line
	badContent := strings.Repeat("a", 64) + "  pkg1.deb  (100 bytes)\nthis is bad\n"
	badFile := filepath.Join(tmpDir, "bad_checksums.sha256")
	if err := os.WriteFile(badFile, []byte(badContent), fsutil.FileMode); err != nil {
		t.Fatalf("failed writing bad manifest: %v", err)
	}
	if _, err := ReadManifest(badFile); err == nil {
		t.Errorf("expected error on malformed manifest line, got nil")
	}

	// 4. ParseManifestEntry with size overflow
	overflowLine := strings.Repeat("a", 64) + "  pkg.deb  (99999999999999999999999999999999999999999 bytes)"
	if _, err := ParseManifestEntry(overflowLine); err == nil {
		t.Errorf("expected error on size overflow, got nil")
	}

	// 5. WriteOrUpdateManifest error when parent directory is a regular file
	dummyFile := filepath.Join(tmpDir, "regular_file")
	if err := os.WriteFile(dummyFile, []byte("data"), fsutil.FileMode); err != nil {
		t.Fatalf("failed creating regular file: %v", err)
	}
	invalidManifestPath := filepath.Join(dummyFile, "checksums.sha256")
	if err := WriteOrUpdateManifest(invalidManifestPath, strings.Repeat("a", 64), "pkg.deb", 100); err == nil {
		t.Errorf("expected error when manifest dir is a file, got nil")
	}
}

func TestOrchestrator_NilContextAndEmptyVersion(t *testing.T) {
	orchestrator := NewOrchestrator()

	// Nil context
	if _, err := orchestrator.Build(context.Background(), nil); err == nil {
		t.Errorf("expected error with nil BuildContext, got nil")
	}

	// Empty version after normalization
	bCtx, _ := NewBuildContext(BuildOptions{
		Target:         "deb",
		PackageVersion: "   v   ",
	})
	if _, err := orchestrator.Build(context.Background(), bCtx); err == nil {
		t.Errorf("expected error when package version normalizes to empty, got nil")
	}

	// BuildWithOptions passing invalid options
	if _, err := orchestrator.BuildWithOptions(context.Background(), BuildOptions{
		Target:         "deb",
		PackageVersion: "v",
	}); err == nil {
		t.Errorf("expected error with invalid version in BuildWithOptions, got nil")
	}
}

func TestOrchestrator_DefaultOptionsAndSkippedStages(t *testing.T) {
	dir, err := os.MkdirTemp("", "craftpack-defaults-test-*")
	if err != nil {
		t.Fatalf("failed creating temp dir: %v", err)
	}
	defer os.RemoveAll(dir)

	// Minimal config with no man pages, no default config
	specContent := `
name: minimalapp
description: Minimal Application Test
maintainer: Developer <dev@example.com>
homepage: https://example.com/min
license: MIT
command: min
payload_dir: src
entrypoint: nested/deep/script.sh
targets:
  deb:
    section: utils
`
	if err := os.WriteFile(filepath.Join(dir, "craftpack.yml"), []byte(strings.TrimSpace(specContent)), fsutil.FileMode); err != nil {
		t.Fatalf("failed writing craftpack.yml: %v", err)
	}

	// Create nested directory in payload with an executable and regular file
	nestedDir := filepath.Join(dir, "src", "nested", "deep")
	if err := os.MkdirAll(nestedDir, fsutil.DirMode); err != nil {
		t.Fatalf("failed creating nested dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(nestedDir, "script.sh"), []byte("#!/bin/sh\n"), fsutil.ExecMode); err != nil {
		t.Fatalf("failed creating script: %v", err)
	}
	if err := os.WriteFile(filepath.Join(nestedDir, "read.txt"), []byte("text\n"), fsutil.FileMode); err != nil {
		t.Fatalf("failed creating read.txt: %v", err)
	}

	// Build with empty Architecture, zero BuildDate, empty OutputDir, empty SpecPath (defaults to craftpack.yml)
	orchestrator := NewOrchestrator()
	opts := BuildOptions{
		WorkspaceDir:   dir,
		SpecPath:       "", // should default to craftpack.yml
		PackageVersion: "1.0.0",
		Target:         "deb",
		Architecture:   "", // should default to host architecture
		BuildDate:      time.Time{}, // should default to time.Now()
		OutputDir:      "", // should default to ./dist
	}

	res, err := orchestrator.BuildWithOptions(context.Background(), opts)
	if err != nil {
		t.Fatalf("BuildWithOptions failed: %v", err)
	}
	if !res.Success {
		t.Errorf("expected success")
	}
	if res.Architecture == "" {
		t.Errorf("expected non-empty auto-detected architecture")
	}
	defer os.RemoveAll(filepath.Dir(res.PackageFile))

	// Verify file was written
	if _, err := os.Stat(res.PackageFile); err != nil {
		t.Errorf("package file not created: %v", err)
	}
}

func TestOrchestrator_DefaultConfigMissingFile(t *testing.T) {
	dir, err := os.MkdirTemp("", "craftpack-missing-conf-*")
	if err != nil {
		t.Fatalf("failed creating temp dir: %v", err)
	}
	defer os.RemoveAll(dir)

	// craftpack.yml referencing a missing config file
	specContent := `
name: badconfapp
description: Bad Conf Application
maintainer: Developer <dev@example.com>
homepage: https://example.com/bad
license: MIT
payload_dir: src
default_config:
  missing.conf: test.conf
targets:
  deb:
    section: utils
`
	if err := os.WriteFile(filepath.Join(dir, "craftpack.yml"), []byte(strings.TrimSpace(specContent)), fsutil.FileMode); err != nil {
		t.Fatalf("failed writing craftpack.yml: %v", err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "src"), fsutil.DirMode); err != nil {
		t.Fatalf("failed creating src: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "src", "file.txt"), []byte("content"), fsutil.FileMode); err != nil {
		t.Fatalf("failed writing payload file: %v", err)
	}

	orchestrator := NewOrchestrator()
	opts := BuildOptions{
		WorkspaceDir:   dir,
		SpecPath:       "craftpack.yml",
		PackageVersion: "1.0.0",
		Target:         "deb",
	}

	// Schema validator will catch missing.conf in stage 1
	if _, err := orchestrator.BuildWithOptions(context.Background(), opts); err == nil {
		t.Errorf("expected error due to missing default_config file, got nil")
	}
}

func TestOrchestrator_CancelAtStages(t *testing.T) {
	stagesToTest := []Stage{
		Stage2StagingPayload,
		Stage3Launcher,
		Stage4Documentation,
		Stage5TargetMetadata,
		Stage6Archive,
		Stage7ManifestCleanup,
	}

	for _, targetStage := range stagesToTest {
		t.Run(string(targetStage), func(t *testing.T) {
			workspace, cleanup := setupMockWorkspace(t)
			defer cleanup()

			orchestrator := NewOrchestrator()
			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()

			opts := BuildOptions{
				WorkspaceDir:   workspace,
				SpecPath:       "craftpack.yml",
				PackageVersion: "1.0.0",
				Target:         "deb",
				OnStage: func(stage Stage, detail string) {
					if stage == targetStage {
						cancel()
					}
				},
			}

			_, err := orchestrator.BuildWithOptions(ctx, opts)
			if err == nil {
				t.Fatalf("expected error on cancellation at %s, got nil", targetStage)
			}
			if !strings.Contains(err.Error(), context.Canceled.Error()) {
				t.Errorf("expected context.Canceled error, got: %v", err)
			}
		})
	}
}

func TestOrchestrator_RawBuildContextDefaults(t *testing.T) {
	workspace, cleanup := setupMockWorkspace(t)
	defer cleanup()

	// Switch working directory to workspace so relative "." and "craftpack.yml" resolve naturally
	oldWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed getting wd: %v", err)
	}
	if err := os.Chdir(workspace); err != nil {
		t.Fatalf("failed chdir to workspace: %v", err)
	}
	defer func() { _ = os.Chdir(oldWd) }()

	orchestrator := NewOrchestrator()

	// Construct raw BuildContext without NewBuildContext to test orchestrator's defensive defaults
	rawCtx := &BuildContext{
		Options: BuildOptions{
			WorkspaceDir:   "", // Orchestrator sets to "."
			SpecPath:       "", // Orchestrator sets to filepath.Join(absWorkspace, "craftpack.yml")
			Target:         "deb",
			PackageVersion: "1.0.0",
			Architecture:   "", // Orchestrator sets to host
			BuildDate:      time.Time{}, // Orchestrator sets to time.Now()
			OutputDir:      "", // Orchestrator sets to "./dist"
		},
	}

	res, err := orchestrator.Build(context.Background(), rawCtx)
	if err != nil {
		t.Fatalf("orchestrator.Build with raw defaults failed: %v", err)
	}
	if !res.Success {
		t.Errorf("expected success")
	}
	if res.Architecture == "" {
		t.Errorf("expected auto-detected architecture")
	}
	defer os.RemoveAll(filepath.Dir(res.PackageFile))
}

func TestOrchestrator_MidStageFailures(t *testing.T) {
	orchestrator := NewOrchestrator()

	// 1. Man page deleted before Stage 4
	t.Run("man_page_missing_mid_stage", func(t *testing.T) {
		workspace, cleanup := setupMockWorkspace(t)
		defer cleanup()

		opts := BuildOptions{
			WorkspaceDir:   workspace,
			SpecPath:       "craftpack.yml",
			PackageVersion: "1.0.0",
			Target:         "deb",
			OnStage: func(stage Stage, detail string) {
				if stage == Stage4Documentation {
					// Delete the man page source file so generator fails
					_ = os.Remove(filepath.Join(workspace, "docs", "testapp.1.md"))
				}
			},
		}

		_, err := orchestrator.BuildWithOptions(context.Background(), opts)
		if err == nil {
			t.Fatalf("expected error on missing man page during stage 4, got nil")
		}
		if !strings.Contains(err.Error(), "stage 4") {
			t.Errorf("expected error from stage 4, got: %v", err)
		}
	})

	// 2. DefaultConfig deleted before Stage 5
	t.Run("default_config_missing_mid_stage", func(t *testing.T) {
		workspace, cleanup := setupMockWorkspace(t)
		defer cleanup()

		opts := BuildOptions{
			WorkspaceDir:   workspace,
			SpecPath:       "craftpack.yml",
			PackageVersion: "1.0.0",
			Target:         "deb",
			OnStage: func(stage Stage, detail string) {
				if stage == Stage5TargetMetadata {
					// Delete default config source file so copy fails
					_ = os.Remove(filepath.Join(workspace, "config", "testapp.conf"))
				}
			},
		}

		_, err := orchestrator.BuildWithOptions(context.Background(), opts)
		if err == nil {
			t.Fatalf("expected error on missing config during stage 5, got nil")
		}
		if !strings.Contains(err.Error(), "stage 5") {
			t.Errorf("expected error from stage 5, got: %v", err)
		}
	})
}

func TestOrchestrator_DefaultConfig_PathTraversal(t *testing.T) {
	workspace, cleanup := setupMockWorkspace(t)
	defer cleanup()

	traversalTargets := []string{
		"../escape.conf",
		"../../escape.conf",
		"/etc/passwd",
		"",
		".",
	}

	for _, badDst := range traversalTargets {
		t.Run("dst_"+badDst, func(t *testing.T) {
			bCtx, err := NewBuildContext(BuildOptions{
				WorkspaceDir:   workspace,
				SpecPath:       "craftpack.yml",
				PackageVersion: "1.0.0",
				Target:         "deb",
			})
			if err != nil {
				t.Fatalf("NewBuildContext failed: %v", err)
			}

			bCtx.Config = &spec.CraftpackConfig{
				Name:        "testapp",
				Description: "Test application",
				Maintainer:  "Dev <dev@test.org>",
				Command:     "testapp",
				PayloadDir:  "build/out",
				Entrypoint:  "app-bin",
				DefaultConfig: map[string]string{
					"config/testapp.conf": badDst,
				},
				Targets: spec.TargetConfigs{
					Deb: &spec.DebianTargetConfig{},
				},
			}
			bCtx.TargetPackager, _ = target.Get("deb")
			bCtx.NormalizedVersion = "1.0.0"
			bCtx.NormalizedArch = "amd64"

			orchestrator := NewOrchestrator()
			_, err = orchestrator.Build(context.Background(), bCtx)
			if err == nil || !strings.Contains(err.Error(), "clean relative path") {
				t.Errorf("expected 'clean relative path' error for dst %q, got: %v", badDst, err)
			}
		})
	}
}

func TestOrchestrator_DefaultConfig_DeterministicOrdering(t *testing.T) {
	workspace, cleanup := setupMockWorkspace(t)
	defer cleanup()

	// Create 3 config files
	cfgDir := filepath.Join(workspace, "config")
	_ = os.WriteFile(filepath.Join(cfgDir, "z.conf"), []byte("z"), 0644)
	_ = os.WriteFile(filepath.Join(cfgDir, "a.conf"), []byte("a"), 0644)
	_ = os.WriteFile(filepath.Join(cfgDir, "m.conf"), []byte("m"), 0644)

	bCtx, err := NewBuildContext(BuildOptions{
		WorkspaceDir:   workspace,
		OutputDir:      t.TempDir(),
		PackageVersion: "1.0.0",
		Target:         "deb",
		DryRun:         true,
	})
	if err != nil {
		t.Fatalf("NewBuildContext failed: %v", err)
	}

	bCtx.Config = &spec.CraftpackConfig{
		Name:        "orderapp",
		Description: "Order test application",
		Maintainer:  "Dev <dev@test.org>",
		Command:     "orderapp",
		PayloadDir:  "build/out",
		Entrypoint:  "app-bin",
		DefaultConfig: map[string]string{
			"config/z.conf": "z.conf",
			"config/a.conf": "a.conf",
			"config/m.conf": "m.conf",
		},
		Targets: spec.TargetConfigs{
			Deb: &spec.DebianTargetConfig{},
		},
	}
	bCtx.TargetPackager, _ = target.Get("deb")
	bCtx.NormalizedVersion = "1.0.0"
	bCtx.NormalizedArch = "amd64"

	orchestrator := NewOrchestrator()
	res, err := orchestrator.Build(context.Background(), bCtx)
	if err != nil {
		t.Fatalf("orchestrator.Build failed: %v", err)
	}

	// StagedFiles should contain etc/orderapp/a.conf, etc/orderapp/m.conf, etc/orderapp/z.conf in sorted order
	var confFiles []string
	for _, f := range res.StagedFiles {
		if strings.HasPrefix(f, "etc/") {
			confFiles = append(confFiles, f)
		}
	}

	expectedOrder := []string{
		"etc/orderapp/a.conf",
		"etc/orderapp/m.conf",
		"etc/orderapp/z.conf",
	}
	if len(confFiles) != 3 || confFiles[0] != expectedOrder[0] || confFiles[1] != expectedOrder[1] || confFiles[2] != expectedOrder[2] {
		t.Errorf("expected deterministic sorted order %v, got %v", expectedOrder, confFiles)
	}
}

func TestOrchestrator_Payload_EscapingSymlinkDirectory(t *testing.T) {
	workspace, cleanup := setupMockWorkspace(t)
	defer cleanup()

	outsideDir := t.TempDir()
	outsideFile := filepath.Join(outsideDir, "secret.txt")
	_ = os.WriteFile(outsideFile, []byte("classified"), 0600)

	// Create symlink to outside directory inside payload_dir
	payloadDir := filepath.Join(workspace, "build", "out")
	symlinkDir := filepath.Join(payloadDir, "escaping_folder")
	_ = os.Symlink(outsideDir, symlinkDir)

	orchestrator := NewOrchestrator()
	opts := BuildOptions{
		WorkspaceDir:   workspace,
		SpecPath:       "craftpack.yml",
		PackageVersion: "1.0.0",
		Target:         "deb",
		OutputDir:      t.TempDir(),
	}

	_, err := orchestrator.BuildWithOptions(context.Background(), opts)
	if err == nil || !strings.Contains(err.Error(), "escaped boundary") {
		t.Errorf("expected 'escaped boundary' error for escaping directory symlink, got: %v", err)
	}
}

func TestOrchestrator_NilContextHandledGracefully(t *testing.T) {
	workspace, cleanup := setupMockWorkspace(t)
	defer cleanup()

	orchestrator := NewOrchestrator()
	opts := BuildOptions{
		WorkspaceDir:   workspace,
		SpecPath:       "craftpack.yml",
		PackageVersion: "1.0.0",
		Target:         "deb",
		DryRun:         true,
	}

	res, err := orchestrator.BuildWithOptions(nil, opts)
	if err != nil {
		t.Fatalf("unexpected error with nil context: %v", err)
	}
	if !res.Success {
		t.Errorf("expected success with nil context")
	}
}

type mockNilPackager struct{}

func (m *mockNilPackager) TargetName() string { return "nilpkg" }
func (m *mockNilPackager) Build(ctx context.Context, opts target.PackageOptions) (*target.PackageResult, error) {
	return nil, nil
}

func TestOrchestrator_PackagerReturnsNilResult(t *testing.T) {
	workspace, cleanup := setupMockWorkspace(t)
	defer cleanup()

	target.Register("nilpkg", func() target.TargetPackager {
		return &mockNilPackager{}
	})

	orchestrator := NewOrchestrator()
	opts := BuildOptions{
		WorkspaceDir:   workspace,
		SpecPath:       "craftpack.yml",
		PackageVersion: "1.0.0",
		Target:         "nilpkg",
		OutputDir:      t.TempDir(),
	}

	_, err := orchestrator.BuildWithOptions(context.Background(), opts)
	if err == nil || !strings.Contains(err.Error(), "nil result or empty package file") {
		t.Errorf("expected 'nil result or empty package file' error, got: %v", err)
	}
}

func TestManifest_ComputeSHA256_Directory(t *testing.T) {
	tmpDir := t.TempDir()
	_, _, err := ComputeSHA256(tmpDir)
	if err == nil || !strings.Contains(err.Error(), "cannot compute sha256 for directory") {
		t.Errorf("expected directory error from ComputeSHA256, got: %v", err)
	}
}

func TestManifest_WriteOrUpdateManifest_InjectionAndInvalidInputs(t *testing.T) {
	tmpDir := t.TempDir()
	manifestFile := filepath.Join(tmpDir, ManifestFileName)
	validHash := strings.Repeat("a", 64)

	tests := []struct {
		name      string
		hash      string
		filename  string
		size      int64
		errSubstr string
	}{
		{
			name:      "hash with newline injection",
			hash:      validHash[:32] + "\n" + validHash[33:],
			filename:  "pkg.deb",
			size:      100,
			errSubstr: "invalid sha256 hash",
		},
		{
			name:      "hash with carriage return",
			hash:      validHash[:63] + "\r",
			filename:  "pkg.deb",
			size:      100,
			errSubstr: "invalid sha256 hash",
		},
		{
			name:      "hash short length",
			hash:      "abcdef",
			filename:  "pkg.deb",
			size:      100,
			errSubstr: "invalid sha256 hash",
		},
		{
			name:      "hash invalid non-hex characters",
			hash:      strings.Repeat("z", 64),
			filename:  "pkg.deb",
			size:      100,
			errSubstr: "invalid sha256 hex digest",
		},
		{
			name:      "filename with newline injection",
			hash:      validHash,
			filename:  "pkg.deb\nmalicious_line",
			size:      100,
			errSubstr: "invalid package filename",
		},
		{
			name:      "empty filename",
			hash:      validHash,
			filename:  "   ",
			size:      100,
			errSubstr: "invalid package filename",
		},
		{
			name:      "negative size",
			hash:      validHash,
			filename:  "pkg.deb",
			size:      -1,
			errSubstr: "package size cannot be negative",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			err := WriteOrUpdateManifest(manifestFile, tc.hash, tc.filename, tc.size)
			if err == nil {
				t.Fatalf("expected error containing %q, got nil", tc.errSubstr)
			}
			if !strings.Contains(err.Error(), tc.errSubstr) {
				t.Errorf("error %q does not contain %q", err.Error(), tc.errSubstr)
			}
		})
	}
}

func TestManifest_ParseManifestEntry_InvalidHexFallback(t *testing.T) {
	badLine := strings.Repeat("z", 64) + "  sample.deb"
	_, err := ParseManifestEntry(badLine)
	if err == nil || !strings.Contains(err.Error(), "malformed manifest entry") {
		t.Errorf("expected malformed manifest entry error for non-hex fallback, got: %v", err)
	}
}

func TestBuildContext_ReallocateStagingAfterCleanup(t *testing.T) {
	bCtx, err := NewBuildContext(BuildOptions{})
	if err != nil {
		t.Fatalf("NewBuildContext failed: %v", err)
	}

	dir1, err := bCtx.EnsureStagingDir()
	if err != nil {
		t.Fatalf("EnsureStagingDir 1 failed: %v", err)
	}
	if err := bCtx.Cleanup(); err != nil {
		t.Fatalf("Cleanup 1 failed: %v", err)
	}
	if _, err := os.Stat(dir1); !os.IsNotExist(err) {
		t.Errorf("expected dir1 to be removed")
	}

	// Re-allocate staging directory
	dir2, err := bCtx.EnsureStagingDir()
	if err != nil {
		t.Fatalf("EnsureStagingDir 2 failed: %v", err)
	}
	if dir2 == "" {
		t.Errorf("expected non-empty dir2")
	}
	if err := bCtx.Cleanup(); err != nil {
		t.Fatalf("Cleanup 2 failed: %v", err)
	}
	if _, err := os.Stat(dir2); !os.IsNotExist(err) {
		t.Errorf("expected dir2 to be removed after second cleanup")
	}
}

func TestOrchestrator_Stage7_ManifestWriteFailure(t *testing.T) {
	workspace, cleanup := setupMockWorkspace(t)
	defer cleanup()

	outDir := t.TempDir()
	// Create a DIRECTORY with the same name as the manifest file
	blockerDir := filepath.Join(outDir, ManifestFileName)
	if err := os.MkdirAll(blockerDir, 0755); err != nil {
		t.Fatalf("failed creating blocker dir: %v", err)
	}

	orchestrator := NewOrchestrator()
	opts := BuildOptions{
		WorkspaceDir:   workspace,
		SpecPath:       "craftpack.yml",
		PackageVersion: "1.0.0",
		Target:         "deb",
		OutputDir:      outDir,
	}

	bCtx, err := NewBuildContext(opts)
	if err != nil {
		t.Fatalf("NewBuildContext failed: %v", err)
	}

	_, err = orchestrator.Build(context.Background(), bCtx)
	if err == nil || !strings.Contains(err.Error(), "manifest update failed") {
		t.Errorf("expected manifest update failed error, got: %v", err)
	}

	// Verify that staging directory was cleaned up despite Stage 7 failure
	if bCtx.StagingDir() != "" {
		if _, statErr := os.Stat(bCtx.StagingDir()); !os.IsNotExist(statErr) {
			t.Errorf("expected staging dir to be cleaned up after error")
		}
	}
}

func TestOrchestrator_DryRun_TargetValidationFailures(t *testing.T) {
	workspace, cleanup := setupMockWorkspace(t)
	defer cleanup()

	orchestrator := NewOrchestrator()

	// 1. Invalid deb maintainer script
	bCtx, _ := NewBuildContext(BuildOptions{
		WorkspaceDir:   workspace,
		PackageVersion: "1.0.0",
		Target:         "deb",
		DryRun:         true,
	})
	bCtx.Config = &spec.CraftpackConfig{
		Name:        "baddeb",
		Description: "Bad deb target",
		Maintainer:  "Dev <dev@test.org>",
		Command:     "baddeb",
		PayloadDir:  "build/out",
		Entrypoint:  "app-bin",
		PreInstall:  "../escaping.sh", // Path traversal in hook
		Targets: spec.TargetConfigs{
			Deb: &spec.DebianTargetConfig{},
		},
	}
	bCtx.TargetPackager, _ = target.Get("deb")
	bCtx.NormalizedVersion = "1.0.0"
	bCtx.NormalizedArch = "amd64"

	_, err := orchestrator.Build(context.Background(), bCtx)
	if err == nil || !strings.Contains(err.Error(), "deb maintainer scripts validation failed") {
		t.Errorf("expected deb maintainer scripts validation error in dry run, got: %v", err)
	}

	// 2. Invalid control metadata in dry run (e.g. invalid app name with newline in Stage 5)
	bCtx2, _ := NewBuildContext(BuildOptions{
		WorkspaceDir:   workspace,
		PackageVersion: "1.0.0",
		Target:         "deb",
		DryRun:         true,
	})
	bCtx2.Config = &spec.CraftpackConfig{
		Name:        "badctrl",
		Description: "Bad control",
		Maintainer:  "Dev <dev@test.org>",
		Command:     "baddeb",
		PayloadDir:  "build/out",
		Entrypoint:  "app-bin",
		Targets: spec.TargetConfigs{
			Deb: &spec.DebianTargetConfig{
				Section: "invalid\nsection",
			},
		},
	}
	bCtx2.TargetPackager, _ = target.Get("deb")
	bCtx2.NormalizedVersion = "1.0.0"
	bCtx2.NormalizedArch = "amd64"

	_, err = orchestrator.Build(context.Background(), bCtx2)
	if err == nil || !strings.Contains(err.Error(), "deb control validation failed") {
		t.Errorf("expected deb control validation error in dry run, got: %v", err)
	}
}

func TestBuildContext_NotifyWarning_And_SourceDateEpoch(t *testing.T) {
	t.Setenv("SOURCE_DATE_EPOCH", "1600000000")
	var captured string
	opts := BuildOptions{
		OnWarning: func(w string) {
			captured = w
		},
	}
	bCtx, err := NewBuildContext(opts)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if bCtx.BuildDate.Unix() != 1600000000 {
		t.Errorf("expected build date 1600000000, got %d", bCtx.BuildDate.Unix())
	}

	bCtx.NotifyWarning("test warning")
	if captured != "test warning" {
		t.Errorf("expected captured warning 'test warning', got %q", captured)
	}
	if len(bCtx.Warnings) != 1 || bCtx.Warnings[0] != "test warning" {
		t.Errorf("expected bCtx.Warnings to contain 'test warning', got %v", bCtx.Warnings)
	}
}



