// SPDX-FileCopyrightText: 2026 Marcin Kaim
// SPDX-License-Identifier: Apache-2.0

package generator

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"craftpack/pkg/fsutil"
	"craftpack/pkg/spec"
)

// --- Proxy Launcher Tests ---

func TestGenerateLauncher_Valid(t *testing.T) {
	tests := []struct {
		name       string
		appID      string
		entrypoint string
		wantAnchor string
	}{
		{
			name:       "standard app and binary",
			appID:      "craftpack",
			entrypoint: "craftpack",
			wantAnchor: `REAL_PAYLOAD="/usr/lib/craftpack/craftpack"`,
		},
		{
			name:       "nested entrypoint path",
			appID:      "my-service",
			entrypoint: "bin/server",
			wantAnchor: `REAL_PAYLOAD="/usr/lib/my-service/bin/server"`,
		},
		{
			name:       "underscored app id",
			appID:      "app_daemon",
			entrypoint: "app_daemon",
			wantAnchor: `REAL_PAYLOAD="/usr/lib/app_daemon/app_daemon"`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			content, err := GenerateLauncher(tt.appID, tt.entrypoint)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			script := string(content)

			// Section 5.1 & Requirement 3 contracts:
			if !strings.HasPrefix(script, "#!/bin/sh\n") {
				t.Errorf("expected script to start with '#!/bin/sh\\n', got:\n%s", script)
			}
			if !strings.Contains(script, "# Auto-generated by Craftpack. Do not edit.") {
				t.Errorf("missing craftpack autogen comment")
			}
			if !strings.Contains(script, tt.wantAnchor) {
				t.Errorf("expected anchor '%s', got script:\n%s", tt.wantAnchor, script)
			}
			if !strings.Contains(script, `exec "$REAL_PAYLOAD" "$@"`) {
				t.Errorf("missing POSIX exec delegation line in script:\n%s", script)
			}
			if !strings.HasSuffix(script, "\n") {
				t.Errorf("expected script to end with newline")
			}
		})
	}
}

func TestGenerateLauncher_ValidationErrors(t *testing.T) {
	tests := []struct {
		name       string
		appID      string
		entrypoint string
		wantErr    error
	}{
		{
			name:       "empty app id",
			appID:      "",
			entrypoint: "app",
			wantErr:    ErrInvalidAppID,
		},
		{
			name:       "whitespace app id",
			appID:      "   ",
			entrypoint: "app",
			wantErr:    ErrInvalidAppID,
		},
		{
			name:       "app id with spaces",
			appID:      "my app",
			entrypoint: "app",
			wantErr:    ErrInvalidAppID,
		},
		{
			name:       "app id with quotes",
			appID:      "app\"id",
			entrypoint: "app",
			wantErr:    ErrInvalidAppID,
		},
		{
			name:       "app id with slashes",
			appID:      "app/id",
			entrypoint: "app",
			wantErr:    ErrInvalidAppID,
		},
		{
			name:       "empty entrypoint",
			appID:      "myapp",
			entrypoint: "",
			wantErr:    ErrInvalidEntrypoint,
		},
		{
			name:       "absolute entrypoint",
			appID:      "myapp",
			entrypoint: "/usr/bin/app",
			wantErr:    ErrInvalidEntrypoint,
		},
		{
			name:       "traversal entrypoint dotdot",
			appID:      "myapp",
			entrypoint: "../outside",
			wantErr:    ErrInvalidEntrypoint,
		},
		{
			name:       "traversal entrypoint in subpath",
			appID:      "myapp",
			entrypoint: "bin/../../outside",
			wantErr:    ErrInvalidEntrypoint,
		},
		{
			name:       "entrypoint with quotes",
			appID:      "myapp",
			entrypoint: "app\"bin",
			wantErr:    ErrInvalidEntrypoint,
		},
		{
			name:       "entrypoint with newline",
			appID:      "myapp",
			entrypoint: "app\nbin",
			wantErr:    ErrInvalidEntrypoint,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := GenerateLauncher(tt.appID, tt.entrypoint)
			if err == nil {
				t.Fatalf("expected error containing %v, got nil", tt.wantErr)
			}
			if !strings.Contains(err.Error(), tt.wantErr.Error()) {
				t.Errorf("expected error %v, got %v", tt.wantErr, err)
			}
		})
	}
}

func TestSynthesizeLauncher(t *testing.T) {
	res, err := SynthesizeLauncher("craftpack", "craftpack", "craftpack")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if res.Command != "craftpack" {
		t.Errorf("expected Command 'craftpack', got '%s'", res.Command)
	}
	if res.AppID != "craftpack" {
		t.Errorf("expected AppID 'craftpack', got '%s'", res.AppID)
	}
	if res.Entrypoint != "craftpack" {
		t.Errorf("expected Entrypoint 'craftpack', got '%s'", res.Entrypoint)
	}
	if res.DestinationPath != "/usr/bin/craftpack" {
		t.Errorf("expected DestinationPath '/usr/bin/craftpack', got '%s'", res.DestinationPath)
	}
	if res.RelPath() != "usr/bin/craftpack" {
		t.Errorf("expected RelPath 'usr/bin/craftpack', got '%s'", res.RelPath())
	}
	if res.Mode != fsutil.ExecMode {
		t.Errorf("expected Mode 0755, got %v", res.Mode)
	}

	// Invalid command tests
	_, err = SynthesizeLauncher("", "myapp", "app")
	if err == nil {
		t.Errorf("expected error for empty command")
	}

	_, err = SynthesizeLauncher("foo/bar", "myapp", "app")
	if err == nil {
		t.Errorf("expected error for command with slashes")
	}
}

func TestSynthesizeLauncherFromConfig(t *testing.T) {
	cfg := &spec.CraftpackConfig{
		Name:       "myapp",
		Command:    "mycmd",
		Entrypoint: "bin/start",
	}

	res, err := SynthesizeLauncherFromConfig(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if res.Command != "mycmd" {
		t.Errorf("expected Command 'mycmd', got '%s'", res.Command)
	}
	if res.DestinationPath != "/usr/bin/mycmd" {
		t.Errorf("expected DestinationPath '/usr/bin/mycmd', got '%s'", res.DestinationPath)
	}

	// Fallback to cfg.Name when cfg.Command is empty
	cfgNoCmd := &spec.CraftpackConfig{
		Name:       "myapp",
		Entrypoint: "bin/start",
	}
	resFallback, err := SynthesizeLauncherFromConfig(cfgNoCmd)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resFallback.Command != "myapp" {
		t.Errorf("expected Command fallback to 'myapp', got '%s'", resFallback.Command)
	}

	// Nil config error
	_, err = SynthesizeLauncherFromConfig(nil)
	if err == nil {
		t.Errorf("expected error for nil config")
	}
}

func TestWriteLauncher(t *testing.T) {
	tempDir := t.TempDir()

	res, err := SynthesizeLauncher("testtool", "testapp", "testbin")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	writtenPath, err := WriteLauncher(tempDir, res)
	if err != nil {
		t.Fatalf("failed to write launcher: %v", err)
	}

	expectedPath := filepath.Join(tempDir, "usr", "bin", "testtool")
	if writtenPath != expectedPath {
		t.Errorf("expected written path '%s', got '%s'", expectedPath, writtenPath)
	}

	fi, err := os.Stat(writtenPath)
	if err != nil {
		t.Fatalf("failed to stat written launcher: %v", err)
	}

	if fi.Mode().Perm() != fsutil.ExecMode {
		t.Errorf("expected permissions 0755, got %v", fi.Mode().Perm())
	}

	data, err := os.ReadFile(writtenPath)
	if err != nil {
		t.Fatalf("failed to read written launcher: %v", err)
	}

	if !bytes.Equal(data, res.Content) {
		t.Errorf("written content does not match synthesized content")
	}
}

// TestLauncher_POSIXExecContractAndArgumentForwarding executes the synthesized launcher script
// to verify the core operational semantics mandated by Requirement 3:
// 1. Argument forwarding without word-splitting or shell interpretation
// 2. Direct STDIN/STDOUT/STDERR stream passthrough
// 3. Transparent exit code propagation
// 4. PID preservation via POSIX exec (replacing the wrapper process)
func TestLauncher_POSIXExecContractAndArgumentForwarding(t *testing.T) {
	tempDir := t.TempDir()

	// 1. Create mock payload script
	payloadDir := filepath.Join(tempDir, "payload")
	if err := os.MkdirAll(payloadDir, 0755); err != nil {
		t.Fatalf("failed to create payload dir: %v", err)
	}
	payloadPath := filepath.Join(payloadDir, "target")

	mockPayloadScript := `#!/bin/sh
case "$1" in
  --print-args)
    shift
    for arg in "$@"; do
      printf 'ARG:[%s]\n' "$arg"
    done
    ;;
  --echo-stdin)
    cat
    ;;
  --exit-code)
    exit "$2"
    ;;
  --pid-check)
    echo "$$"
    ;;
  *)
    echo "UNKNOWN"
    exit 1
    ;;
esac
`
	if err := os.WriteFile(payloadPath, []byte(mockPayloadScript), 0755); err != nil {
		t.Fatalf("failed to write mock payload: %v", err)
	}

	// 2. Synthesize a proxy launcher.
	// Since in this unit test we are running in tempDir rather than the root filesystem,
	// we create a launcher that uses the same exec logic targeting payloadPath.
	launcherScript := fmt.Sprintf(`#!/bin/sh
# Auto-generated by Craftpack. Do not edit.

REAL_PAYLOAD="%s"

exec "$REAL_PAYLOAD" "$@"
`, payloadPath)

	launcherPath := filepath.Join(tempDir, "launcher.sh")
	if err := os.WriteFile(launcherPath, []byte(launcherScript), 0755); err != nil {
		t.Fatalf("failed to write launcher script: %v", err)
	}

	// Test A: Argument forwarding with complex spaces, quotes, and symbols
	testArgs := []string{
		"--print-args",
		"simple",
		"two words with spaces",
		"single'quote",
		"double\"quote",
		"$VAR_LITERAL",
		"--flag=value with space",
		"*glob*",
		"-v",
		"",
	}

	cmd := exec.Command("/bin/sh", append([]string{launcherPath}, testArgs...)...)
	outBytes, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("launcher execution failed: %v, output:\n%s", err, string(outBytes))
	}

	outStr := string(outBytes)
	for _, expectedArg := range testArgs[1:] { // skip --print-args
		expectedLine := fmt.Sprintf("ARG:[%s]", expectedArg)
		if !strings.Contains(outStr, expectedLine) {
			t.Errorf("expected output to contain '%s', got:\n%s", expectedLine, outStr)
		}
	}

	// Test B: Exit code propagation (test codes 0, 42, 127)
	for _, code := range []int{0, 42, 127} {
		cmdExit := exec.Command(launcherPath, "--exit-code", fmt.Sprintf("%d", code))
		errExit := cmdExit.Run()
		if code == 0 {
			if errExit != nil {
				t.Errorf("expected exit code 0, got err: %v", errExit)
			}
		} else {
			if exitErr, ok := errExit.(*exec.ExitError); ok {
				if exitErr.ExitCode() != code {
					t.Errorf("expected exit code %d, got %d", code, exitErr.ExitCode())
				}
			} else {
				t.Errorf("expected ExitError for code %d, got %v", code, errExit)
			}
		}
	}

	// Test C: Stdin stream passthrough
	inputMessage := "Testing stdin passthrough across exec proxy barrier\nLine 2 payload"
	cmdStdin := exec.Command(launcherPath, "--echo-stdin")
	cmdStdin.Stdin = strings.NewReader(inputMessage)
	outStdin, err := cmdStdin.Output()
	if err != nil {
		t.Fatalf("stdin passthrough failed: %v", err)
	}
	if string(outStdin) != inputMessage {
		t.Errorf("expected stdin output '%s', got '%s'", inputMessage, string(outStdin))
	}

	// Test D: PID preservation (POSIX exec contract)
	// Execute in a subshell: echo shell PID, then exec launcher; the payload PID must equal shell PID
	subshellCmd := fmt.Sprintf(`echo -n "SHELL:$$ "; exec "%s" --pid-check`, launcherPath)
	cmdPID := exec.Command("/bin/sh", "-c", subshellCmd)
	outPIDBytes, err := cmdPID.CombinedOutput()
	if err != nil {
		t.Fatalf("PID check failed: %v, output: %s", err, string(outPIDBytes))
	}
	fields := strings.Fields(string(outPIDBytes))
	if len(fields) != 2 {
		t.Fatalf("unexpected PID output: %s", string(outPIDBytes))
	}
	shellPID := strings.TrimPrefix(fields[0], "SHELL:")
	payloadPID := fields[1]
	if shellPID != payloadPID {
		t.Errorf("expected PID preservation under exec: shell PID %s != payload PID %s", shellPID, payloadPID)
	}
}

// --- Decoupled Man Page Compiler Tests ---

func TestDefaultSectionHeader(t *testing.T) {
	tests := []struct {
		section int
		want    string
	}{
		{1, "User Commands Manual"},
		{2, "System Calls Manual"},
		{3, "Library Functions Manual"},
		{4, "Special Files Manual"},
		{5, "File Formats Manual"},
		{6, "Games Manual"},
		{7, "Miscellaneous Information Manual"},
		{8, "System Administration Commands"},
		{99, "User Commands Manual"}, // fallback
	}

	for _, tt := range tests {
		t.Run(fmt.Sprintf("section_%d", tt.section), func(t *testing.T) {
			got := DefaultSectionHeader(tt.section)
			if got != tt.want {
				t.Errorf("DefaultSectionHeader(%d) = '%s', want '%s'", tt.section, got, tt.want)
			}
		})
	}
}

func TestInferManPageMetadata(t *testing.T) {
	fixedDate := time.Date(2026, 9, 6, 12, 0, 0, 0, time.UTC)

	t.Run("explicit fields override all defaults", func(t *testing.T) {
		mp := spec.ManPageConfig{
			Source:  "docs/craftpack.1.md",
			Section: 1,
			Title:   "my-title",
			Header:  "Custom Header",
			Footer:  "Custom Footer v1",
		}
		cfg := &spec.CraftpackConfig{
			Name:    "craftpack",
			Command: "craftpack",
		}

		meta := InferManPageMetadata(mp, cfg, "v1.0.0", fixedDate)
		if meta.Title != "MY-TITLE" {
			t.Errorf("expected Title 'MY-TITLE', got '%s'", meta.Title)
		}
		if meta.Section != 1 {
			t.Errorf("expected Section 1, got %d", meta.Section)
		}
		if meta.Header != "Custom Header" {
			t.Errorf("expected Header 'Custom Header', got '%s'", meta.Header)
		}
		if meta.Footer != "Custom Footer v1" {
			t.Errorf("expected Footer 'Custom Footer v1', got '%s'", meta.Footer)
		}
		if meta.Date != "2026-09-06" {
			t.Errorf("expected Date '2026-09-06', got '%s'", meta.Date)
		}
	})

	t.Run("inferred defaults from config and section", func(t *testing.T) {
		mp := spec.ManPageConfig{
			Source:  "docs/app.5.md",
			Section: 5,
		}
		cfg := &spec.CraftpackConfig{
			Name:    "myapp",
			Command: "mycmd",
		}

		meta := InferManPageMetadata(mp, cfg, "2.3.4", fixedDate)
		if meta.Title != "MYCMD" {
			t.Errorf("expected Title 'MYCMD' (from command), got '%s'", meta.Title)
		}
		if meta.Section != 5 {
			t.Errorf("expected Section 5, got %d", meta.Section)
		}
		if meta.Header != "File Formats Manual" {
			t.Errorf("expected Header 'File Formats Manual', got '%s'", meta.Header)
		}
		if meta.Footer != "myapp 2.3.4" {
			t.Errorf("expected Footer 'myapp 2.3.4', got '%s'", meta.Footer)
		}
		if meta.Date != "2026-09-06" {
			t.Errorf("expected Date '2026-09-06', got '%s'", meta.Date)
		}
	})

	t.Run("title fallback to name when command is empty", func(t *testing.T) {
		mp := spec.ManPageConfig{Section: 1}
		cfg := &spec.CraftpackConfig{Name: "appname"}

		meta := InferManPageMetadata(mp, cfg, "1.0", fixedDate)
		if meta.Title != "APPNAME" {
			t.Errorf("expected Title 'APPNAME', got '%s'", meta.Title)
		}
	})
}

func TestFormatTitleHeaderDirective(t *testing.T) {
	meta := ManPageMetadata{
		Title:   "CRAFTPACK",
		Section: 1,
		Date:    "2026-09-06",
		Header:  "User Commands Manual",
		Footer:  "craftpack 1.0.0",
	}

	directive := FormatTitleHeaderDirective(meta)
	expected := "% CRAFTPACK(1) craftpack 1.0.0 | User Commands Manual\n\n"
	if directive != expected {
		t.Errorf("expected directive:\n%q\ngot:\n%q", expected, directive)
	}

	// Without footer
	metaNoFooter := ManPageMetadata{Title: "TOOL", Section: 2, Header: "System Calls"}
	directiveNoFooter := FormatTitleHeaderDirective(metaNoFooter)
	expectedNoFooter := "% TOOL(2) | System Calls\n\n"
	if directiveNoFooter != expectedNoFooter {
		t.Errorf("expected directive:\n%q\ngot:\n%q", expectedNoFooter, directiveNoFooter)
	}

	// Without header
	metaNoHeader := ManPageMetadata{Title: "TOOL", Section: 2, Footer: "tool 1.0"}
	directiveNoHeader := FormatTitleHeaderDirective(metaNoHeader)
	expectedNoHeader := "% TOOL(2) tool 1.0\n\n"
	if directiveNoHeader != expectedNoHeader {
		t.Errorf("expected directive:\n%q\ngot:\n%q", expectedNoHeader, directiveNoHeader)
	}
}

func TestValidateZeroMarkup(t *testing.T) {
	validMarkdown := []byte("# NAME\ncraftpack - tool\n\n# DESCRIPTION\nValid doc\n")
	if err := ValidateZeroMarkup(validMarkdown); err != nil {
		t.Errorf("expected valid markdown to pass, got: %v", err)
	}

	invalidMarkdown := []byte("---\ntitle: Foo\n---\n# NAME\nfoo\n")
	if err := ValidateZeroMarkup(invalidMarkdown); err == nil {
		t.Errorf("expected error for YAML front-matter, got nil")
	} else if !strings.Contains(err.Error(), ErrZeroMarkupViolation.Error()) {
		t.Errorf("expected ErrZeroMarkupViolation, got: %v", err)
	}

	invalidWithWhitespace := []byte("   \n\t---\nsection: 1\n---\n")
	if err := ValidateZeroMarkup(invalidWithWhitespace); err == nil {
		t.Errorf("expected error for YAML front-matter with leading whitespace")
	}
}

func TestRenderRoff(t *testing.T) {
	rawMarkdown := `# NAME
craftpack \- Standardized Linux packaging factory

# SYNOPSIS
**craftpack** build [options]

# DESCRIPTION
Craftpack compiles packages deterministically.

# EXAMPLES
Run build:
` + "```\ncraftpack build --spec craftpack.yml\n```\n"

	meta := ManPageMetadata{
		Title:   "CRAFTPACK",
		Section: 1,
		Date:    "2026-09-06",
		Header:  "User Commands Manual",
		Footer:  "craftpack 1.0.0",
	}

	roffBytes, err := RenderRoff([]byte(rawMarkdown), meta)
	if err != nil {
		t.Fatalf("unexpected error rendering roff: %v", err)
	}

	roff := string(roffBytes)

	// Check roff directives
	if !strings.Contains(roff, ".TH CRAFTPACK(1) craftpack 1.0.0 | User Commands Manual") {
		t.Errorf("missing .TH title header in roff:\n%s", roff)
	}
	if !strings.Contains(roff, ".SH NAME") {
		t.Errorf("missing .SH NAME section header in roff")
	}
	if !strings.Contains(roff, ".SH SYNOPSIS") {
		t.Errorf("missing .SH SYNOPSIS section header in roff")
	}
	if !strings.Contains(roff, ".SH DESCRIPTION") {
		t.Errorf("missing .SH DESCRIPTION section header in roff")
	}
	if !strings.Contains(roff, ".EX") || !strings.Contains(roff, ".EE") {
		t.Errorf("missing code block .EX/.EE in roff:\n%s", roff)
	}
}

func TestCompressRoffAndDecompressRoundtrip(t *testing.T) {
	sampleRoff := []byte(".TH TEST 1\n.SH NAME\ntest - tool\n")
	fixedTime := time.Date(2026, 9, 6, 10, 0, 0, 0, time.UTC)

	compressed, err := CompressRoff(sampleRoff, fixedTime)
	if err != nil {
		t.Fatalf("failed to compress roff: %v", err)
	}

	// Decompress and verify content
	gr, err := gzip.NewReader(bytes.NewReader(compressed))
	if err != nil {
		t.Fatalf("failed to initialize gzip reader: %v", err)
	}
	defer gr.Close()

	if gr.Header.ModTime.UTC() != fixedTime {
		t.Errorf("expected gzip ModTime %v, got %v", fixedTime, gr.Header.ModTime.UTC())
	}

	decompressed, err := io.ReadAll(gr)
	if err != nil {
		t.Fatalf("failed reading gzip stream: %v", err)
	}

	if !bytes.Equal(decompressed, sampleRoff) {
		t.Errorf("decompressed content does not match original roff")
	}
}

func TestSynthesizeManPage(t *testing.T) {
	tempWorkspace := t.TempDir()

	// Write a valid pristine markdown file
	docRelPath := filepath.Join("docs", "tool.1.md")
	docFullPath := filepath.Join(tempWorkspace, docRelPath)
	if err := os.MkdirAll(filepath.Dir(docFullPath), 0755); err != nil {
		t.Fatalf("failed to create docs dir: %v", err)
	}

	markdownContent := `# NAME
tool - a useful CLI utility

# SYNOPSIS
**tool** [options]
`
	if err := os.WriteFile(docFullPath, []byte(markdownContent), 0644); err != nil {
		t.Fatalf("failed to write test markdown: %v", err)
	}

	mp := spec.ManPageConfig{
		Source:  docRelPath,
		Section: 1,
		Title:   "TOOL",
	}

	cfg := &spec.CraftpackConfig{
		Name:    "mytool",
		Command: "tool",
	}

	fixedTime := time.Date(2026, 9, 6, 12, 0, 0, 0, time.UTC)
	res, err := SynthesizeManPage(mp, cfg, tempWorkspace, "v1.2.3", fixedTime)
	if err != nil {
		t.Fatalf("unexpected error synthesizing man page: %v", err)
	}

	expectedDest := "/usr/share/man/man1/tool.1.gz"
	if res.DestinationPath != expectedDest {
		t.Errorf("expected DestinationPath '%s', got '%s'", expectedDest, res.DestinationPath)
	}
	if res.RelPath() != "usr/share/man/man1/tool.1.gz" {
		t.Errorf("expected RelPath 'usr/share/man/man1/tool.1.gz', got '%s'", res.RelPath())
	}
	if res.Mode != fsutil.FileMode {
		t.Errorf("expected Mode 0644, got %v", res.Mode)
	}
	if res.Section != 1 {
		t.Errorf("expected Section 1, got %d", res.Section)
	}
	if res.Command != "tool" {
		t.Errorf("expected Command 'tool', got '%s'", res.Command)
	}

	// Verify compressed content can be decompressed
	gr, err := gzip.NewReader(bytes.NewReader(res.Content))
	if err != nil {
		t.Fatalf("failed to decompress synthesized content: %v", err)
	}
	decompressed, err := io.ReadAll(gr)
	gr.Close()
	if err != nil {
		t.Fatalf("failed to read decompressed stream: %v", err)
	}

	decompressedStr := string(decompressed)
	if !strings.Contains(decompressedStr, ".TH TOOL(1)") {
		t.Errorf("missing .TH TOOL(1) in decompressed roff:\n%s", decompressedStr)
	}
	if !strings.Contains(decompressedStr, ".SH NAME") {
		t.Errorf("missing .SH NAME in decompressed roff")
	}
}

func TestSynthesizeManPage_Errors(t *testing.T) {
	tempWorkspace := t.TempDir()

	cfg := &spec.CraftpackConfig{Name: "app", Command: "app"}
	now := time.Now()

	// Empty source
	_, err := SynthesizeManPage(spec.ManPageConfig{Source: "", Section: 1}, cfg, tempWorkspace, "1.0", now)
	if err == nil || !strings.Contains(err.Error(), ErrEmptySource.Error()) {
		t.Errorf("expected ErrEmptySource, got: %v", err)
	}

	// Invalid sections (< 1 or > 8)
	_, err = SynthesizeManPage(spec.ManPageConfig{Source: "doc.md", Section: 0}, cfg, tempWorkspace, "1.0", now)
	if err == nil || !strings.Contains(err.Error(), ErrInvalidSection.Error()) {
		t.Errorf("expected ErrInvalidSection for 0, got: %v", err)
	}

	_, err = SynthesizeManPage(spec.ManPageConfig{Source: "doc.md", Section: 9}, cfg, tempWorkspace, "1.0", now)
	if err == nil || !strings.Contains(err.Error(), ErrInvalidSection.Error()) {
		t.Errorf("expected ErrInvalidSection for 9, got: %v", err)
	}

	// Traversal source
	_, err = SynthesizeManPage(spec.ManPageConfig{Source: "../outside.md", Section: 1}, cfg, tempWorkspace, "1.0", now)
	if err == nil || !strings.Contains(err.Error(), "boundary violation") {
		t.Errorf("expected boundary violation error, got: %v", err)
	}

	// Non-existent source
	_, err = SynthesizeManPage(spec.ManPageConfig{Source: "missing.md", Section: 1}, cfg, tempWorkspace, "1.0", now)
	if err == nil {
		t.Errorf("expected error for missing source file, got nil")
	}

	// Zero-Markup violation in source file
	frontmatterFile := filepath.Join(tempWorkspace, "frontmatter.md")
	_ = os.WriteFile(frontmatterFile, []byte("---\ntitle: Bad\n---\n# NAME\n"), 0644)
	_, err = SynthesizeManPage(spec.ManPageConfig{Source: "frontmatter.md", Section: 1}, cfg, tempWorkspace, "1.0", now)
	if err == nil || !strings.Contains(err.Error(), ErrZeroMarkupViolation.Error()) {
		t.Errorf("expected ErrZeroMarkupViolation, got: %v", err)
	}
}

func TestSynthesizeAllManPages(t *testing.T) {
	tempWorkspace := t.TempDir()

	_ = os.WriteFile(filepath.Join(tempWorkspace, "doc1.md"), []byte("# NAME\napp - 1\n"), 0644)
	_ = os.WriteFile(filepath.Join(tempWorkspace, "doc5.md"), []byte("# NAME\napp - 5\n"), 0644)

	cfg := &spec.CraftpackConfig{
		Name:    "app",
		Command: "app",
		ManPages: []spec.ManPageConfig{
			{Source: "doc1.md", Section: 1},
			{Source: "doc5.md", Section: 5},
		},
	}

	results, err := SynthesizeAllManPages(cfg, tempWorkspace, "1.0.0", time.Now())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(results) != 2 {
		t.Fatalf("expected 2 man page results, got %d", len(results))
	}

	if results[0].DestinationPath != "/usr/share/man/man1/app.1.gz" {
		t.Errorf("unexpected destination 0: %s", results[0].DestinationPath)
	}
	if results[1].DestinationPath != "/usr/share/man/man5/app.5.gz" {
		t.Errorf("unexpected destination 1: %s", results[1].DestinationPath)
	}
}

func TestWriteManPage(t *testing.T) {
	tempDir := t.TempDir()

	res := &ManPageResult{
		DestinationPath: "/usr/share/man/man1/tool.1.gz",
		Content:         []byte("gzipped-dummy-bytes"),
		Mode:            fsutil.FileMode,
	}

	writtenPath, err := WriteManPage(tempDir, res)
	if err != nil {
		t.Fatalf("failed to write man page: %v", err)
	}

	expectedPath := filepath.Join(tempDir, "usr", "share", "man", "man1", "tool.1.gz")
	if writtenPath != expectedPath {
		t.Errorf("expected '%s', got '%s'", expectedPath, writtenPath)
	}

	fi, err := os.Stat(writtenPath)
	if err != nil {
		t.Fatalf("failed to stat written file: %v", err)
	}

	if fi.Mode().Perm() != fsutil.FileMode {
		t.Errorf("expected permissions 0644, got %v", fi.Mode().Perm())
	}
}

func TestWriteLauncher_NilResult(t *testing.T) {
	_, err := WriteLauncher(t.TempDir(), nil)
	if err == nil {
		t.Errorf("expected error when passing nil LauncherResult to WriteLauncher")
	}
}

func TestWriteManPage_NilResult(t *testing.T) {
	_, err := WriteManPage(t.TempDir(), nil)
	if err == nil {
		t.Errorf("expected error when passing nil ManPageResult to WriteManPage")
	}
}

func TestSynthesizeAllManPages_NilConfig(t *testing.T) {
	_, err := SynthesizeAllManPages(nil, t.TempDir(), "1.0.0", time.Now())
	if err == nil {
		t.Errorf("expected error when passing nil config to SynthesizeAllManPages")
	}
}

func TestInferManPageMetadata_NilConfigAndEmpty(t *testing.T) {
	// Zero time and nil config
	meta := InferManPageMetadata(spec.ManPageConfig{}, nil, "", time.Time{})
	if meta.Title != "MANUAL" {
		t.Errorf("expected title 'MANUAL', got '%s'", meta.Title)
	}
	if meta.Section != 1 {
		t.Errorf("expected section 1, got %d", meta.Section)
	}
	if meta.Header != "User Commands Manual" {
		t.Errorf("expected default header 'User Commands Manual', got '%s'", meta.Header)
	}
	if meta.Footer != "" {
		t.Errorf("expected empty footer, got '%s'", meta.Footer)
	}
	if meta.Date == "" {
		t.Errorf("expected non-empty Date")
	}

	// Nil config with version
	metaVerOnly := InferManPageMetadata(spec.ManPageConfig{}, nil, "1.2.3", time.Now())
	if metaVerOnly.Footer != "1.2.3" {
		t.Errorf("expected footer '1.2.3', got '%s'", metaVerOnly.Footer)
	}

	// Config with name only (no version)
	cfgNameOnly := &spec.CraftpackConfig{Name: "onlyname"}
	metaNameOnly := InferManPageMetadata(spec.ManPageConfig{}, cfgNameOnly, "", time.Now())
	if metaNameOnly.Footer != "onlyname" {
		t.Errorf("expected footer 'onlyname', got '%s'", metaNameOnly.Footer)
	}
}

func TestFormatTitleHeaderDirective_TitleOnly(t *testing.T) {
	meta := ManPageMetadata{Title: "ONLYTITLE", Section: 3}
	got := FormatTitleHeaderDirective(meta)
	expected := "% ONLYTITLE(3)\n\n"
	if got != expected {
		t.Errorf("expected %q, got %q", expected, got)
	}
}

func TestCompileManPage_FrontMatterError(t *testing.T) {
	meta := ManPageMetadata{Title: "FAIL", Section: 1}
	_, _, err := CompileManPage([]byte("---\nfront: matter\n---\n"), meta, time.Now())
	if err == nil {
		t.Errorf("expected error for front matter in CompileManPage")
	}
}

func TestSanitizeCommand_InvalidCharacters(t *testing.T) {
	tests := []string{
		"cmd with space",
		"cmd!",
		"cmd@name",
		"cmd#",
	}
	for _, cmd := range tests {
		_, err := SanitizeCommand(cmd)
		if err == nil {
			t.Errorf("expected error for invalid command '%s', got nil", cmd)
		}
	}
}

// TestManPage_SystemManToolIntegration tests that the synthesized roff document can be parsed
// and formatted by the host system's `man` binary without syntax errors.
func TestManPage_SystemManToolIntegration(t *testing.T) {
	manPath, err := exec.LookPath("man")
	if err != nil {
		t.Skip("system 'man' binary not found on host, skipping integration test")
	}

	rawMarkdown := `# NAME
sample \- a sample utility for man page testing

# SYNOPSIS
**sample** [**\--verbose**] [*argument*...]

# DESCRIPTION
This is a test description verifying host man utility compatibility.
`
	meta := ManPageMetadata{
		Title:   "SAMPLE",
		Section: 1,
		Date:    "2026-09-06",
		Header:  "User Commands Manual",
		Footer:  "sample 1.0.0",
	}

	roffBytes, err := RenderRoff([]byte(rawMarkdown), meta)
	if err != nil {
		t.Fatalf("failed to render roff: %v", err)
	}

	// Invoke `man -l -` feeding roff into stdin
	cmd := exec.Command(manPath, "-l", "-")
	cmd.Stdin = bytes.NewReader(roffBytes)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("system 'man' failed to parse generated roff: %v\nOutput:\n%s\nRoff:\n%s", err, string(out), string(roffBytes))
	}

	formatted := string(out)
	if !strings.Contains(formatted, "SAMPLE") {
		t.Errorf("expected formatted man page to contain 'SAMPLE', got:\n%s", formatted)
	}
	if !strings.Contains(formatted, "SYNOPSIS") {
		t.Errorf("expected formatted man page to contain 'SYNOPSIS', got:\n%s", formatted)
	}
}
