// SPDX-FileCopyrightText: 2026 Marcin Kaim
// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileComment: Generated by AI (Gemini 3.8 Flash)

package generator

import (
	"bytes"
	"compress/gzip"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"craftpack/pkg/fsutil"
	"craftpack/pkg/spec"
	"github.com/cpuguy83/go-md2man/v2/md2man"
)

var (
	// ErrZeroMarkupViolation is returned when Markdown source violates the Zero-Markup policy
	// by including YAML front-matter or formatting metadata directives.
	ErrZeroMarkupViolation = errors.New("zero-markup policy violation")

	// ErrInvalidSection is returned when a manual page section is outside the range 1-8.
	ErrInvalidSection = errors.New("invalid manual page section: must be an integer between 1 and 8")

	// ErrEmptySource is returned when a manual page source path is empty.
	ErrEmptySource = errors.New("manual page source path cannot be empty")
)

// ManPageMetadata encapsulates the derived attributes computed by the Metadata Inference Engine.
type ManPageMetadata struct {
	Title   string // Document title (e.g., "CRAFTPACK")
	Section int    // Manual section (1 to 8)
	Date    string // Compilation date formatted as YYYY-MM-DD
	Header  string // Localized category header (e.g., "User Commands Manual")
	Footer  string // Localized footer string (e.g., "craftpack 1.0.0")
}

// ManPageResult represents the compiled, compressed manual page artifact ready for staging.
type ManPageResult struct {
	SourcePath      string          // Original relative source path (e.g., "docs/craftpack.1.md")
	DestinationPath string          // Absolute destination path (e.g., "/usr/share/man/man1/craftpack.1.gz")
	Content         []byte          // Gzip-compressed roff bytes
	RoffContent     []byte          // Uncompressed roff bytes
	Mode            os.FileMode     // Standard file permissions (0644)
	Section         int             // Manual section number
	Command         string          // Associated command name
	Metadata        ManPageMetadata // Inferred metadata used for compilation
}

// RelPath returns the relative destination path suitable for tar archive serialization.
func (r *ManPageResult) RelPath() string {
	return strings.TrimPrefix(r.DestinationPath, "/")
}

// DefaultSectionHeader returns the standard UNIX manual category label for sections 1 through 8.
func DefaultSectionHeader(section int) string {
	switch section {
	case 1:
		return "User Commands Manual"
	case 2:
		return "System Calls Manual"
	case 3:
		return "Library Functions Manual"
	case 4:
		return "Special Files Manual"
	case 5:
		return "File Formats Manual"
	case 6:
		return "Games Manual"
	case 7:
		return "Miscellaneous Information Manual"
	case 8:
		return "System Administration Commands"
	default:
		return "User Commands Manual"
	}
}

// InferManPageMetadata applies the out-of-band Metadata Inference Engine rules to derive all required attributes.
func InferManPageMetadata(mp spec.ManPageConfig, cfg *spec.CraftpackConfig, packageVersion string, buildDate time.Time) ManPageMetadata {
	var meta ManPageMetadata

	// Section: 1 to 8 (default: 1)
	if mp.Section >= 1 && mp.Section <= 8 {
		meta.Section = mp.Section
	} else {
		meta.Section = 1
	}

	// Document Title: Inferred from uppercase manPage.Title or page name (explicit/inferred) or config Command or Name
	if strings.TrimSpace(mp.Title) != "" {
		meta.Title = strings.ToUpper(strings.TrimSpace(mp.Title))
	} else if strings.TrimSpace(mp.Name) != "" {
		meta.Title = strings.ToUpper(strings.TrimSpace(mp.Name))
	} else if inferred := spec.InferManPageBaseFromSource(mp.Source, meta.Section); inferred != "" {
		meta.Title = strings.ToUpper(inferred)
	} else if cfg != nil && strings.TrimSpace(cfg.Command) != "" {
		meta.Title = strings.ToUpper(strings.TrimSpace(cfg.Command))
	} else if cfg != nil && strings.TrimSpace(cfg.Name) != "" {
		meta.Title = strings.ToUpper(strings.TrimSpace(cfg.Name))
	} else {
		meta.Title = "MANUAL"
	}

	// Compilation Date: Build date formatted as YYYY-MM-DD
	if buildDate.IsZero() {
		buildDate = time.Now().UTC()
	}
	meta.Date = buildDate.UTC().Format("2006-01-02")

	// Localized Header: manPage.Header or derived section label
	if strings.TrimSpace(mp.Header) != "" {
		meta.Header = strings.TrimSpace(mp.Header)
	} else {
		meta.Header = DefaultSectionHeader(meta.Section)
	}

	// Footer: manPage.Footer or fmt.Sprintf("%s %s", config.Name, packageVersion)
	if strings.TrimSpace(mp.Footer) != "" {
		meta.Footer = strings.TrimSpace(mp.Footer)
	} else if cfg != nil && strings.TrimSpace(cfg.Name) != "" && strings.TrimSpace(packageVersion) != "" {
		meta.Footer = fmt.Sprintf("%s %s", strings.TrimSpace(cfg.Name), strings.TrimSpace(packageVersion))
	} else if cfg != nil && strings.TrimSpace(cfg.Name) != "" {
		meta.Footer = strings.TrimSpace(cfg.Name)
	} else if strings.TrimSpace(packageVersion) != "" {
		meta.Footer = strings.TrimSpace(packageVersion)
	}

	return meta
}

// FormatTitleHeaderDirective formats the roff title header directive for md2man:
// % TITLE SECTION "DATE" "FOOTER" "HEADER"
// Translates directly into the standard roff macro:
// .TH TITLE SECTION "DATE" "FOOTER" "HEADER"
func FormatTitleHeaderDirective(meta ManPageMetadata) string {
	cleanTitle := strings.ReplaceAll(strings.ReplaceAll(strings.TrimSpace(meta.Title), "\r", ""), "\n", " ")
	cleanTitle = strings.ReplaceAll(cleanTitle, "|", "-")
	cleanTitle = strings.TrimSpace(cleanTitle)
	if cleanTitle == "" {
		cleanTitle = "MANUAL"
	}
	cleanHeader := strings.ReplaceAll(strings.ReplaceAll(strings.TrimSpace(meta.Header), "\r", ""), "\n", " ")
	cleanHeader = strings.ReplaceAll(cleanHeader, "|", "-")
	cleanHeader = strings.TrimSpace(cleanHeader)

	cleanFooter := strings.ReplaceAll(strings.ReplaceAll(strings.TrimSpace(meta.Footer), "\r", ""), "\n", " ")
	cleanFooter = strings.ReplaceAll(cleanFooter, "|", "-")
	cleanFooter = strings.TrimSpace(cleanFooter)

	cleanDate := strings.ReplaceAll(strings.ReplaceAll(strings.TrimSpace(meta.Date), "\r", ""), "\n", " ")
	cleanDate = strings.TrimSpace(cleanDate)

	section := meta.Section
	if section < 1 || section > 8 {
		section = 1
	}

	escapeArg := func(s string) string {
		return strings.ReplaceAll(s, `"`, `\"`)
	}

	if cleanHeader != "" {
		return fmt.Sprintf("%% %s %d \"%s\" \"%s\" \"%s\"\n\n",
			cleanTitle, section, escapeArg(cleanDate), escapeArg(cleanFooter), escapeArg(cleanHeader))
	} else if cleanFooter != "" {
		return fmt.Sprintf("%% %s %d \"%s\" \"%s\"\n\n",
			cleanTitle, section, escapeArg(cleanDate), escapeArg(cleanFooter))
	} else if cleanDate != "" {
		return fmt.Sprintf("%% %s %d \"%s\"\n\n",
			cleanTitle, section, escapeArg(cleanDate))
	}
	return fmt.Sprintf("%% %s %d\n\n", cleanTitle, section)
}

// ValidateZeroMarkup verifies that markdown source does not contain YAML front-matter ('---')
// or TOML front-matter ('+++').
func ValidateZeroMarkup(markdown []byte) error {
	trimmed := strings.TrimSpace(string(bytes.TrimPrefix(markdown, []byte("\xef\xbb\xbf"))))
	if strings.HasPrefix(trimmed, "---") {
		return fmt.Errorf("%w: YAML front-matter ('---') detected", ErrZeroMarkupViolation)
	}
	if strings.HasPrefix(trimmed, "+++") {
		return fmt.Errorf("%w: TOML front-matter ('+++') detected", ErrZeroMarkupViolation)
	}
	return nil
}

// RenderRoff executes On-the-Fly Staging: checks Zero-Markup, prepends synthesized title directive,
// and compiles the composite markdown buffer to roff format using md2man.
func RenderRoff(markdown []byte, meta ManPageMetadata) ([]byte, error) {
	cleanMarkdown := bytes.TrimPrefix(markdown, []byte("\xef\xbb\xbf"))
	if err := ValidateZeroMarkup(cleanMarkdown); err != nil {
		return nil, err
	}

	headerDirective := FormatTitleHeaderDirective(meta)
	var composite bytes.Buffer
	composite.WriteString(headerDirective)
	composite.Write(cleanMarkdown)

	roff := md2man.Render(composite.Bytes())
	return roff, nil
}

// CompressRoff compresses rendered roff bytes using gzip level 9 with deterministic zero timestamp.
func CompressRoff(roff []byte, modTime time.Time) ([]byte, error) {
	var buf bytes.Buffer
	gw, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if err != nil {
		return nil, fmt.Errorf("failed to create gzip writer: %w", err)
	}
	gw.Header.ModTime = time.Time{} // Zero timestamp per Debian Policy §12.1 and Reproducible Builds
	gw.Header.OS = 255              // Unknown / non-specific OS for deterministic reproducibility

	if _, err := gw.Write(roff); err != nil {
		return nil, fmt.Errorf("failed to compress roff bytes: %w", err)
	}
	if err := gw.Close(); err != nil {
		return nil, fmt.Errorf("failed to close gzip writer: %w", err)
	}
	return buf.Bytes(), nil
}

// CompileManPage compiles raw Markdown bytes to roff and gzip compresses it in memory.
// Returns (compressedBytes, roffBytes, error).
func CompileManPage(markdown []byte, meta ManPageMetadata, modTime time.Time) ([]byte, []byte, error) {
	roff, err := RenderRoff(markdown, meta)
	if err != nil {
		return nil, nil, err
	}

	compressed, err := CompressRoff(roff, modTime)
	if err != nil {
		return nil, nil, err
	}

	return compressed, roff, nil
}

// SynthesizeManPage compiles a mapped markdown source file into a compressed manual page.
func SynthesizeManPage(mp spec.ManPageConfig, cfg *spec.CraftpackConfig, workspaceDir, packageVersion string, buildDate time.Time) (*ManPageResult, error) {
	if mp.Source == "" {
		return nil, ErrEmptySource
	}
	if mp.Section < 1 || mp.Section > 8 {
		return nil, fmt.Errorf("%w: %d", ErrInvalidSection, mp.Section)
	}

	// Boundary-checked resolution within workspace
	resolvedPath, err := fsutil.AssertWithinWorkspace(workspaceDir, mp.Source)
	if err != nil {
		return nil, fmt.Errorf("man page source '%s' boundary violation: %w", mp.Source, err)
	}

	fi, err := os.Stat(resolvedPath)
	if err != nil {
		return nil, fmt.Errorf("failed to stat man page source '%s': %w", mp.Source, err)
	}
	if fi.IsDir() {
		return nil, fmt.Errorf("man page source '%s' is a directory, expected regular file", mp.Source)
	}

	markdownBytes, err := os.ReadFile(resolvedPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read man page source '%s': %w", mp.Source, err)
	}

	meta := InferManPageMetadata(mp, cfg, packageVersion, buildDate)

	compressed, roff, err := CompileManPage(markdownBytes, meta, buildDate)
	if err != nil {
		return nil, fmt.Errorf("failed to compile man page '%s': %w", mp.Source, err)
	}

	// Determine output filename
	pageName := InferManPageOutputName(mp, cfg, meta.Section)
	destPath := fmt.Sprintf("/usr/share/man/man%d/%s.%d.gz", meta.Section, pageName, meta.Section)

	return &ManPageResult{
		SourcePath:      mp.Source,
		DestinationPath: destPath,
		Content:         compressed,
		RoffContent:     roff,
		Mode:            fsutil.FileMode,
		Section:         meta.Section,
		Command:         pageName,
		Metadata:        meta,
	}, nil
}

// InferManPageOutputName determines the output manual page filename base (without section and .gz).
// Delegates to spec.InferManPageOutputName to guarantee unified inference rules.
func InferManPageOutputName(mp spec.ManPageConfig, cfg *spec.CraftpackConfig, section int) string {
	return spec.InferManPageOutputName(mp, cfg, section)
}

// SynthesizeAllManPages synthesizes all man pages defined in cfg.ManPages, checking for destination collisions.
func SynthesizeAllManPages(cfg *spec.CraftpackConfig, workspaceDir, packageVersion string, buildDate time.Time) ([]*ManPageResult, error) {
	if cfg == nil {
		return nil, errors.New("craftpack config cannot be nil")
	}
	var results []*ManPageResult
	seenDests := make(map[string]string)
	for _, mp := range cfg.ManPages {
		res, err := SynthesizeManPage(mp, cfg, workspaceDir, packageVersion, buildDate)
		if err != nil {
			return nil, err
		}
		if prevSrc, exists := seenDests[res.DestinationPath]; exists {
			return nil, fmt.Errorf("man page destination collision: '%s' and '%s' both resolve to '%s'", prevSrc, mp.Source, res.DestinationPath)
		}
		seenDests[res.DestinationPath] = mp.Source
		results = append(results, res)
	}
	return results, nil
}

// WriteManPage writes the synthesized man page result to destDir with 0644 permissions.
func WriteManPage(destDir string, res *ManPageResult) (string, error) {
	if res == nil {
		return "", errors.New("man page result cannot be nil")
	}
	cleanRel := strings.TrimPrefix(filepath.Clean(res.DestinationPath), "/")
	fullDest, err := fsutil.AssertWithinWorkspace(destDir, cleanRel)
	if err != nil {
		return "", fmt.Errorf("man page destination path '%s' escapes '%s': %w", res.DestinationPath, destDir, err)
	}

	if err := os.MkdirAll(filepath.Dir(fullDest), fsutil.DirMode); err != nil {
		return "", fmt.Errorf("failed to create man page directory: %w", err)
	}

	if err := os.WriteFile(fullDest, res.Content, res.Mode); err != nil {
		return "", fmt.Errorf("failed to write man page file: %w", err)
	}

	return fullDest, nil
}
