// SPDX-FileCopyrightText: 2026 Marcin Kaim
// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileComment: Generated by AI (Gemini 3.8 Flash)

package validator_test

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"craftpack/pkg/validator"
)

func writeMinimalSpec(t *testing.T, dir, payloadDir, entrypoint string) string {
	t.Helper()
	content := fmt.Sprintf(`name: test-app
description: Standard test application description
maintainer: Test Maintainer <test@example.com>
homepage: https://example.com/test-app
license: MIT
command: test-app
payload_dir: %s
entrypoint: %s
targets:
  deb:
    section: utils
    priority: optional
`, payloadDir, entrypoint)

	specPath := filepath.Join(dir, "craftpack.yml")
	if err := os.WriteFile(specPath, []byte(content), 0644); err != nil {
		t.Fatalf("failed writing craftpack.yml: %v", err)
	}
	return specPath
}

func TestValidate_ConfigOnly(t *testing.T) {
	dir := t.TempDir()
	// Point to non-existent payload_dir
	specPath := writeMinimalSpec(t, dir, "non-existent-payload", "bin/test-app")

	// Standard validation should fail because payload_dir doesn't exist on disk
	res, err := validator.Validate(validator.Options{
		SpecPath:     specPath,
		WorkspaceDir: dir,
		ConfigOnly:   false,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if res.Valid {
		t.Errorf("expected standard validation to fail when payload_dir is missing")
	}

	// ConfigOnly validation should succeed because it skips filesystem payload checks
	resConfigOnly, err := validator.Validate(validator.Options{
		SpecPath:     specPath,
		WorkspaceDir: dir,
		ConfigOnly:   true,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !resConfigOnly.Valid {
		t.Errorf("expected config-only validation to succeed, got errors: %v", resConfigOnly.Errors)
	}
}

func TestValidate_NonExecutableEntrypoint(t *testing.T) {
	dir := t.TempDir()
	payloadDir := filepath.Join(dir, "bin")
	if err := os.MkdirAll(payloadDir, 0755); err != nil {
		t.Fatalf("failed creating payload dir: %v", err)
	}

	entryPath := filepath.Join(payloadDir, "script.sh")
	// Write with non-executable permissions 0644
	if err := os.WriteFile(entryPath, []byte("#!/bin/sh\necho hello\n"), 0644); err != nil {
		t.Fatalf("failed writing entrypoint: %v", err)
	}

	specPath := writeMinimalSpec(t, dir, "bin", "script.sh")

	// In non-strict mode, non-executable is a warning, so Valid is true
	res, err := validator.Validate(validator.Options{
		SpecPath:     specPath,
		WorkspaceDir: dir,
		Strict:       false,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !res.Valid {
		t.Errorf("expected non-strict validation to pass, got errors: %v", res.Errors)
	}
	hasWarning := false
	for _, w := range res.Warnings {
		if strings.Contains(w, "no executable permissions") {
			hasWarning = true
			break
		}
	}
	if !hasWarning {
		t.Errorf("expected warning about non-executable permissions, got warnings: %v", res.Warnings)
	}

	// In strict mode, warning causes Valid to be false
	resStrict, err := validator.Validate(validator.Options{
		SpecPath:     specPath,
		WorkspaceDir: dir,
		Strict:       true,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resStrict.Valid {
		t.Errorf("expected strict validation to fail due to non-executable warning")
	}
}

func TestValidate_NonELFScript(t *testing.T) {
	dir := t.TempDir()
	payloadDir := filepath.Join(dir, "bin")
	if err := os.MkdirAll(payloadDir, 0755); err != nil {
		t.Fatalf("failed creating payload dir: %v", err)
	}

	entryPath := filepath.Join(payloadDir, "runner.sh")
	if err := os.WriteFile(entryPath, []byte("#!/bin/sh\nexit 0\n"), 0755); err != nil {
		t.Fatalf("failed writing entrypoint: %v", err)
	}

	specPath := writeMinimalSpec(t, dir, "bin", "runner.sh")

	res, err := validator.Validate(validator.Options{
		SpecPath:     specPath,
		WorkspaceDir: dir,
		Strict:       true,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !res.Valid {
		t.Errorf("expected script validation to pass in strict mode, got errors: %v", res.Errors)
	}
	for _, w := range res.Warnings {
		if strings.Contains(w, "PIE") || strings.Contains(w, "unstripped") {
			t.Errorf("non-ELF script should not trigger ELF warnings, got: %s", w)
		}
	}
}

func TestValidate_ELF_Inspection(t *testing.T) {
	dir := t.TempDir()
	payloadDir := filepath.Join(dir, "bin")
	if err := os.MkdirAll(payloadDir, 0755); err != nil {
		t.Fatalf("failed creating payload dir: %v", err)
	}

	srcFile := filepath.Join(dir, "main.go")
	if err := os.WriteFile(srcFile, []byte("package main\nfunc main() {}\n"), 0644); err != nil {
		t.Fatalf("failed writing dummy source: %v", err)
	}

	// 1. Build unstripped, non-PIE binary
	unstrippedBin := filepath.Join(payloadDir, "unstripped-app")
	cmdBuild1 := exec.Command("go", "build", "-o", unstrippedBin, srcFile)
	cmdBuild1.Env = append(os.Environ(), "CGO_ENABLED=0")
	if out, err := cmdBuild1.CombinedOutput(); err != nil {
		t.Skipf("skipping ELF test: unable to compile Go binary: %v\nOutput: %s", err, string(out))
	}

	specPath1 := writeMinimalSpec(t, dir, "bin", "unstripped-app")

	res1, err := validator.Validate(validator.Options{
		SpecPath:     specPath1,
		WorkspaceDir: dir,
		Strict:       false,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !res1.Valid {
		t.Errorf("expected non-strict validation to pass, got errors: %v", res1.Errors)
	}

	hasUnstrippedWarn := false
	hasNonPIEWarn := false
	for _, w := range res1.Warnings {
		if strings.Contains(w, "unstripped") {
			hasUnstrippedWarn = true
		}
		if strings.Contains(w, "PIE") {
			hasNonPIEWarn = true
		}
	}
	if !hasUnstrippedWarn {
		t.Errorf("expected warning for unstripped binary, got: %v", res1.Warnings)
	}
	if !hasNonPIEWarn {
		t.Errorf("expected warning for non-PIE binary, got: %v", res1.Warnings)
	}

	// In strict mode, it must fail
	res1Strict, err := validator.Validate(validator.Options{
		SpecPath:     specPath1,
		WorkspaceDir: dir,
		Strict:       true,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if res1Strict.Valid {
		t.Errorf("expected strict validation to fail on unstripped/non-PIE warnings")
	}

	// 2. Build stripped, PIE binary
	hardenedBin := filepath.Join(payloadDir, "hardened-app")
	cmdBuild2 := exec.Command("go", "build", "-buildmode=pie", "-ldflags=-s -w", "-o", hardenedBin, srcFile)
	cmdBuild2.Env = append(os.Environ(), "CGO_ENABLED=0")
	if out, err := cmdBuild2.CombinedOutput(); err != nil {
		t.Skipf("skipping ELF test: unable to compile PIE binary: %v\nOutput: %s", err, string(out))
	}

	specPath2 := writeMinimalSpec(t, dir, "bin", "hardened-app")

	res2, err := validator.Validate(validator.Options{
		SpecPath:     specPath2,
		WorkspaceDir: dir,
		Strict:       true,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !res2.Valid {
		t.Errorf("expected hardened binary to pass strict validation, got errors: %v, warnings: %v", res2.Errors, res2.Warnings)
	}
}

func TestValidate_ManPageValidation(t *testing.T) {
	dir := t.TempDir()
	payloadDir := filepath.Join(dir, "bin")
	_ = os.MkdirAll(payloadDir, 0755)
	_ = os.WriteFile(filepath.Join(payloadDir, "app"), []byte("#!/bin/sh\n"), 0755)

	docsDir := filepath.Join(dir, "docs")
	_ = os.MkdirAll(docsDir, 0755)
	validManPath := filepath.Join(docsDir, "app.1.md")
	_ = os.WriteFile(validManPath, []byte("# app(1)\n\n## NAME\napp - dummy\n"), 0644)

	specContent := fmt.Sprintf(`name: man-app
description: Man page validation test
maintainer: Tester <tester@example.com>
homepage: https://example.com/man
license: MIT
command: man-app
payload_dir: bin
entrypoint: app
man_pages:
  - source: docs/app.1.md
    section: 1
targets:
  deb:
    section: utils
`)
	specPath := filepath.Join(dir, "craftpack.yml")
	_ = os.WriteFile(specPath, []byte(specContent), 0644)

	res, err := validator.Validate(validator.Options{
		SpecPath:     specPath,
		WorkspaceDir: dir,
		Strict:       true,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !res.Valid {
		t.Errorf("expected valid man page to pass validation, got errors: %v", res.Errors)
	}
}

func TestValidate_NoticeUTF8(t *testing.T) {
	dir := t.TempDir()
	payloadDir := filepath.Join(dir, "bin")
	_ = os.MkdirAll(payloadDir, 0755)
	_ = os.WriteFile(filepath.Join(payloadDir, "app"), []byte("#!/bin/sh\n"), 0755)

	// Write invalid UTF-8 bytes to NOTICE
	noticePath := filepath.Join(dir, "NOTICE")
	_ = os.WriteFile(noticePath, []byte{0xff, 0xfe, 0xfd}, 0644)

	specPath := writeMinimalSpec(t, dir, "bin", "app")

	res, err := validator.Validate(validator.Options{
		SpecPath:     specPath,
		WorkspaceDir: dir,
		Strict:       false,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if res.Valid {
		t.Errorf("expected invalid UTF-8 NOTICE to fail validation")
	}
	hasNoticeErr := false
	for _, e := range res.Errors {
		if strings.Contains(e, "NOTICE") && strings.Contains(e, "UTF-8") {
			hasNoticeErr = true
			break
		}
	}
	if !hasNoticeErr {
		t.Errorf("expected NOTICE UTF-8 error, got: %v", res.Errors)
	}
}

func TestValidate_CustomChangelogMissing(t *testing.T) {
	dir := t.TempDir()
	payloadDir := filepath.Join(dir, "bin")
	_ = os.MkdirAll(payloadDir, 0755)
	_ = os.WriteFile(filepath.Join(payloadDir, "app"), []byte("#!/bin/sh\n"), 0755)

	specContent := `name: changelog-app
description: Changelog validation test
maintainer: Tester <tester@example.com>
homepage: https://example.com/changelog
license: MIT
command: changelog-app
payload_dir: bin
entrypoint: app
changelog: docs/missing_changelog.Debian
targets:
  deb:
    section: utils
`
	specPath := filepath.Join(dir, "craftpack.yml")
	_ = os.WriteFile(specPath, []byte(specContent), 0644)

	res, err := validator.Validate(validator.Options{
		SpecPath:     specPath,
		WorkspaceDir: dir,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if res.Valid {
		t.Errorf("expected validation to fail on missing changelog file")
	}
	hasClErr := false
	for _, e := range res.Errors {
		if strings.Contains(e, "changelog") && (strings.Contains(e, "not found") || strings.Contains(e, "does not exist")) {
			hasClErr = true
			break
		}
	}
	if !hasClErr {
		t.Errorf("expected changelog missing error, got: %v", res.Errors)
	}
}

func TestValidate_TargetFilter(t *testing.T) {
	dir := t.TempDir()
	payloadDir := filepath.Join(dir, "bin")
	_ = os.MkdirAll(payloadDir, 0755)
	_ = os.WriteFile(filepath.Join(payloadDir, "app"), []byte("#!/bin/sh\n"), 0755)

	specPath := writeMinimalSpec(t, dir, "bin", "app")

	// Target deb matches
	resDeb, err := validator.Validate(validator.Options{
		SpecPath:     specPath,
		WorkspaceDir: dir,
		Target:       "deb",
		Strict:       true,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !resDeb.Valid {
		t.Errorf("expected target deb validation to succeed, got errors: %v", resDeb.Errors)
	}
}
