// SPDX-FileCopyrightText: 2026 Marcin Kaim
// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileComment: Generated by AI (Gemini 3.8 Flash)

package integration_test

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto/md5"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"testing"

	"github.com/blakesmith/ar"
)

var (
	binPathOnce sync.Once
	binaryPath  string
	buildErr    error
)

// getCraftpackBinary builds the craftpack CLI executable once and returns its path.
func getCraftpackBinary(t *testing.T) string {
	t.Helper()
	binPathOnce.Do(func() {
		tmpDir, err := os.MkdirTemp("", "craftpack-integ-bin-*")
		if err != nil {
			buildErr = err
			return
		}
		targetBin := filepath.Join(tmpDir, "craftpack")

		// Locate project root relative to test/integration
		rootDir, err := filepath.Abs("../..")
		if err != nil {
			buildErr = err
			return
		}

		cmd := exec.Command("go", "build", "-ldflags=-s -w", "-o", targetBin, "./cmd/craftpack")
		cmd.Dir = rootDir
		cmd.Env = append(os.Environ(), "CGO_ENABLED=0")
		output, err := cmd.CombinedOutput()
		if err != nil {
			buildErr = fmt.Errorf("failed to compile craftpack CLI: %w\nOutput: %s", err, string(output))
			return
		}
		binaryPath = targetBin
	})

	if buildErr != nil {
		t.Fatalf("getCraftpackBinary failed: %v", buildErr)
	}
	return binaryPath
}

// UnpackedDeb represents the dissected contents and metadata of a Debian package (.deb).
type UnpackedDeb struct {
	DebianBinary string
	ControlFiles map[string][]byte
	DataFiles    map[string][]byte
	DataHeaders  map[string]*tar.Header
}

// unpackDeb opens a .deb archive using pure Go and validates its ar structure and payloads.
func unpackDeb(t *testing.T, debPath string) *UnpackedDeb {
	t.Helper()

	f, err := os.Open(debPath)
	if err != nil {
		t.Fatalf("failed to open deb file %q: %v", debPath, err)
	}
	defer f.Close()

	arReader := ar.NewReader(f)
	result := &UnpackedDeb{
		ControlFiles: make(map[string][]byte),
		DataFiles:    make(map[string][]byte),
		DataHeaders:  make(map[string]*tar.Header),
	}

	// 1. Entry 1: debian-binary
	hdr1, err := arReader.Next()
	if err != nil {
		t.Fatalf("failed reading ar header 1: %v", err)
	}
	if hdr1.Name != "debian-binary" {
		t.Errorf("ar entry 1: name = %q, want 'debian-binary'", hdr1.Name)
	}
	if hdr1.Mode != 0644 {
		t.Errorf("ar entry 1: mode = %o, want 0644", hdr1.Mode)
	}
	content1, err := io.ReadAll(arReader)
	if err != nil {
		t.Fatalf("failed reading debian-binary: %v", err)
	}
	result.DebianBinary = string(content1)
	if result.DebianBinary != "2.0\n" {
		t.Errorf("debian-binary content = %q, want '2.0\\n'", result.DebianBinary)
	}

	// 2. Entry 2: control.tar.gz
	hdr2, err := arReader.Next()
	if err != nil {
		t.Fatalf("failed reading ar header 2: %v", err)
	}
	if hdr2.Name != "control.tar.gz" {
		t.Errorf("ar entry 2: name = %q, want 'control.tar.gz'", hdr2.Name)
	}
	if hdr2.Mode != 0644 {
		t.Errorf("ar entry 2: mode = %o, want 0644", hdr2.Mode)
	}
	controlBytes, err := io.ReadAll(arReader)
	if err != nil {
		t.Fatalf("failed reading control.tar.gz bytes: %v", err)
	}

	gzControl, err := gzip.NewReader(bytes.NewReader(controlBytes))
	if err != nil {
		t.Fatalf("failed creating gzip reader for control.tar.gz: %v", err)
	}
	defer gzControl.Close()

	tarControl := tar.NewReader(gzControl)
	for {
		thdr, err := tarControl.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatalf("failed reading control tar header: %v", err)
		}

		// Verify deterministic ownership
		if thdr.Uid != 0 || thdr.Gid != 0 {
			t.Errorf("control tar header %s: Uid/Gid = %d/%d, want 0/0", thdr.Name, thdr.Uid, thdr.Gid)
		}
		if thdr.Uname != "root" || thdr.Gname != "root" {
			t.Errorf("control tar header %s: Uname/Gname = %q/%q, want root/root", thdr.Name, thdr.Uname, thdr.Gname)
		}

		cleanName := strings.TrimPrefix(filepath.Clean(thdr.Name), "./")
		cleanName = strings.TrimPrefix(cleanName, ".")
		cleanName = strings.TrimPrefix(cleanName, "/")

		if thdr.Typeflag == tar.TypeReg {
			data, err := io.ReadAll(tarControl)
			if err != nil {
				t.Fatalf("failed reading file %s in control.tar.gz: %v", thdr.Name, err)
			}
			result.ControlFiles[cleanName] = data
		}
	}

	// 3. Entry 3: data.tar.gz
	hdr3, err := arReader.Next()
	if err != nil {
		t.Fatalf("failed reading ar header 3: %v", err)
	}
	if hdr3.Name != "data.tar.gz" {
		t.Errorf("ar entry 3: name = %q, want 'data.tar.gz'", hdr3.Name)
	}
	if hdr3.Mode != 0644 {
		t.Errorf("ar entry 3: mode = %o, want 0644", hdr3.Mode)
	}
	dataBytes, err := io.ReadAll(arReader)
	if err != nil {
		t.Fatalf("failed reading data.tar.gz bytes: %v", err)
	}

	gzData, err := gzip.NewReader(bytes.NewReader(dataBytes))
	if err != nil {
		t.Fatalf("failed creating gzip reader for data.tar.gz: %v", err)
	}
	defer gzData.Close()

	tarData := tar.NewReader(gzData)
	for {
		thdr, err := tarData.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatalf("failed reading data tar header: %v", err)
		}

		// Verify deterministic ownership
		if thdr.Uid != 0 || thdr.Gid != 0 {
			t.Errorf("data tar header %s: Uid/Gid = %d/%d, want 0/0", thdr.Name, thdr.Uid, thdr.Gid)
		}
		if thdr.Uname != "root" || thdr.Gname != "root" {
			t.Errorf("data tar header %s: Uname/Gname = %q/%q, want root/root", thdr.Name, thdr.Uname, thdr.Gname)
		}

		cleanPath := "/" + strings.TrimPrefix(filepath.ToSlash(filepath.Clean(thdr.Name)), "./")
		cleanPath = filepath.Clean(cleanPath)

		result.DataHeaders[cleanPath] = thdr

		if thdr.Typeflag == tar.TypeReg {
			data, err := io.ReadAll(tarData)
			if err != nil {
				t.Fatalf("failed reading file %s in data.tar.gz: %v", thdr.Name, err)
			}
			result.DataFiles[cleanPath] = data
		}
	}

	// Verify no trailing entries in ar container
	_, err = arReader.Next()
	if err != io.EOF {
		t.Errorf("expected EOF after data.tar.gz, got: %v", err)
	}

	return result
}

func TestIntegration_Build_ValidMinimal(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/valid-minimal/craftpack.yml")
	outDir := t.TempDir()

	cmd := exec.Command(bin,
		"build",
		"--spec", specPath,
		"--target", "deb",
		"--package-version", "1.0.0",
		"--output-dir", outDir,
		"-v",
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	if err != nil {
		t.Fatalf("craftpack build failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	// 1. STDOUT must be 0 bytes (strict stream separation)
	if stdout.Len() != 0 {
		t.Errorf("STDOUT must be clean (0 bytes), got %d bytes:\n%s", stdout.Len(), stdout.String())
	}

	// 2. Locate generated .deb package
	entries, err := os.ReadDir(outDir)
	if err != nil {
		t.Fatalf("failed reading outDir: %v", err)
	}

	var debFile string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".deb") {
			debFile = filepath.Join(outDir, e.Name())
			break
		}
	}
	if debFile == "" {
		t.Fatalf("no .deb package found in output directory %s", outDir)
	}

	// 3. Unpack and verify pure-Go .deb structure
	unpacked := unpackDeb(t, debFile)

	// Verify control file
	ctrlData, ok := unpacked.ControlFiles["control"]
	if !ok {
		t.Fatalf("DEBIAN/control not found in control.tar.gz")
	}
	ctrlStr := string(ctrlData)
	if !strings.Contains(ctrlStr, "Package: minimal-app") {
		t.Errorf("control missing Package: minimal-app\n%s", ctrlStr)
	}
	if !strings.Contains(ctrlStr, "Version: 1.0.0") {
		t.Errorf("control missing Version: 1.0.0\n%s", ctrlStr)
	}
	if !strings.Contains(ctrlStr, "Maintainer: Jane Doe <jane.doe@example.com>") {
		t.Errorf("control missing Maintainer\n%s", ctrlStr)
	}

	// Verify conffiles is omitted when default_config is empty
	if _, ok := unpacked.ControlFiles["conffiles"]; ok {
		t.Errorf("conffiles should not exist when default_config is omitted")
	}

	// Verify direct binary in data.tar.gz at /usr/bin/minimal-app
	binData, ok := unpacked.DataFiles["/usr/bin/minimal-app"]
	if !ok {
		t.Fatalf("/usr/bin/minimal-app missing in data.tar.gz")
	}
	if !strings.Contains(string(binData), "minimal-app running") {
		t.Errorf("binary content unexpected: %s", string(binData))
	}
	binStr := string(binData)
	if strings.Contains(binStr, "REAL_PAYLOAD") {
		t.Errorf("expected direct binary at /usr/bin/minimal-app, got proxy launcher script: %s", binStr)
	}

	// Verify /usr/lib is NOT present in direct single-binary mode
	if _, ok := unpacked.DataFiles["/usr/lib/minimal-app/minimal-app"]; ok {
		t.Errorf("unexpected payload in /usr/lib/minimal-app/minimal-app in direct mode")
	}
	for path := range unpacked.DataFiles {
		if strings.HasPrefix(path, "/usr/lib") {
			t.Errorf("unexpected entry under /usr/lib in single binary mode: %s", path)
		}
	}

	// Verify binary permissions
	binHdr := unpacked.DataHeaders["/usr/bin/minimal-app"]
	if binHdr.Mode != 0755 {
		t.Errorf("binary permissions = %o, want 0755", binHdr.Mode)
	}

	// 4. Verify checksums.sha256 manifest
	manifestPath := filepath.Join(outDir, "checksums.sha256")
	manifestData, err := os.ReadFile(manifestPath)
	if err != nil {
		t.Fatalf("failed reading manifest: %v", err)
	}

	debBytes, _ := os.ReadFile(debFile)
	actualHash := sha256.Sum256(debBytes)
	actualHashStr := hex.EncodeToString(actualHash[:])
	actualSize := len(debBytes)

	manifestLine := string(manifestData)
	if !strings.Contains(manifestLine, actualHashStr) {
		t.Errorf("manifest does not contain actual SHA-256 hash %s:\n%s", actualHashStr, manifestLine)
	}
	if !strings.Contains(manifestLine, filepath.Base(debFile)) {
		t.Errorf("manifest does not contain package filename %s:\n%s", filepath.Base(debFile), manifestLine)
	}
	if !strings.Contains(manifestLine, fmt.Sprintf("(%d bytes)", actualSize)) {
		t.Errorf("manifest does not contain file size %d bytes:\n%s", actualSize, manifestLine)
	}
}

func TestIntegration_Build_ValidFull(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/valid-full/craftpack.yml")
	outDir := t.TempDir()

	// Use leading v in package version to assert normalization
	cmd := exec.Command(bin,
		"build",
		"--spec", specPath,
		"--target", "deb",
		"--package-version", "v2.1.0",
		"--output-dir", outDir,
		"-v",
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	if err != nil {
		t.Fatalf("craftpack build failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	// STDOUT clean
	if stdout.Len() != 0 {
		t.Errorf("STDOUT must be 0 bytes, got: %s", stdout.String())
	}

	// Locate .deb package
	entries, _ := os.ReadDir(outDir)
	var debFile string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".deb") {
			debFile = filepath.Join(outDir, e.Name())
			break
		}
	}
	if debFile == "" {
		t.Fatalf("no .deb package created in %s", outDir)
	}

	unpacked := unpackDeb(t, debFile)

	// 1. Verify control metadata
	ctrlData := string(unpacked.ControlFiles["control"])
	if !strings.Contains(ctrlData, "Package: full-app") {
		t.Errorf("control missing Package: full-app")
	}
	if !strings.Contains(ctrlData, "Version: 2.1.0") {
		t.Errorf("control missing normalized Version: 2.1.0 (got %s)", ctrlData)
	}
	if !strings.Contains(ctrlData, "Depends: libc6 (>= 2.31), ca-certificates") {
		t.Errorf("control missing Depends: %s", ctrlData)
	}
	if !strings.Contains(ctrlData, "Section: utils") {
		t.Errorf("control missing Section: utils")
	}
	if !strings.Contains(ctrlData, "Priority: optional") {
		t.Errorf("control missing Priority: optional")
	}

	// 2. Verify conffiles in control.tar.gz
	conffilesData, ok := unpacked.ControlFiles["conffiles"]
	if !ok {
		t.Fatalf("DEBIAN/conffiles missing in control.tar.gz")
	}
	if !strings.Contains(string(conffilesData), "/etc/full-app/full-app.conf") {
		t.Errorf("conffiles missing /etc/full-app/full-app.conf:\n%s", string(conffilesData))
	}

	// 3. Verify maintainer script hooks with set -e
	hooks := []string{"preinst", "postinst", "prerm", "postrm"}
	for _, hook := range hooks {
		hookData, ok := unpacked.ControlFiles[hook]
		if !ok {
			t.Errorf("DEBIAN/%s missing in control.tar.gz", hook)
			continue
		}
		hookStr := string(hookData)
		if !strings.HasPrefix(hookStr, "#!/bin/sh") {
			t.Errorf("hook %s missing #!/bin/sh: %s", hook, hookStr)
		}
		if !strings.Contains(hookStr, "set -e") {
			t.Errorf("hook %s missing set -e: %s", hook, hookStr)
		}
		if !strings.Contains(hookStr, hook+" running") {
			t.Errorf("hook %s missing expected body: %s", hook, hookStr)
		}
	}

	// 4. Verify md5sums in control.tar.gz
	md5Data, ok := unpacked.ControlFiles["md5sums"]
	if !ok {
		t.Fatalf("DEBIAN/md5sums missing in control.tar.gz")
	}
	md5Lines := strings.Split(strings.TrimSpace(string(md5Data)), "\n")

	// Verify alphabetical ordering of md5sums by path
	var pathsInMd5 []string
	for _, line := range md5Lines {
		parts := strings.Fields(line)
		if len(parts) == 2 {
			pathsInMd5 = append(pathsInMd5, parts[1])
		}
	}
	if !sort.StringsAreSorted(pathsInMd5) {
		t.Errorf("md5sums entries not alphabetically sorted by path: %v", pathsInMd5)
	}

	// Verify md5 hash accuracy
	for _, line := range md5Lines {
		parts := strings.Fields(line)
		if len(parts) != 2 {
			continue
		}
		expectedHash := parts[0]
		relPath := "/" + parts[1]

		fileData, exists := unpacked.DataFiles[relPath]
		if !exists {
			t.Errorf("md5sums references path %s which does not exist in data.tar.gz", relPath)
			continue
		}
		actualSum := md5.Sum(fileData)
		actualHashStr := hex.EncodeToString(actualSum[:])
		if actualHashStr != expectedHash {
			t.Errorf("md5 mismatch for %s: got %s, want %s", relPath, actualHashStr, expectedHash)
		}
	}

	// 5. Verify data layout: launcher
	launcherData := string(unpacked.DataFiles["/usr/bin/full-app"])
	if !strings.Contains(launcherData, `REAL_PAYLOAD="/usr/lib/full-app/bin/engine"`) {
		t.Errorf("launcher target payload incorrect: %s", launcherData)
	}
	if !strings.Contains(launcherData, `exec "$REAL_PAYLOAD" "$@"`) {
		t.Errorf("launcher missing exec delegation: %s", launcherData)
	}
	launcherHdr := unpacked.DataHeaders["/usr/bin/full-app"]
	if launcherHdr.Mode != 0755 {
		t.Errorf("launcher permissions = %o, want 0755", launcherHdr.Mode)
	}

	// 5b. Verify isolated private payload binary and auxiliary assets in /usr/lib/full-app/
	engineData, ok := unpacked.DataFiles["/usr/lib/full-app/bin/engine"]
	if !ok {
		t.Fatalf("/usr/lib/full-app/bin/engine missing in data.tar.gz")
	}
	if !strings.Contains(string(engineData), "engine running") {
		t.Errorf("engine binary content unexpected: %s", string(engineData))
	}
	engineHdr := unpacked.DataHeaders["/usr/lib/full-app/bin/engine"]
	if engineHdr.Mode != 0755 {
		t.Errorf("engine binary permissions = %o, want 0755", engineHdr.Mode)
	}

	assetData, ok := unpacked.DataFiles["/usr/lib/full-app/share/asset.txt"]
	if !ok {
		t.Fatalf("/usr/lib/full-app/share/asset.txt missing in data.tar.gz")
	}
	if !strings.Contains(string(assetData), "Sample asset file content for testing") {
		t.Errorf("auxiliary asset content unexpected: %s", string(assetData))
	}
	assetHdr := unpacked.DataHeaders["/usr/lib/full-app/share/asset.txt"]
	if assetHdr.Mode != 0644 {
		t.Errorf("auxiliary asset permissions = %o, want 0644", assetHdr.Mode)
	}

	// 6. Verify documentation: compressed man page
	manGzData, ok := unpacked.DataFiles["/usr/share/man/man1/full-app.1.gz"]
	if !ok {
		t.Fatalf("/usr/share/man/man1/full-app.1.gz missing in data.tar.gz")
	}
	gzMan, err := gzip.NewReader(bytes.NewReader(manGzData))
	if err != nil {
		t.Fatalf("failed reading gzipped manpage: %v", err)
	}
	manRoff, err := io.ReadAll(gzMan)
	_ = gzMan.Close()
	if err != nil {
		t.Fatalf("failed decompressing man page: %v", err)
	}
	if !strings.Contains(string(manRoff), "FULL-APP") && !strings.Contains(string(manRoff), "full-app") {
		t.Errorf("man page missing title: %s", string(manRoff))
	}

	// 7. Verify config template deployed to /etc/full-app/full-app.conf
	confData, ok := unpacked.DataFiles["/etc/full-app/full-app.conf"]
	if !ok {
		t.Fatalf("/etc/full-app/full-app.conf missing in data.tar.gz")
	}
	if !strings.Contains(string(confData), "server_port = 8080") {
		t.Errorf("config template content unexpected: %s", string(confData))
	}
}

func TestIntegration_Build_RejectsTraversal(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/invalid-traversal/craftpack.yml")
	outDir := t.TempDir()

	cmd := exec.Command(bin,
		"build",
		"--spec", specPath,
		"--target", "deb",
		"--package-version", "1.0.0",
		"--output-dir", outDir,
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	if err == nil {
		t.Fatalf("expected build to fail for traversal exploit, but succeeded")
	}

	exitErr, ok := err.(*exec.ExitError)
	if !ok {
		t.Fatalf("unexpected error type: %v", err)
	}
	if exitErr.ExitCode() != 1 {
		t.Errorf("exit code = %d, want 1 (ExitValidation)", exitErr.ExitCode())
	}

	errLower := strings.ToLower(stderr.String())
	if !strings.Contains(errLower, "traverse") &&
		!strings.Contains(errLower, "boundary") &&
		!strings.Contains(errLower, "validation") {
		t.Errorf("stderr missing traversal security error message:\n%s", stderr.String())
	}

	// Ensure no archives created
	entries, _ := os.ReadDir(outDir)
	if len(entries) > 0 {
		t.Errorf("no files should be generated on traversal exploit, found %d", len(entries))
	}
}

func TestIntegration_Build_RejectsInvalidSchema(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/invalid-schema/craftpack.yml")
	outDir := t.TempDir()

	cmd := exec.Command(bin,
		"build",
		"--spec", specPath,
		"--target", "deb",
		"--package-version", "1.0.0",
		"--output-dir", outDir,
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	if err == nil {
		t.Fatalf("expected build to fail for invalid schema, but succeeded")
	}

	exitErr, ok := err.(*exec.ExitError)
	if !ok {
		t.Fatalf("unexpected error type: %v", err)
	}
	if exitErr.ExitCode() != 1 {
		t.Errorf("exit code = %d, want 1 (ExitValidation)", exitErr.ExitCode())
	}

	if !strings.Contains(stderr.String(), "validation") &&
		!strings.Contains(stderr.String(), "maintainer") &&
		!strings.Contains(stderr.String(), "name") {
		t.Errorf("stderr missing validation details:\n%s", stderr.String())
	}
}

func TestIntegration_Build_DryRun(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/valid-minimal/craftpack.yml")
	outDir := t.TempDir()

	cmd := exec.Command(bin,
		"build",
		"--spec", specPath,
		"--target", "deb",
		"--package-version", "1.0.0",
		"--output-dir", outDir,
		"--dry-run",
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	if err != nil {
		t.Fatalf("dry-run build failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	// 1. STDOUT must be 0 bytes (strict stream separation)
	if stdout.Len() != 0 {
		t.Errorf("STDOUT must be clean (0 bytes) during dry-run, got: %s", stdout.String())
	}

	// 2. STDERR must indicate dry-run simulation
	if !strings.Contains(stderr.String(), "Dry-run build simulation completed successfully") {
		t.Errorf("STDERR missing dry-run completion log: %s", stderr.String())
	}

	// 3. No files must be created in output directory
	entries, err := os.ReadDir(outDir)
	if err != nil {
		t.Fatalf("failed reading outDir: %v", err)
	}
	if len(entries) > 0 {
		t.Errorf("expected 0 files in output dir for dry-run, found %d", len(entries))
	}
}

func TestIntegration_Build_JSONOutput(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/valid-minimal/craftpack.yml")
	outDir := t.TempDir()

	cmd := exec.Command(bin,
		"build",
		"--spec", specPath,
		"--target", "deb",
		"--package-version", "1.0.0",
		"--output-dir", outDir,
		"--json",
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	if err != nil {
		t.Fatalf("build --json failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	var res struct {
		Success      bool   `json:"success"`
		PackageFile  string `json:"package_file"`
		PackageName  string `json:"package_name"`
		Filename     string `json:"filename"`
		Version      string `json:"version"`
		Architecture string `json:"architecture"`
		Target       string `json:"target"`
		SHA256       string `json:"sha256"`
		SizeBytes    int64  `json:"size_bytes"`
		DryRun       bool   `json:"dry_run"`
	}

	if err := json.Unmarshal(stdout.Bytes(), &res); err != nil {
		t.Fatalf("failed unmarshaling STDOUT JSON: %v (raw: %s)", err, stdout.String())
	}

	if !res.Success || res.PackageName != "minimal-app" || res.DryRun {
		t.Errorf("unexpected build result: %+v", res)
	}
	if res.SHA256 == "" || res.SizeBytes <= 0 {
		t.Errorf("manifest checksum or size missing: %+v", res)
	}
	if _, err := os.Stat(res.PackageFile); err != nil {
		t.Errorf("package file referenced in JSON does not exist: %v", err)
	}
}

func TestIntegration_Build_DryRun_JSONOutput(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/valid-minimal/craftpack.yml")
	outDir := t.TempDir()

	cmd := exec.Command(bin,
		"build",
		"--spec", specPath,
		"--target", "deb",
		"--package-version", "1.0.0",
		"--output-dir", outDir,
		"--dry-run",
		"--json",
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	if err != nil {
		t.Fatalf("build --dry-run --json failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	var res struct {
		Success      bool   `json:"success"`
		PackageFile  string `json:"package_file"`
		PackageName  string `json:"package_name"`
		Filename     string `json:"filename"`
		DryRun       bool   `json:"dry_run"`
	}

	if err := json.Unmarshal(stdout.Bytes(), &res); err != nil {
		t.Fatalf("failed unmarshaling STDOUT JSON: %v (raw: %s)", err, stdout.String())
	}

	if !res.Success || !res.DryRun || res.PackageFile != "" {
		t.Errorf("unexpected dry-run json result: %+v", res)
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) > 0 {
		t.Errorf("expected 0 files in outDir, found %d", len(entries))
	}
}

func TestIntegration_Build_SymlinkEscape(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()

	appDir := filepath.Join(dir, "app")
	if err := os.MkdirAll(appDir, 0755); err != nil {
		t.Fatalf("failed creating app dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(appDir, "run.sh"), []byte("#!/bin/sh\necho hi\n"), 0755); err != nil {
		t.Fatalf("failed creating entrypoint: %v", err)
	}

	// Create a secret file outside the workspace
	outsideDir := t.TempDir()
	secretFile := filepath.Join(outsideDir, "secret.txt")
	if err := os.WriteFile(secretFile, []byte("super-secret"), 0600); err != nil {
		t.Fatalf("failed creating secret file: %v", err)
	}

	// Symlink from inside app/ pointing outside workspace
	symlinkPath := filepath.Join(appDir, "evil_link")
	if err := os.Symlink(secretFile, symlinkPath); err != nil {
		t.Fatalf("failed creating symlink: %v", err)
	}

	specContent := `name: escape-app
description: App attempting symlink traversal
maintainer: Hacker <hacker@example.com>
homepage: https://example.com/escape
license: MIT
command: escape-app
payload_dir: app
entrypoint: run.sh
targets:
  deb:
    section: utils
`
	specFile := filepath.Join(dir, "craftpack.yml")
	if err := os.WriteFile(specFile, []byte(specContent), 0644); err != nil {
		t.Fatalf("failed writing spec: %v", err)
	}

	outDir := t.TempDir()
	cmd := exec.Command(bin, "build", "--spec", specFile, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	if err == nil {
		t.Fatalf("expected build to fail on symlink traversal, but succeeded")
	}

	exitErr, ok := err.(*exec.ExitError)
	if !ok || exitErr.ExitCode() != 1 {
		t.Errorf("exit code = %v, want 1 (ExitValidation)", err)
	}

	errLower := strings.ToLower(stderr.String())
	if !strings.Contains(errLower, "escape") && !strings.Contains(errLower, "travers") && !strings.Contains(errLower, "symlink") {
		t.Errorf("stderr missing symlink escape message: %s", stderr.String())
	}
}

func TestIntegration_Build_ManPage_ZeroMarkupViolation(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()

	appDir := filepath.Join(dir, "app")
	docsDir := filepath.Join(dir, "docs")
	_ = os.MkdirAll(appDir, 0755)
	_ = os.MkdirAll(docsDir, 0755)
	_ = os.WriteFile(filepath.Join(appDir, "run.sh"), []byte("#!/bin/sh\n"), 0755)

	badManPage := `---
title: Bad Page
section: 1
---
# Name
bad-app - An app with front-matter
`
	_ = os.WriteFile(filepath.Join(docsDir, "bad.1.md"), []byte(badManPage), 0644)

	specContent := `name: bad-manpage-app
description: App violating Zero-Markup policy
maintainer: Doc Writer <doc@example.com>
homepage: https://example.com/badman
license: MIT
command: bad-app
payload_dir: app
entrypoint: run.sh
man_pages:
  - source: docs/bad.1.md
    section: 1
targets:
  deb:
    section: utils
`
	specFile := filepath.Join(dir, "craftpack.yml")
	_ = os.WriteFile(specFile, []byte(specContent), 0644)

	outDir := t.TempDir()
	cmd := exec.Command(bin, "build", "--spec", specFile, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	if err == nil {
		t.Fatalf("expected build to fail on Zero-Markup front-matter violation")
	}

	exitErr, ok := err.(*exec.ExitError)
	if !ok || exitErr.ExitCode() != 1 {
		t.Errorf("exit code = %v, want 1 (ExitValidation)", err)
	}

	if !strings.Contains(stderr.String(), "Zero-Markup") && !strings.Contains(stderr.String(), "front-matter") {
		t.Errorf("stderr missing Zero-Markup violation details: %s", stderr.String())
	}
}

func TestIntegration_Build_MissingPrerequisites(t *testing.T) {
	bin := getCraftpackBinary(t)

	cases := []struct {
		name        string
		setup       func(dir string) string
		errContains string
	}{
		{
			name: "nonexistent spec file",
			setup: func(dir string) string {
				return filepath.Join(dir, "nonexistent.yml")
			},
			errContains: "not found",
		},
		{
			name: "missing entrypoint in payload",
			setup: func(dir string) string {
				appDir := filepath.Join(dir, "app")
				_ = os.MkdirAll(appDir, 0755)
				spec := `name: missing-entrypoint
description: Testing missing entrypoint
maintainer: Tester <test@example.com>
homepage: https://example.com/test
license: MIT
command: testcmd
payload_dir: app
entrypoint: missing_bin
targets:
  deb:
    section: utils
`
				specFile := filepath.Join(dir, "craftpack.yml")
				_ = os.WriteFile(specFile, []byte(spec), 0644)
				return specFile
			},
			errContains: "entrypoint",
		},
		{
			name: "missing default_config source",
			setup: func(dir string) string {
				appDir := filepath.Join(dir, "app")
				_ = os.MkdirAll(appDir, 0755)
				_ = os.WriteFile(filepath.Join(appDir, "run.sh"), []byte("#!/bin/sh\n"), 0755)
				spec := `name: missing-config
description: Testing missing config
maintainer: Tester <test@example.com>
homepage: https://example.com/test
license: MIT
command: testcmd
payload_dir: app
entrypoint: run.sh
default_config:
  missing.conf: testcmd.conf
targets:
  deb:
    section: utils
`
				specFile := filepath.Join(dir, "craftpack.yml")
				_ = os.WriteFile(specFile, []byte(spec), 0644)
				return specFile
			},
			errContains: "default_config",
		},
		{
			name: "hook script attempting path traversal",
			setup: func(dir string) string {
				appDir := filepath.Join(dir, "app")
				_ = os.MkdirAll(appDir, 0755)
				_ = os.WriteFile(filepath.Join(appDir, "run.sh"), []byte("#!/bin/sh\n"), 0755)
				spec := `name: traversal-hook
description: Testing traversal hook
maintainer: Tester <test@example.com>
homepage: https://example.com/test
license: MIT
command: testcmd
payload_dir: app
entrypoint: run.sh
preinstall: ../../evil.sh
targets:
  deb:
    section: utils
`
				specFile := filepath.Join(dir, "craftpack.yml")
				_ = os.WriteFile(specFile, []byte(spec), 0644)
				return specFile
			},
			errContains: "traverse",
		},
		{
			name: "missing man page source",
			setup: func(dir string) string {
				appDir := filepath.Join(dir, "app")
				_ = os.MkdirAll(appDir, 0755)
				_ = os.WriteFile(filepath.Join(appDir, "run.sh"), []byte("#!/bin/sh\n"), 0755)
				spec := `name: missing-man
description: Testing missing man page
maintainer: Tester <test@example.com>
homepage: https://example.com/test
license: MIT
command: testcmd
payload_dir: app
entrypoint: run.sh
man_pages:
  - source: docs/nonexistent.1.md
    section: 1
targets:
  deb:
    section: utils
`
				specFile := filepath.Join(dir, "craftpack.yml")
				_ = os.WriteFile(specFile, []byte(spec), 0644)
				return specFile
			},
			errContains: "does not exist or is not readable",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			specFile := tc.setup(dir)
			outDir := t.TempDir()

			cmd := exec.Command(bin, "build", "--spec", specFile, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir)
			var stdout, stderr bytes.Buffer
			cmd.Stdout = &stdout
			cmd.Stderr = &stderr

			err := cmd.Run()
			if err == nil {
				t.Fatalf("expected build to fail for %s", tc.name)
			}
			exitErr, ok := err.(*exec.ExitError)
			if !ok || exitErr.ExitCode() != 1 {
				t.Errorf("exit code = %v, want 1 (ExitValidation)", err)
			}
			if !strings.Contains(strings.ToLower(stderr.String()), strings.ToLower(tc.errContains)) {
				t.Errorf("stderr missing %q: %s", tc.errContains, stderr.String())
			}
		})
	}
}

func TestIntegration_Build_ArchitectureMatrix(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/valid-minimal/craftpack.yml")

	archCases := []struct {
		cliArch  string
		wantDeb  string
		wantArch string
	}{
		{cliArch: "arm64", wantDeb: "minimal-app_1.0.0_arm64.deb", wantArch: "arm64"},
		{cliArch: "all", wantDeb: "minimal-app_1.0.0_all.deb", wantArch: "all"},
		{cliArch: "aarch64", wantDeb: "minimal-app_1.0.0_arm64.deb", wantArch: "arm64"},
		{cliArch: "x86_64", wantDeb: "minimal-app_1.0.0_amd64.deb", wantArch: "amd64"},
	}

	for _, tc := range archCases {
		t.Run(tc.cliArch, func(t *testing.T) {
			outDir := t.TempDir()
			cmd := exec.Command(bin,
				"build",
				"--spec", specPath,
				"--target", "deb",
				"--package-version", "1.0.0",
				"--arch", tc.cliArch,
				"--output-dir", outDir,
			)

			var stdout, stderr bytes.Buffer
			cmd.Stdout = &stdout
			cmd.Stderr = &stderr

			if err := cmd.Run(); err != nil {
				t.Fatalf("build failed for arch %s: %v\nSTDERR:\n%s", tc.cliArch, err, stderr.String())
			}

			debPath := filepath.Join(outDir, tc.wantDeb)
			if _, err := os.Stat(debPath); err != nil {
				t.Fatalf("expected package %s was not generated: %v", tc.wantDeb, err)
			}

			unpacked := unpackDeb(t, debPath)
			ctrlData := string(unpacked.ControlFiles["control"])
			expectedLine := fmt.Sprintf("Architecture: %s", tc.wantArch)
			if !strings.Contains(ctrlData, expectedLine) {
				t.Errorf("control missing %q:\n%s", expectedLine, ctrlData)
			}
		})
	}
}

func TestIntegration_Build_ZeroByteFileAndDeepNesting(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()

	payloadDir := filepath.Join(dir, "payload")
	nestedDir := filepath.Join(payloadDir, "sub1", "sub2", "sub3")
	if err := os.MkdirAll(nestedDir, 0755); err != nil {
		t.Fatalf("failed creating nested dir: %v", err)
	}

	// 1. Regular entrypoint
	_ = os.WriteFile(filepath.Join(payloadDir, "app.sh"), []byte("#!/bin/sh\necho running\n"), 0755)

	// 2. Empty 0-byte file
	emptyFile := filepath.Join(payloadDir, "empty.txt")
	if err := os.WriteFile(emptyFile, []byte{}, 0644); err != nil {
		t.Fatalf("failed writing empty file: %v", err)
	}

	// 3. Deeply nested file
	nestedFile := filepath.Join(nestedDir, "deep.conf")
	if err := os.WriteFile(nestedFile, []byte("nested_key = true\n"), 0644); err != nil {
		t.Fatalf("failed writing nested file: %v", err)
	}

	spec := `name: edge-app
description: Application with empty files and deep directory structures
maintainer: Developer <dev@example.com>
homepage: https://example.com/edge
license: MIT
command: edge-app
payload_dir: payload
entrypoint: app.sh
targets:
  deb:
    section: utils
`
	specPath := filepath.Join(dir, "craftpack.yml")
	_ = os.WriteFile(specPath, []byte(spec), 0644)

	outDir := t.TempDir()
	cmd := exec.Command(bin, "build", "--spec", specPath, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		t.Fatalf("build failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	debFile := filepath.Join(outDir, "edge-app_1.0.0_amd64.deb")
	entries, _ := os.ReadDir(outDir)
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".deb") {
			debFile = filepath.Join(outDir, e.Name())
			break
		}
	}

	unpacked := unpackDeb(t, debFile)

	// Verify empty.txt exists and is 0 bytes
	emptyData, ok := unpacked.DataFiles["/usr/lib/edge-app/empty.txt"]
	if !ok {
		t.Fatalf("/usr/lib/edge-app/empty.txt not found in data.tar.gz")
	}
	if len(emptyData) != 0 {
		t.Errorf("empty.txt length = %d, want 0", len(emptyData))
	}

	// Verify empty file MD5 in DEBIAN/md5sums matches standard empty hash d41d8cd98f00b204e9800998ecf8427e
	md5Content := string(unpacked.ControlFiles["md5sums"])
	if !strings.Contains(md5Content, "d41d8cd98f00b204e9800998ecf8427e  usr/lib/edge-app/empty.txt") {
		t.Errorf("md5sums missing entry for 0-byte file:\n%s", md5Content)
	}

	// Verify deeply nested file exists
	nestedData, ok := unpacked.DataFiles["/usr/lib/edge-app/sub1/sub2/sub3/deep.conf"]
	if !ok {
		t.Fatalf("nested file not found in data.tar.gz")
	}
	if string(nestedData) != "nested_key = true\n" {
		t.Errorf("unexpected nested file content: %s", string(nestedData))
	}

	// Verify primary entrypoint is placed directly at /usr/bin/edge-app (0755)
	binData, ok := unpacked.DataFiles["/usr/bin/edge-app"]
	if !ok {
		t.Fatalf("missing direct entrypoint at /usr/bin/edge-app")
	}
	if string(binData) != "#!/bin/sh\necho running\n" {
		t.Errorf("unexpected binary content at /usr/bin/edge-app: %s", string(binData))
	}
	binHdr := unpacked.DataHeaders["/usr/bin/edge-app"]
	if binHdr.Mode != 0755 {
		t.Errorf("binary mode = %o, want 0755", binHdr.Mode)
	}

	// Verify entrypoint is NOT duplicated under /usr/lib/edge-app/app.sh
	if _, ok := unpacked.DataFiles["/usr/lib/edge-app/app.sh"]; ok {
		t.Errorf("entrypoint app.sh unexpectedly found under /usr/lib/edge-app/ in direct mode")
	}
}

func TestIntegration_Build_MultipleConffiles(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()

	payloadDir := filepath.Join(dir, "bin")
	configDir := filepath.Join(dir, "configs")
	_ = os.MkdirAll(payloadDir, 0755)
	_ = os.MkdirAll(configDir, 0755)

	_ = os.WriteFile(filepath.Join(payloadDir, "daemon"), []byte("#!/bin/sh\n"), 0755)
	_ = os.WriteFile(filepath.Join(configDir, "main.conf"), []byte("main = 1\n"), 0644)
	_ = os.WriteFile(filepath.Join(configDir, "extra.conf"), []byte("extra = 2\n"), 0644)

	spec := `name: multiconf-app
description: App with multiple config files
maintainer: Admin <admin@example.com>
homepage: https://example.com/multiconf
license: BSD-3-Clause
command: daemon
payload_dir: bin
entrypoint: daemon
default_config:
  configs/main.conf: daemon.conf
  configs/extra.conf: extra.conf
targets:
  deb:
    section: utils
`
	specPath := filepath.Join(dir, "craftpack.yml")
	_ = os.WriteFile(specPath, []byte(spec), 0644)

	outDir := t.TempDir()
	cmd := exec.Command(bin, "build", "--spec", specPath, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		t.Fatalf("build failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	entries, _ := os.ReadDir(outDir)
	var debFile string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".deb") {
			debFile = filepath.Join(outDir, e.Name())
			break
		}
	}

	unpacked := unpackDeb(t, debFile)

	conffilesData, ok := unpacked.ControlFiles["conffiles"]
	if !ok {
		t.Fatalf("DEBIAN/conffiles missing")
	}
	conffilesStr := string(conffilesData)

	// Must have leading slashes
	if !strings.Contains(conffilesStr, "/etc/multiconf-app/daemon.conf") {
		t.Errorf("conffiles missing /etc/multiconf-app/daemon.conf:\n%s", conffilesStr)
	}
	if !strings.Contains(conffilesStr, "/etc/multiconf-app/extra.conf") {
		t.Errorf("conffiles missing /etc/multiconf-app/extra.conf:\n%s", conffilesStr)
	}

	// Must be present in data.tar.gz
	if _, ok := unpacked.DataFiles["/etc/multiconf-app/daemon.conf"]; !ok {
		t.Errorf("daemon.conf missing in data.tar.gz")
	}
	if _, ok := unpacked.DataFiles["/etc/multiconf-app/extra.conf"]; !ok {
		t.Errorf("extra.conf missing in data.tar.gz")
	}
}

func TestIntegration_Build_NestedOutputDirAutoCreation(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/valid-minimal/craftpack.yml")

	dir := t.TempDir()
	deepOutDir := filepath.Join(dir, "dist", "releases", "2026", "linux")

	cmd := exec.Command(bin,
		"build",
		"--spec", specPath,
		"--target", "deb",
		"--package-version", "1.0.0",
		"--output-dir", deepOutDir,
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		t.Fatalf("build failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	// Verify deepOutDir created and contains .deb and checksums.sha256
	manifestPath := filepath.Join(deepOutDir, "checksums.sha256")
	if _, err := os.Stat(manifestPath); err != nil {
		t.Errorf("checksums.sha256 not found in deep outDir: %v", err)
	}
}

func TestIntegration_Build_ConcurrentExecutions(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/valid-minimal/craftpack.yml")

	concurrency := 4
	var wg sync.WaitGroup
	errCh := make(chan error, concurrency)

	for i := 0; i < concurrency; i++ {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()
			outDir := t.TempDir()
			cmd := exec.Command(bin,
				"build",
				"--spec", specPath,
				"--target", "deb",
				"--package-version", fmt.Sprintf("1.0.%d", idx),
				"--output-dir", outDir,
			)
			var stdout, stderr bytes.Buffer
			cmd.Stdout = &stdout
			cmd.Stderr = &stderr

			if err := cmd.Run(); err != nil {
				errCh <- fmt.Errorf("worker %d failed: %w (stderr: %s)", idx, err, stderr.String())
				return
			}

			manifest := filepath.Join(outDir, "checksums.sha256")
			if _, err := os.Stat(manifest); err != nil {
				errCh <- fmt.Errorf("worker %d manifest missing: %w", idx, err)
			}
		}(i)
	}

	wg.Wait()
	close(errCh)

	for err := range errCh {
		t.Errorf("concurrent execution error: %v", err)
	}
}

func TestIntegration_Build_ReproducibleBuildsWithSourceDateEpoch(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/valid-minimal/craftpack.yml")

	outDir1 := t.TempDir()
	outDir2 := t.TempDir()

	runBuild := func(outDir string) {
		cmd := exec.Command(bin,
			"build",
			"--spec", specPath,
			"--target", "deb",
			"--package-version", "1.0.0",
			"--output-dir", outDir,
		)
		cmd.Env = append(os.Environ(), "SOURCE_DATE_EPOCH=1700000000")
		var stdout, stderr bytes.Buffer
		cmd.Stdout = &stdout
		cmd.Stderr = &stderr

		if err := cmd.Run(); err != nil {
			t.Fatalf("build failed: %v\nSTDERR:\n%s", err, stderr.String())
		}
	}

	runBuild(outDir1)
	runBuild(outDir2)

	debName := "minimal-app_1.0.0_amd64.deb"
	debPath1 := filepath.Join(outDir1, debName)
	debPath2 := filepath.Join(outDir2, debName)

	bytes1, err := os.ReadFile(debPath1)
	if err != nil {
		t.Fatalf("failed reading deb1: %v", err)
	}
	bytes2, err := os.ReadFile(debPath2)
	if err != nil {
		t.Fatalf("failed reading deb2: %v", err)
	}

	if !bytes.Equal(bytes1, bytes2) {
		hash1 := sha256.Sum256(bytes1)
		hash2 := sha256.Sum256(bytes2)
		t.Errorf("reproducible build assertion failed: packages differ in bytes!\nHash1: %x\nHash2: %x", hash1, hash2)
	}

	manifest1, _ := os.ReadFile(filepath.Join(outDir1, "checksums.sha256"))
	manifest2, _ := os.ReadFile(filepath.Join(outDir2, "checksums.sha256"))
	if !bytes.Equal(manifest1, manifest2) {
		t.Errorf("manifest files differ:\nManifest 1:\n%s\nManifest 2:\n%s", string(manifest1), string(manifest2))
	}
}

func TestIntegration_Build_DestructiveHookRejection(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()

	payloadDir := filepath.Join(dir, "bin")
	_ = os.MkdirAll(payloadDir, 0755)
	_ = os.WriteFile(filepath.Join(payloadDir, "app"), []byte("#!/bin/sh\n"), 0755)

	spec := `name: destructive-app
description: Application containing forbidden destructive hook
maintainer: Tester <test@example.com>
homepage: https://example.com/destruct
license: MIT
command: app
payload_dir: bin
entrypoint: app
postinstall: "echo starting && rm -rf / && echo done"
targets:
  deb:
    section: utils
`
	specPath := filepath.Join(dir, "craftpack.yml")
	_ = os.WriteFile(specPath, []byte(spec), 0644)

	outDir := t.TempDir()
	cmd := exec.Command(bin, "build", "--spec", specPath, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	if err == nil {
		t.Fatalf("expected build to fail for destructive hook, but succeeded")
	}

	exitErr, ok := err.(*exec.ExitError)
	if !ok || exitErr.ExitCode() != 1 {
		t.Errorf("exit code = %v, want 1 (ExitValidation)", err)
	}

	if !strings.Contains(stderr.String(), "destructive command") {
		t.Errorf("stderr missing destructive command details: %s", stderr.String())
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) > 0 {
		t.Errorf("expected 0 files in outDir, found %d", len(entries))
	}
}

func TestIntegration_Build_StrictMode(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()

	payloadDir := filepath.Join(dir, "bin")
	_ = os.MkdirAll(payloadDir, 0755)
	_ = os.WriteFile(filepath.Join(payloadDir, "app"), []byte("#!/bin/sh\n"), 0755)

	spec := `name: strict-test-app
description: Application with unknown root key for strict testing
maintainer: Tester <test@example.com>
homepage: https://example.com/strict
license: MIT
command: app
payload_dir: bin
entrypoint: app
unknown_root_property: "experimental_value"
targets:
  deb:
    section: utils
`
	specPath := filepath.Join(dir, "craftpack.yml")
	_ = os.WriteFile(specPath, []byte(spec), 0644)

	// 1. Without --strict: build succeeds, warning emitted
	t.Run("without strict succeeds", func(t *testing.T) {
		outDir := t.TempDir()
		cmd := exec.Command(bin, "build", "--spec", specPath, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir)
		var stdout, stderr bytes.Buffer
		cmd.Stdout = &stdout
		cmd.Stderr = &stderr

		if err := cmd.Run(); err != nil {
			t.Fatalf("build without --strict failed: %v\nSTDERR:\n%s", err, stderr.String())
		}
		if !strings.Contains(stderr.String(), "[WARN ]") {
			t.Errorf("expected warning in stderr: %s", stderr.String())
		}
		entries, _ := os.ReadDir(outDir)
		if len(entries) == 0 {
			t.Errorf("expected package generated in outDir")
		}
	})

	// 2. With --strict: build fails with exit code 1
	t.Run("with strict fails", func(t *testing.T) {
		outDir := t.TempDir()
		cmd := exec.Command(bin, "build", "--spec", specPath, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir, "--strict")
		var stdout, stderr bytes.Buffer
		cmd.Stdout = &stdout
		cmd.Stderr = &stderr

		err := cmd.Run()
		if err == nil {
			t.Fatalf("expected build with --strict to fail")
		}
		exitErr, ok := err.(*exec.ExitError)
		if !ok || exitErr.ExitCode() != 1 {
			t.Errorf("exit code = %v, want 1 (ExitValidation)", err)
		}
		if !strings.Contains(stderr.String(), "unknown configuration key") {
			t.Errorf("stderr missing unknown configuration key message: %s", stderr.String())
		}
		entries, _ := os.ReadDir(outDir)
		if len(entries) > 0 {
			t.Errorf("expected 0 files in outDir for strict failure, found %d", len(entries))
		}
	})
}

func TestIntegration_Build_DefaultSpecAndOutputDirInference(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()

	payloadDir := filepath.Join(dir, "bin")
	_ = os.MkdirAll(payloadDir, 0755)
	_ = os.WriteFile(filepath.Join(payloadDir, "app"), []byte("#!/bin/sh\necho running\n"), 0755)

	spec := `name: default-inferred-app
description: Testing default spec and output dir inference
maintainer: Tester <test@example.com>
homepage: https://example.com/inferred
license: MIT
command: app
payload_dir: bin
entrypoint: app
targets:
  deb:
    section: utils
`
	specPath := filepath.Join(dir, "craftpack.yml")
	_ = os.WriteFile(specPath, []byte(spec), 0644)

	// Execute without --spec and without --output-dir in working directory dir
	cmd := exec.Command(bin, "build", "--target", "deb", "--package-version", "1.0.0")
	cmd.Dir = dir
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		t.Fatalf("build with default inference failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	// Verify ./dist directory was created inside dir
	distDir := filepath.Join(dir, "dist")
	manifestPath := filepath.Join(distDir, "checksums.sha256")
	if _, err := os.Stat(manifestPath); err != nil {
		t.Errorf("checksums.sha256 not found in inferred ./dist directory: %v", err)
	}

	entries, _ := os.ReadDir(distDir)
	foundDeb := false
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".deb") {
			foundDeb = true
			break
		}
	}
	if !foundDeb {
		t.Errorf("expected .deb package in inferred ./dist directory")
	}
}

func TestIntegration_Build_SemVerPrereleaseAndBuildMetadata(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/valid-minimal/craftpack.yml")
	outDir := t.TempDir()

	version := "1.2.3-alpha.1+build.42"
	cmd := exec.Command(bin,
		"build",
		"--spec", specPath,
		"--target", "deb",
		"--package-version", version,
		"--output-dir", outDir,
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		t.Fatalf("build failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	debPath := filepath.Join(outDir, fmt.Sprintf("minimal-app_%s_amd64.deb", version))
	if _, err := os.Stat(debPath); err != nil {
		t.Fatalf("expected package %s was not found: %v", debPath, err)
	}

	unpacked := unpackDeb(t, debPath)
	ctrlStr := string(unpacked.ControlFiles["control"])
	expectedVersionLine := fmt.Sprintf("Version: %s", version)
	if !strings.Contains(ctrlStr, expectedVersionLine) {
		t.Errorf("control missing %q:\n%s", expectedVersionLine, ctrlStr)
	}
}

func TestIntegration_Build_CraftpackYamlExtension(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()

	payloadDir := filepath.Join(dir, "bin")
	_ = os.MkdirAll(payloadDir, 0755)
	_ = os.WriteFile(filepath.Join(payloadDir, "app"), []byte("#!/bin/sh\n"), 0755)

	spec := `name: yaml-extension-app
description: Testing craftpack.yaml with .yaml extension
maintainer: Tester <test@example.com>
homepage: https://example.com/yaml
license: MIT
command: app
payload_dir: bin
entrypoint: app
targets:
  deb:
    section: utils
`
	specPath := filepath.Join(dir, "craftpack.yaml")
	_ = os.WriteFile(specPath, []byte(spec), 0644)

	outDir := t.TempDir()
	cmd := exec.Command(bin, "build", "--spec", specPath, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		t.Fatalf("build with craftpack.yaml failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	entries, _ := os.ReadDir(outDir)
	if len(entries) < 2 {
		t.Errorf("expected .deb and manifest in outDir, found %d entries", len(entries))
	}
}

func TestIntegration_Build_WithManualLicensingHeader(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, err := filepath.Abs("../..")
	if err != nil {
		t.Fatalf("failed to resolve root dir: %v", err)
	}

	manualPath := filepath.Join(rootDir, "docs", "manuals", "craftpack.1.md")
	manualData, err := os.ReadFile(manualPath)
	if err != nil {
		t.Fatalf("failed reading docs/manuals/craftpack.1.md: %v", err)
	}

	// Verify docs/manuals/craftpack.1.md has the licensing header
	if !strings.HasPrefix(strings.TrimSpace(string(manualData)), "<!--") {
		t.Fatal("docs/manuals/craftpack.1.md must start with HTML comment licensing header")
	}

	tmpDir := t.TempDir()

	// 1. Create docs/manuals/craftpack.1.md inside tmpDir
	docsDir := filepath.Join(tmpDir, "docs", "manuals")
	if err := os.MkdirAll(docsDir, 0755); err != nil {
		t.Fatalf("failed creating docs/manuals dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(docsDir, "craftpack.1.md"), manualData, 0644); err != nil {
		t.Fatalf("failed writing craftpack.1.md copy: %v", err)
	}

	// 2. Create payload directory with a dummy binary
	payloadDir := filepath.Join(tmpDir, "dist", "payload", "bin")
	if err := os.MkdirAll(payloadDir, 0755); err != nil {
		t.Fatalf("failed creating payload dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(payloadDir, "craftpack"), []byte("#!/bin/sh\necho craftpack\n"), 0755); err != nil {
		t.Fatalf("failed writing payload binary: %v", err)
	}

	// 3. Create config directory
	cfgDir := filepath.Join(tmpDir, "config")
	if err := os.MkdirAll(cfgDir, 0755); err != nil {
		t.Fatalf("failed creating config dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(cfgDir, "craftpack.default.yml"), []byte("# config\n"), 0644); err != nil {
		t.Fatalf("failed writing config template: %v", err)
	}

	// 4. Create craftpack.yml specification
	specContent := `name: craftpack
description: Standardized Linux packaging factory
maintainer: Developer <dev@example.com>
homepage: https://github.com/dev/craftpack
license: MIT
command: craftpack
payload_dir: dist/payload
entrypoint: bin/craftpack
man_pages:
  - source: docs/manuals/craftpack.1.md
    section: 1
    title: CRAFTPACK
    header: User Commands Manual
    footer: Craftpack Packaging Utility
default_config:
  config/craftpack.default.yml: craftpack.yml
targets:
  deb:
    section: utils
    priority: optional
    dependencies:
      - libc6 (>= 2.31)
`
	specFile := filepath.Join(tmpDir, "craftpack.yml")
	if err := os.WriteFile(specFile, []byte(specContent), 0644); err != nil {
		t.Fatalf("failed writing craftpack.yml: %v", err)
	}

	outDir := filepath.Join(tmpDir, "dist")
	cmd := exec.Command(bin,
		"build",
		"--spec", specFile,
		"--target", "deb",
		"--package-version", "1.0.0",
		"--output-dir", outDir,
		"-v",
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		t.Fatalf("craftpack build with manual.md failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	// Find the created .deb package
	entries, err := os.ReadDir(outDir)
	if err != nil {
		t.Fatalf("failed reading outDir: %v", err)
	}

	var debPath string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".deb") {
			debPath = filepath.Join(outDir, e.Name())
			break
		}
	}
	if debPath == "" {
		t.Fatalf("no .deb package found in %s", outDir)
	}

	unpacked := unpackDeb(t, debPath)

	// Verify man page exists in data.tar.gz
	manGzData, ok := unpacked.DataFiles["/usr/share/man/man1/craftpack.1.gz"]
	if !ok {
		t.Fatalf("/usr/share/man/man1/craftpack.1.gz missing in data.tar.gz")
	}

	gzReader, err := gzip.NewReader(bytes.NewReader(manGzData))
	if err != nil {
		t.Fatalf("failed reading gzipped man page: %v", err)
	}
	defer gzReader.Close()

	roffData, err := io.ReadAll(gzReader)
	if err != nil {
		t.Fatalf("failed decompressing man page: %v", err)
	}

	roffStr := string(roffData)
	if !strings.Contains(roffStr, ".TH CRAFTPACK 1") {
		t.Errorf("man page missing .TH CRAFTPACK 1: %s", roffStr[:min(len(roffStr), 200)])
	}
	if !strings.Contains(roffStr, ".SH NAME") {
		t.Errorf("man page missing .SH NAME section")
	}
	if !strings.Contains(roffStr, ".SH SYNOPSIS") {
		t.Errorf("man page missing .SH SYNOPSIS section")
	}
	if !strings.Contains(roffStr, ".SH DESCRIPTION") {
		t.Errorf("man page missing .SH DESCRIPTION section")
	}
	if !strings.Contains(roffStr, ".SH EXAMPLES") {
		t.Errorf("man page missing .SH EXAMPLES section")
	}
}

func TestIntegration_Build_DirectBinary_ExplicitWrapperFalse(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()
	outDir := filepath.Join(dir, "dist")

	binDir := filepath.Join(dir, "bin")
	if err := os.MkdirAll(binDir, 0755); err != nil {
		t.Fatalf("failed creating binDir: %v", err)
	}
	binFile := filepath.Join(binDir, "direct-tool")
	binContent := []byte("#!/bin/sh\necho direct-tool-exec\n")
	if err := os.WriteFile(binFile, binContent, 0755); err != nil {
		t.Fatalf("failed writing binary: %v", err)
	}

	spec := `name: direct-tool
description: Direct binary placement test application
maintainer: Tester <tester@example.com>
homepage: https://example.com/direct
license: MIT
command: direct-tool
payload_dir: bin
entrypoint: direct-tool
targets:
  deb:
    section: utils
    priority: optional
    wrapper: false
`
	specFile := filepath.Join(dir, "craftpack.yml")
	if err := os.WriteFile(specFile, []byte(spec), 0644); err != nil {
		t.Fatalf("failed writing spec: %v", err)
	}

	cmd := exec.Command(bin,
		"build",
		"--spec", specFile,
		"--target", "deb",
		"--package-version", "1.0.0",
		"--output-dir", outDir,
		"-v",
	)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		t.Fatalf("build failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	// Locate .deb
	entries, _ := os.ReadDir(outDir)
	var debPath string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".deb") {
			debPath = filepath.Join(outDir, e.Name())
			break
		}
	}
	if debPath == "" {
		t.Fatalf("no .deb package produced")
	}

	unpacked := unpackDeb(t, debPath)

	// Assert binary placed directly at /usr/bin/direct-tool
	data, ok := unpacked.DataFiles["/usr/bin/direct-tool"]
	if !ok {
		t.Fatalf("missing /usr/bin/direct-tool in package")
	}
	if !bytes.Equal(data, binContent) {
		t.Errorf("binary content mismatch: %q vs %q", string(data), string(binContent))
	}
	if strings.Contains(string(data), "REAL_PAYLOAD") {
		t.Errorf("expected direct binary, got proxy launcher script")
	}
	hdr := unpacked.DataHeaders["/usr/bin/direct-tool"]
	if hdr.Mode != 0755 {
		t.Errorf("permissions = %o, want 0755", hdr.Mode)
	}

	// Assert /usr/lib is completely omitted for single-binary package
	for path := range unpacked.DataFiles {
		if strings.HasPrefix(path, "/usr/lib") {
			t.Errorf("unexpected entry under /usr/lib in single binary mode: %s", path)
		}
	}
}

func TestIntegration_Build_DirectBinary_WithAuxiliaryAssets(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()
	outDir := filepath.Join(dir, "dist")

	payloadDir := filepath.Join(dir, "dist-payload")
	binSubdir := filepath.Join(payloadDir, "bin")
	assetsSubdir := filepath.Join(payloadDir, "assets")
	libSubdir := filepath.Join(payloadDir, "lib")
	for _, d := range []string{binSubdir, assetsSubdir, libSubdir} {
		if err := os.MkdirAll(d, 0755); err != nil {
			t.Fatalf("failed creating dir %s: %v", d, err)
		}
	}

	binContent := []byte("#!/bin/sh\necho multi-payload-bin\n")
	if err := os.WriteFile(filepath.Join(binSubdir, "runner"), binContent, 0755); err != nil {
		t.Fatalf("failed writing binary: %v", err)
	}
	assetContent := []byte("asset icon data\n")
	if err := os.WriteFile(filepath.Join(assetsSubdir, "icon.png"), assetContent, 0644); err != nil {
		t.Fatalf("failed writing asset: %v", err)
	}
	libContent := []byte("shared library data\n")
	if err := os.WriteFile(filepath.Join(libSubdir, "helper.so"), libContent, 0644); err != nil {
		t.Fatalf("failed writing lib: %v", err)
	}

	spec := `name: multiapp
description: Multi-file application with direct binary placement
maintainer: Tester <tester@example.com>
homepage: https://example.com/multi
license: MIT
command: multiapp
payload_dir: dist-payload
entrypoint: bin/runner
targets:
  deb:
    section: utils
    priority: optional
    wrapper: false
`
	specFile := filepath.Join(dir, "craftpack.yml")
	if err := os.WriteFile(specFile, []byte(spec), 0644); err != nil {
		t.Fatalf("failed writing spec: %v", err)
	}

	cmd := exec.Command(bin,
		"build",
		"--spec", specFile,
		"--target", "deb",
		"--package-version", "2.0.0",
		"--output-dir", outDir,
		"-v",
	)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		t.Fatalf("build failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	entries, _ := os.ReadDir(outDir)
	var debPath string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".deb") {
			debPath = filepath.Join(outDir, e.Name())
			break
		}
	}
	if debPath == "" {
		t.Fatalf("no .deb package produced")
	}

	unpacked := unpackDeb(t, debPath)

	// 1. Entrypoint directly in /usr/bin/multiapp
	data, ok := unpacked.DataFiles["/usr/bin/multiapp"]
	if !ok {
		t.Fatalf("missing /usr/bin/multiapp")
	}
	if !bytes.Equal(data, binContent) {
		t.Errorf("binary content mismatch at /usr/bin/multiapp")
	}
	if strings.Contains(string(data), "REAL_PAYLOAD") {
		t.Errorf("expected direct binary, got proxy launcher script")
	}

	// 2. Entrypoint NOT in /usr/lib/multiapp/bin/runner
	if _, ok := unpacked.DataFiles["/usr/lib/multiapp/bin/runner"]; ok {
		t.Errorf("unexpected entrypoint duplicate in /usr/lib/multiapp/bin/runner")
	}

	// 3. Auxiliary assets preserved in /usr/lib/multiapp/
	assetData, ok := unpacked.DataFiles["/usr/lib/multiapp/assets/icon.png"]
	if !ok {
		t.Fatalf("missing /usr/lib/multiapp/assets/icon.png")
	}
	if !bytes.Equal(assetData, assetContent) {
		t.Errorf("asset content mismatch")
	}

	libData, ok := unpacked.DataFiles["/usr/lib/multiapp/lib/helper.so"]
	if !ok {
		t.Fatalf("missing /usr/lib/multiapp/lib/helper.so")
	}
	if !bytes.Equal(libData, libContent) {
		t.Errorf("lib content mismatch")
	}
}

func TestIntegration_Build_LauncherExecution_ArgumentAndStreamPassthrough(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()
	outDir := filepath.Join(dir, "dist")

	payloadDir := filepath.Join(dir, "payload", "bin")
	if err := os.MkdirAll(payloadDir, 0755); err != nil {
		t.Fatalf("failed creating payload dir: %v", err)
	}

	runnerScript := `#!/bin/sh
for arg in "$@"; do
    echo "ARG:$arg"
done
read -r line
echo "STDIN:$line"
echo "STDERR_TEST_MSG" >&2
exit 42
`
	if err := os.WriteFile(filepath.Join(payloadDir, "runner.sh"), []byte(runnerScript), 0755); err != nil {
		t.Fatalf("failed writing runner script: %v", err)
	}

	spec := `name: streamapp
description: Application testing launcher argument and stream passthrough
maintainer: Tester <tester@example.com>
homepage: https://example.com/stream
license: MIT
command: streamapp
payload_dir: payload
entrypoint: bin/runner.sh
targets:
  deb:
    section: utils
    priority: optional
    wrapper: true
`
	specPath := filepath.Join(dir, "craftpack.yml")
	if err := os.WriteFile(specPath, []byte(spec), 0644); err != nil {
		t.Fatalf("failed writing spec: %v", err)
	}

	cmd := exec.Command(bin, "build", "--spec", specPath, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("build failed: %v\nOutput:\n%s", err, string(out))
	}

	entries, _ := os.ReadDir(outDir)
	var debFile string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".deb") {
			debFile = filepath.Join(outDir, e.Name())
			break
		}
	}
	unpacked := unpackDeb(t, debFile)

	// Extract launcher and private payload into a mock execution environment
	mockEnv := t.TempDir()
	mockPayloadPath := filepath.Join(mockEnv, "runner.sh")
	if err := os.WriteFile(mockPayloadPath, unpacked.DataFiles["/usr/lib/streamapp/bin/runner.sh"], 0755); err != nil {
		t.Fatalf("failed writing mock payload: %v", err)
	}

	// Adapt launcher to point to mock payload for testing execution semantics
	launcherTemplate := string(unpacked.DataFiles["/usr/bin/streamapp"])
	adaptedLauncher := strings.Replace(launcherTemplate, `REAL_PAYLOAD="/usr/lib/streamapp/bin/runner.sh"`, fmt.Sprintf(`REAL_PAYLOAD="%s"`, mockPayloadPath), 1)
	mockLauncherPath := filepath.Join(mockEnv, "streamapp")
	if err := os.WriteFile(mockLauncherPath, []byte(adaptedLauncher), 0755); err != nil {
		t.Fatalf("failed writing adapted launcher: %v", err)
	}

	// Execute adapted launcher with complex arguments and piped STDIN
	execCmd := exec.Command(mockLauncherPath, "simple", "arg with spaces", `arg"with'quotes`, "--flag=value", "; touch /tmp/evil_injection")
	execCmd.Stdin = strings.NewReader("hello via stdin\n")
	var execStdout, execStderr bytes.Buffer
	execCmd.Stdout = &execStdout
	execCmd.Stderr = &execStderr

	err := execCmd.Run()
	if err == nil {
		t.Fatalf("expected exit code 42, got nil error")
	}
	exitErr, ok := err.(*exec.ExitError)
	if !ok || exitErr.ExitCode() != 42 {
		t.Fatalf("expected exit code 42, got: %v", err)
	}

	outStr := execStdout.String()
	errStr := execStderr.String()

	// Verify exact literal argument forwarding without shell injection or word-splitting
	expectedArgs := []string{
		"ARG:simple",
		"ARG:arg with spaces",
		"ARG:arg\"with'quotes",
		"ARG:--flag=value",
		"ARG:; touch /tmp/evil_injection",
	}
	for _, exp := range expectedArgs {
		if !strings.Contains(outStr, exp) {
			t.Errorf("stdout missing expected argument %q:\n%s", exp, outStr)
		}
	}

	// Verify STDIN streaming
	if !strings.Contains(outStr, "STDIN:hello via stdin") {
		t.Errorf("stdout missing expected stdin stream result:\n%s", outStr)
	}

	// Verify STDERR streaming
	if !strings.Contains(errStr, "STDERR_TEST_MSG") {
		t.Errorf("stderr missing expected stream output:\n%s", errStr)
	}
}

func TestIntegration_Build_DisparateCommandAndName_CLI(t *testing.T) {
	bin := getCraftpackBinary(t)

	for _, wrap := range []bool{false, true} {
		t.Run(fmt.Sprintf("wrapper_%v", wrap), func(t *testing.T) {
			dir := t.TempDir()
			outDir := filepath.Join(dir, "dist")

			binDir := filepath.Join(dir, "payload", "bin")
			_ = os.MkdirAll(binDir, 0755)
			_ = os.WriteFile(filepath.Join(binDir, "app"), []byte("#!/bin/sh\necho running\n"), 0755)

			spec := fmt.Sprintf(`name: distinct-service
command: distinct-cli
description: Disparate name and command CLI test
maintainer: Tester <tester@example.com>
homepage: https://example.com/distinct
license: MIT
payload_dir: payload
entrypoint: bin/app
targets:
  deb:
    section: utils
    priority: optional
    wrapper: %v
`, wrap)

			specPath := filepath.Join(dir, "craftpack.yml")
			_ = os.WriteFile(specPath, []byte(spec), 0644)

			cmd := exec.Command(bin, "build", "--spec", specPath, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir)
			if out, err := cmd.CombinedOutput(); err != nil {
				t.Fatalf("build failed: %v\nOutput:\n%s", err, string(out))
			}

			entries, _ := os.ReadDir(outDir)
			var debFile string
			for _, e := range entries {
				if strings.HasSuffix(e.Name(), ".deb") {
					debFile = filepath.Join(outDir, e.Name())
					break
				}
			}
			if !strings.HasPrefix(filepath.Base(debFile), "distinct-service_1.0.0_") {
				t.Errorf("expected package filename prefix 'distinct-service_1.0.0_', got: %s", filepath.Base(debFile))
			}

			unpacked := unpackDeb(t, debFile)

			// Executable must always be at /usr/bin/distinct-cli
			if _, ok := unpacked.DataFiles["/usr/bin/distinct-cli"]; !ok {
				t.Errorf("missing executable at /usr/bin/distinct-cli in package")
			}

			// Control must have Package: distinct-service
			ctrl := string(unpacked.ControlFiles["control"])
			if !strings.Contains(ctrl, "Package: distinct-service\n") {
				t.Errorf("control file missing Package: distinct-service:\n%s", ctrl)
			}

			if wrap {
				// Launcher points to /usr/lib/distinct-service/bin/app
				launcher := string(unpacked.DataFiles["/usr/bin/distinct-cli"])
				if !strings.Contains(launcher, `REAL_PAYLOAD="/usr/lib/distinct-service/bin/app"`) {
					t.Errorf("launcher does not target /usr/lib/distinct-service/bin/app:\n%s", launcher)
				}
				if _, ok := unpacked.DataFiles["/usr/lib/distinct-service/bin/app"]; !ok {
					t.Errorf("missing private payload at /usr/lib/distinct-service/bin/app")
				}
			} else {
				// Direct binary at /usr/bin/distinct-cli
				directBin := string(unpacked.DataFiles["/usr/bin/distinct-cli"])
				if !strings.Contains(directBin, "echo running") {
					t.Errorf("direct binary content mismatch")
				}
				if _, ok := unpacked.DataFiles["/usr/lib/distinct-service/bin/app"]; ok {
					t.Errorf("entrypoint unexpectedly present in /usr/lib in direct mode")
				}
			}
		})
	}
}

func TestIntegration_Build_DryRun_WrapperTrue(t *testing.T) {
	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")
	specPath := filepath.Join(rootDir, "test/fixtures/valid-full/craftpack.yml")
	outDir := t.TempDir()

	cmd := exec.Command(bin,
		"build",
		"--spec", specPath,
		"--target", "deb",
		"--package-version", "2.1.0",
		"--output-dir", outDir,
		"--dry-run",
		"--json",
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		t.Fatalf("dry-run failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	var res struct {
		Success      bool   `json:"success"`
		PackageName  string `json:"package_name"`
		DryRun       bool   `json:"dry_run"`
	}
	if err := json.Unmarshal(stdout.Bytes(), &res); err != nil {
		t.Fatalf("failed unmarshaling json: %v\nRaw: %s", err, stdout.String())
	}
	if !res.Success || !res.DryRun || res.PackageName != "full-app" {
		t.Errorf("unexpected dry-run response: %+v", res)
	}

	// Output dir must remain empty
	entries, _ := os.ReadDir(outDir)
	if len(entries) != 0 {
		t.Errorf("dry-run unexpectedly wrote files to outDir: %v", entries)
	}

	// Stage 3 launcher synthesis must be reported in logs
	if !strings.Contains(stderr.String(), "Stage 3:") || !strings.Contains(stderr.String(), "proxy launcher") {
		t.Errorf("logs missing Stage 3 launcher synthesis notice:\n%s", stderr.String())
	}
}

func TestIntegration_Build_SingleBinary_DeeplyNestedEntrypoint_CLI(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()
	outDir := filepath.Join(dir, "dist")

	payloadDir := filepath.Join(dir, "dist-src", "deep", "nested", "path")
	_ = os.MkdirAll(payloadDir, 0755)
	binPath := filepath.Join(payloadDir, "sole-binary")
	_ = os.WriteFile(binPath, []byte("#!/bin/sh\necho sole\n"), 0755)

	spec := `name: sole-app
description: Sole binary deeply nested application
maintainer: Tester <tester@example.com>
homepage: https://example.com/sole
license: MIT
command: sole-app
payload_dir: dist-src
entrypoint: deep/nested/path/sole-binary
targets:
  deb:
    section: utils
    priority: optional
    wrapper: false
`
	specPath := filepath.Join(dir, "craftpack.yml")
	_ = os.WriteFile(specPath, []byte(spec), 0644)

	cmd := exec.Command(bin, "build", "--spec", specPath, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("build failed: %v\nOutput:\n%s", err, string(out))
	}

	entries, _ := os.ReadDir(outDir)
	var debFile string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".deb") {
			debFile = filepath.Join(outDir, e.Name())
			break
		}
	}
	unpacked := unpackDeb(t, debFile)

	// Sole binary must be directly at /usr/bin/sole-app
	if _, ok := unpacked.DataFiles["/usr/bin/sole-app"]; !ok {
		t.Fatalf("missing /usr/bin/sole-app in package")
	}

	// usr/lib must be completely omitted
	for p := range unpacked.DataFiles {
		if strings.HasPrefix(p, "/usr/lib") {
			t.Errorf("unexpected entry under /usr/lib in single binary mode: %s", p)
		}
	}

	// md5sums must have no usr/lib
	md5Str := string(unpacked.ControlFiles["md5sums"])
	if strings.Contains(md5Str, "usr/lib") {
		t.Errorf("md5sums unexpectedly contains usr/lib:\n%s", md5Str)
	}
	if !strings.Contains(md5Str, "usr/bin/sole-app") {
		t.Errorf("md5sums missing usr/bin/sole-app:\n%s", md5Str)
	}
}

func TestIntegration_Build_DpkgDebVerification_AllModes(t *testing.T) {
	dpkgPath, err := exec.LookPath("dpkg-deb")
	if err != nil {
		t.Skip("dpkg-deb not found on host, skipping native verification")
	}

	bin := getCraftpackBinary(t)
	rootDir, _ := filepath.Abs("../..")

	testCases := []struct {
		name        string
		specPath    string
		expectCmd   string
		expectVault bool
	}{
		{
			name:        "direct_minimal",
			specPath:    filepath.Join(rootDir, "test/fixtures/valid-minimal/craftpack.yml"),
			expectCmd:   "usr/bin/minimal-app",
			expectVault: false,
		},
		{
			name:        "vault_full",
			specPath:    filepath.Join(rootDir, "test/fixtures/valid-full/craftpack.yml"),
			expectCmd:   "usr/bin/full-app",
			expectVault: true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			outDir := t.TempDir()
			cmd := exec.Command(bin, "build", "--spec", tc.specPath, "--target", "deb", "--package-version", "1.0.0", "--output-dir", outDir)
			if out, err := cmd.CombinedOutput(); err != nil {
				t.Fatalf("build failed for %s: %v\nOutput:\n%s", tc.name, err, string(out))
			}

			entries, _ := os.ReadDir(outDir)
			var debFile string
			for _, e := range entries {
				if strings.HasSuffix(e.Name(), ".deb") {
					debFile = filepath.Join(outDir, e.Name())
					break
				}
			}

			// 1. Run dpkg-deb -I (control information)
			infoCmd := exec.Command(dpkgPath, "-I", debFile)
			infoOut, err := infoCmd.CombinedOutput()
			if err != nil {
				t.Errorf("dpkg-deb -I failed: %v\nOutput:\n%s", err, string(infoOut))
			}

			// 2. Run dpkg-deb -c (archive contents table)
			contentsCmd := exec.Command(dpkgPath, "-c", debFile)
			contentsOut, err := contentsCmd.CombinedOutput()
			if err != nil {
				t.Errorf("dpkg-deb -c failed: %v\nOutput:\n%s", err, string(contentsOut))
			}

			contentsStr := string(contentsOut)
			if !strings.Contains(contentsStr, tc.expectCmd) {
				t.Errorf("dpkg-deb -c missing %s:\n%s", tc.expectCmd, contentsStr)
			}
			if tc.expectVault {
				if !strings.Contains(contentsStr, "usr/lib/") {
					t.Errorf("dpkg-deb -c missing usr/lib in vault mode:\n%s", contentsStr)
				}
			} else {
				if strings.Contains(contentsStr, "usr/lib/") {
					t.Errorf("dpkg-deb -c unexpectedly contains usr/lib in direct minimal mode:\n%s", contentsStr)
				}
			}
		})
	}
}

func TestIntegration_Build_ScaffoldedDayZero_ExecutionVerification(t *testing.T) {
	bin := getCraftpackBinary(t)

	for _, wrap := range []bool{false, true} {
		t.Run(fmt.Sprintf("wrapper_%v", wrap), func(t *testing.T) {
			dir := t.TempDir()
			outDir := filepath.Join(dir, "dist")

			// 1. Scaffold project with passive stub
			payloadDir := filepath.Join(dir, "payload", "bin")
			if err := os.MkdirAll(payloadDir, 0755); err != nil {
				t.Fatalf("failed creating payload dir: %v", err)
			}
			stubPath := filepath.Join(payloadDir, "dayzero")
			stubContent := []byte("#!/bin/sh\nexit 0\n")
			if err := os.WriteFile(stubPath, stubContent, 0755); err != nil {
				t.Fatalf("failed writing stub: %v", err)
			}

			spec := fmt.Sprintf(`name: dayzero-app
description: Day-Zero scaffolded package test
maintainer: Developer <dev@example.org>
homepage: https://example.org/dayzero
license: MIT
command: dayzero-cli
payload_dir: payload
entrypoint: bin/dayzero
targets:
  deb:
    section: utils
    priority: optional
    wrapper: %v
`, wrap)
			specFile := filepath.Join(dir, "craftpack.yml")
			if err := os.WriteFile(specFile, []byte(spec), 0644); err != nil {
				t.Fatalf("failed writing spec: %v", err)
			}

			// 2. Execute CLI build
			cmd := exec.Command(bin,
				"build",
				"--spec", specFile,
				"--target", "deb",
				"--package-version", "0.1.0",
				"--output-dir", outDir,
			)
			var stdout, stderr bytes.Buffer
			cmd.Stdout = &stdout
			cmd.Stderr = &stderr

			if err := cmd.Run(); err != nil {
				t.Fatalf("build failed: %v\nSTDERR:\n%s", err, stderr.String())
			}

			// Verify STDOUT is 0 bytes
			if stdout.Len() != 0 {
				t.Errorf("stdout must be empty, got: %s", stdout.String())
			}

			// Locate generated .deb
			entries, _ := os.ReadDir(outDir)
			var debFile string
			for _, e := range entries {
				if strings.HasSuffix(e.Name(), ".deb") {
					debFile = filepath.Join(outDir, e.Name())
					break
				}
			}
			if debFile == "" {
				t.Fatalf("no .deb package found in output dir")
			}

			unpacked := unpackDeb(t, debFile)

			// 3. Inspect archive contents
			if _, ok := unpacked.DataFiles["/usr/bin/dayzero-cli"]; !ok {
				t.Fatalf("missing /usr/bin/dayzero-cli in package")
			}

			execDir := t.TempDir()
			if wrap {
				// Launcher must delegate to /usr/lib/dayzero-app/bin/dayzero
				launcherContent := string(unpacked.DataFiles["/usr/bin/dayzero-cli"])
				if !strings.Contains(launcherContent, `REAL_PAYLOAD="/usr/lib/dayzero-app/bin/dayzero"`) {
					t.Errorf("launcher does not target /usr/lib/dayzero-app/bin/dayzero:\n%s", launcherContent)
				}
				payloadData, ok := unpacked.DataFiles["/usr/lib/dayzero-app/bin/dayzero"]
				if !ok {
					t.Fatalf("missing private payload in package")
				}

				// Extract and test execution
				mockPayload := filepath.Join(execDir, "dayzero")
				_ = os.WriteFile(mockPayload, payloadData, 0755)
				adaptedLauncher := strings.Replace(launcherContent, `REAL_PAYLOAD="/usr/lib/dayzero-app/bin/dayzero"`, fmt.Sprintf(`REAL_PAYLOAD="%s"`, mockPayload), 1)
				mockLauncher := filepath.Join(execDir, "dayzero-cli")
				_ = os.WriteFile(mockLauncher, []byte(adaptedLauncher), 0755)

				runCmd := exec.Command(mockLauncher)
				runOut, err := runCmd.CombinedOutput()
				if err != nil {
					t.Errorf("executing scaffolded launcher failed: %v (output: %s)", err, string(runOut))
				}
				if len(runOut) != 0 {
					t.Errorf("expected 0-byte output from passive stub, got: %s", string(runOut))
				}
			} else {
				// Direct binary matches stub and usr/lib is completely omitted
				binData := unpacked.DataFiles["/usr/bin/dayzero-cli"]
				if !bytes.Equal(binData, stubContent) {
					t.Errorf("direct binary content mismatch")
				}
				for p := range unpacked.DataFiles {
					if strings.HasPrefix(p, "/usr/lib") {
						t.Errorf("unexpected entry under /usr/lib in direct mode: %s", p)
					}
				}

				// Test direct execution
				extractedBin := filepath.Join(execDir, "dayzero-cli")
				_ = os.WriteFile(extractedBin, binData, 0755)

				runCmd := exec.Command(extractedBin)
				runOut, err := runCmd.CombinedOutput()
				if err != nil {
					t.Errorf("executing scaffolded direct binary failed: %v (output: %s)", err, string(runOut))
				}
				if len(runOut) != 0 {
					t.Errorf("expected 0-byte output from passive stub, got: %s", string(runOut))
				}
			}
		})
	}
}

func TestIntegration_Build_SharedTemplatesAndMultiManPages(t *testing.T) {
	bin := getCraftpackBinary(t)
	dir := t.TempDir()
	outDir := filepath.Join(dir, "dist")

	// 1. Create payload
	payloadDir := filepath.Join(dir, "dist", "payload", "bin")
	if err := os.MkdirAll(payloadDir, 0755); err != nil {
		t.Fatalf("failed creating payloadDir: %v", err)
	}
	binFile := filepath.Join(payloadDir, "multi-tool")
	if err := os.WriteFile(binFile, []byte("#!/bin/sh\necho multi-tool\n"), 0755); err != nil {
		t.Fatalf("failed writing binary: %v", err)
	}

	// 2. Create templates
	tmplDir := filepath.Join(dir, "templates")
	if err := os.MkdirAll(tmplDir, 0755); err != nil {
		t.Fatalf("failed creating templates dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(tmplDir, "deb.yml"), []byte("name: deb-template\n"), 0644); err != nil {
		t.Fatalf("failed writing deb.yml template: %v", err)
	}
	if err := os.WriteFile(filepath.Join(tmplDir, "custom.yml"), []byte("name: custom-template\n"), 0644); err != nil {
		t.Fatalf("failed writing custom.yml template: %v", err)
	}

	// 3. Create manuals
	manDir := filepath.Join(dir, "docs", "manuals")
	if err := os.MkdirAll(manDir, 0755); err != nil {
		t.Fatalf("failed creating manuals dir: %v", err)
	}
	man1Content := `# multi-tool 1 "September 2026" "v1.0.0" "User Commands"
# NAME
multi-tool - multi tool test utility
# DESCRIPTION
Test utility for shared templates and multiple man pages.
`
	man5Content := `# multi-tool.conf 5 "September 2026" "v1.0.0" "File Formats"
# NAME
multi-tool.conf - configuration file for multi-tool
# DESCRIPTION
Format specification for multi-tool.conf.
`
	if err := os.WriteFile(filepath.Join(manDir, "multi-tool.1.md"), []byte(man1Content), 0644); err != nil {
		t.Fatalf("failed writing man 1: %v", err)
	}
	if err := os.WriteFile(filepath.Join(manDir, "multi-tool.conf.5.md"), []byte(man5Content), 0644); err != nil {
		t.Fatalf("failed writing man 5: %v", err)
	}

	// 4. Create craftpack.yml
	spec := `name: multi-tool
description: Multi-tool application with shared templates and man pages
maintainer: Tester <tester@example.com>
homepage: https://example.com/multi-tool
license: GPL-3.0-only
command: multi-tool
payload_dir: dist/payload
entrypoint: bin/multi-tool

templates_dir: templates

man_pages:
  - source: docs/manuals/multi-tool.1.md
    section: 1
    title: MULTI-TOOL
  - source: docs/manuals/multi-tool.conf.5.md
    section: 5
    name: multi-tool.conf
    title: MULTI-TOOL.CONF

targets:
  deb:
    section: utils
    priority: optional
    wrapper: false
    dependencies:
      - libc6 (>= 2.31)
`
	specFile := filepath.Join(dir, "craftpack.yml")
	if err := os.WriteFile(specFile, []byte(spec), 0644); err != nil {
		t.Fatalf("failed writing spec: %v", err)
	}

	cmd := exec.Command(bin,
		"build",
		"--spec", specFile,
		"--target", "deb",
		"--package-version", "2.0.0",
		"--output-dir", outDir,
		"-v",
	)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		t.Fatalf("build failed: %v\nSTDERR:\n%s", err, stderr.String())
	}

	// Locate .deb
	entries, _ := os.ReadDir(outDir)
	var debPath string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".deb") {
			debPath = filepath.Join(outDir, e.Name())
			break
		}
	}
	if debPath == "" {
		t.Fatalf("no .deb package produced")
	}

	unpacked := unpackDeb(t, debPath)

	// A. Check shared templates staged to /usr/share/multi-tool/templates/
	if _, ok := unpacked.DataFiles["/usr/share/multi-tool/templates/deb.yml"]; !ok {
		t.Errorf("missing /usr/share/multi-tool/templates/deb.yml in data.tar.gz")
	}
	if _, ok := unpacked.DataFiles["/usr/share/multi-tool/templates/custom.yml"]; !ok {
		t.Errorf("missing /usr/share/multi-tool/templates/custom.yml in data.tar.gz")
	}

	// B. Verify templates are NOT in conffiles
	if conffilesData, ok := unpacked.ControlFiles["conffiles"]; ok && len(conffilesData) > 0 {
		t.Errorf("expected DEBIAN/conffiles to be omitted or empty, got: %s", string(conffilesData))
	}

	// C. Check manual pages staged to /usr/share/man/man1/ and /usr/share/man/man5/
	if _, ok := unpacked.DataFiles["/usr/share/man/man1/multi-tool.1.gz"]; !ok {
		t.Errorf("missing /usr/share/man/man1/multi-tool.1.gz in data.tar.gz")
	}
	if _, ok := unpacked.DataFiles["/usr/share/man/man5/multi-tool.conf.5.gz"]; !ok {
		t.Errorf("missing /usr/share/man/man5/multi-tool.conf.5.gz in data.tar.gz")
	}

	// D. Check md5sums contains all entries
	md5Data, ok := unpacked.ControlFiles["md5sums"]
	if !ok {
		t.Fatalf("missing md5sums in control archive")
	}
	md5Str := string(md5Data)
	for _, expectedFile := range []string{
		"usr/bin/multi-tool",
		"usr/share/multi-tool/templates/deb.yml",
		"usr/share/multi-tool/templates/custom.yml",
		"usr/share/man/man1/multi-tool.1.gz",
		"usr/share/man/man5/multi-tool.conf.5.gz",
	} {
		if !strings.Contains(md5Str, expectedFile) {
			t.Errorf("md5sums missing expected entry %s:\n%s", expectedFile, md5Str)
		}
	}
}

