// SPDX-FileCopyrightText: 2026 Marcin Kaim
// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileComment: Generated by AI (Gemini 3.8 Flash)

package integration_test

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// findContainerEngine searches for an available, functional container runtime (podman or docker).
func findContainerEngine() (string, error) {
	for _, engine := range []string{"podman", "docker"} {
		path, err := exec.LookPath(engine)
		if err != nil {
			continue
		}
		// Verify engine can execute a minimal command
		cmd := exec.Command(path, "info")
		if err := cmd.Run(); err == nil {
			return engine, nil
		}
	}
	return "", fmt.Errorf("neither podman nor docker is available and functional")
}

// TestContainer_DebPackageInstallAndDiscovery tests the complete installation,
// PATH discoverability, asset deployment, functional CLI usage, and clean uninstallation
// of the synthesized Debian (.deb) package inside a clean Debian container.
func TestContainer_DebPackageInstallAndDiscovery(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping container installation test in -short mode")
	}

	engine, err := findContainerEngine()
	if err != nil {
		t.Skipf("skipping container install test: %v", err)
	}
	t.Logf("Using container engine: %s", engine)

	// 1. Build the self-packaged Debian archive in an isolated workspace
	wsDir, payloadBin, testVer := setupSelfPackagingWorkspace(t)
	distDir := filepath.Join(wsDir, "dist")

	buildCmd := exec.Command(payloadBin, "build",
		"--spec", "craftpack.yml",
		"--package-version", testVer,
		"--target", "deb",
		"--output-dir", distDir,
	)
	buildCmd.Dir = wsDir
	if out, err := buildCmd.CombinedOutput(); err != nil {
		t.Fatalf("failed building package for container smoke test: %v\nOutput:\n%s", err, string(out))
	}

	// 2. Locate built .deb package
	debMatches, err := filepath.Glob(filepath.Join(distDir, "craftpack_*.deb"))
	if err != nil || len(debMatches) == 0 {
		t.Fatalf("no .deb package found in %s", distDir)
	}
	debData, err := os.ReadFile(debMatches[0])
	if err != nil {
		t.Fatalf("failed reading .deb package: %v", err)
	}

	// 3. Shell script to execute inside clean debian:trixie-slim container
	containerScript := strings.TrimSpace(fmt.Sprintf(`
set -eu

echo "=== 1. Ingest and Install Debian Package ==="
cat > /tmp/craftpack.deb
dpkg -i /tmp/craftpack.deb
rm -f /tmp/craftpack.deb

echo "=== 2. Verify Binary Discoverability in PATH ==="
CRAFTPACK_BIN="$(command -v craftpack)"
test -n "${CRAFTPACK_BIN}"
test -x "${CRAFTPACK_BIN}"
test "${CRAFTPACK_BIN}" = "/usr/bin/craftpack"

echo "=== 3. Verify CLI Execution and Metadata ==="
craftpack -V
craftpack --version-info
craftpack --help

echo "=== 4. Verify System Documentation and Assets ==="
test -f /usr/share/man/man1/craftpack.1.gz
test -f /usr/share/man/man5/craftpack.yml.5.gz
test -f /usr/share/craftpack/templates/deb.yml
test -f /usr/share/doc/craftpack/copyright
test -f /usr/share/doc/craftpack/NOTICE
if [ ! -f /usr/share/doc/craftpack/changelog.gz ] && [ ! -f /usr/share/doc/craftpack/changelog.Debian.gz ]; then
    echo "ERROR: changelog archive not found in /usr/share/doc/craftpack/" >&2
    exit 1
fi

echo "=== 5. Verify Functional Out-of-the-Box Usage ==="
TEST_APP_DIR="$(mktemp -d)"
cd "${TEST_APP_DIR}"
craftpack init deb
test -f craftpack.yml
mkdir -p dist/payload/bin
touch dist/payload/bin/my-app
chmod +x dist/payload/bin/my-app
craftpack validate --strict

echo "=== 6. Verify Clean Package Removal ==="
dpkg -P craftpack
hash -r 2>/dev/null || true
if [ -f /usr/bin/craftpack ]; then
    echo "ERROR: /usr/bin/craftpack still exists after purge" >&2
    exit 1
fi
if command -v craftpack >/dev/null 2>&1; then
    echo "ERROR: craftpack command still discoverable in PATH after purge" >&2
    exit 1
fi
test ! -f /usr/share/man/man1/craftpack.1.gz
test ! -f /usr/share/craftpack/templates/deb.yml
test ! -d /usr/share/doc/craftpack

echo "=== All Container Smoke Tests Passed Successfully ==="
`))

	// 4. Launch container streaming package via STDIN (eliminates volume-mount & namespace issues)
	containerArgs := []string{
		"run", "-i", "--rm",
		"debian:trixie-slim",
		"/bin/sh", "-c", containerScript,
	}

	cmdRun := exec.Command(engine, containerArgs...)
	cmdRun.Stdin = bytes.NewReader(debData)
	var stdout, stderr bytes.Buffer
	cmdRun.Stdout = &stdout
	cmdRun.Stderr = &stderr

	if err := cmdRun.Run(); err != nil {
		t.Fatalf("container smoke test failed: %v\nSTDOUT:\n%s\nSTDERR:\n%s", err, stdout.String(), stderr.String())
	}

	t.Logf("Container smoke test output:\n%s", stdout.String())

	// Assert key verifications in stdout
	output := stdout.String()
	if !strings.Contains(output, "All Container Smoke Tests Passed Successfully") {
		t.Errorf("missing success confirmation in container output:\n%s", output)
	}
	if !strings.Contains(output, fmt.Sprintf("craftpack %s", testVer)) && !strings.Contains(output, testVer) {
		t.Errorf("version %q not reported in container output:\n%s", testVer, output)
	}
}
